### ISSUE TITLE
Sending Password reset link from User account view creates 500 server error message

### ISSUE THREAD

**Issue by kale1d0code** [grokability/snipe-it#11100] opened 2022-05-16 10:27 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When navigating to a user account and clicking the send password reset link on the right
the server creates a Type error

### Reproduction steps

1. Navigate to user account
2. Click "reset password link" button
3.
...

### Expected behavior

Password reset email to be sent to user
and next UI screen to be served by web service

### Screenshots

![Screenshot from 2022-05-16 11-13-05](https://user-images.githubusercontent.com/13876156/168574483-eb78e6f9-9a04-4247-acdf-61600dfe94a3.jpg)

### Snipe-IT Version

6.0.0

### Operating System

Alpine

### Web Server

Nginx?

### PHP Version

7.4.26

### Operating System

Ubuntu

### Browser

Chrome

### Version

101

### Error messages

```shell
/var/www/html/
TypeError
Argument 1 passed to App\Http\Controllers\Users\UsersController::App\Http\Controllers\Users\{closure}() must be an instance of App\Http\Controllers\Users\Message, instance of App\Models\User given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php on line 66
https://<REDACTED>/users/1/password


Headers
host
<REDACTED>
user-agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
content-length
47
accept
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding
gzip, deflate, br
accept-language
en-GB,en-US;q=0.9,en;q=0.8
cache-control
max-age=0
content-type
application/x-www-form-urlencoded
cookie
<REDACTED>
dnt
1
origin
https://<REDACTED>
referer
https://<REDACTED>/users/1
sec-ch-ua
" Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"
sec-ch-ua-mobile
?0
sec-ch-ua-platform
"Linux"
sec-fetch-dest
document
sec-fetch-mode
navigate
sec-fetch-site
same-origin
sec-fetch-user
?1
upgrade-insecure-requests
1
x-forwarded-for
<REDACTED>
x-forwarded-host
<REDACTED>
x-forwarded-port
443
x-forwarded-proto
https
x-forwarded-server
<REDACTED>
x-real-ip
<REDACTED>
Query String
—
Body
_token
<REDACTED>
Files
—
Session
_token
<REDACTED>
url
[]
_previous
{
  "url": "https://<REDACTED>/_debugbar/assets/stylesheets?theme=auto&v=1652481494"
}
_flash
{
  "old": [],
  "new": []
}
backUrl
https://<REDACTED>/login
login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d
1


Routing
Controller
App\Http\Controllers\Users\UsersController@sendPasswordReset
Route name
users.password
Route parameters
userId
1
Middleware
web
auth
View
View name
View data
—


User Data
Email
<REDACTED>
User data
{
    "id": 1,
    "email": "<REDACTED>",
    "activated": true,
    "activation_code": null,
    "activated_at": null,
    "last_login": "<REDACTED>",
    "first_name": "<REDACTED>",
    "last_name": "<REDACTED>",
    "created_at": "<REDACTED>",
    "updated_at": "<REDACTED>",
    "deleted_at": null,
    "website": null,
    "country": null,
    "gravatar": null,
    "location_id": 33,
    "phone": null,
    "jobtitle": null,
    "manager_id": null,
    "employee_num": null,
    "avatar": null,
    "username": "<REDACTED>",
    "notes": null,
    "company_id": 1,
    "ldap_import": 0,
    "locale": "en-GB",
    "show_in_list": 1,
    "two_factor_secret": <REDACTED>,
    "two_factor_enrolled": <REDACTED>,
    "two_factor_optin": <REDACTED>,
    "department_id": null,
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "skin": null,
    "remote": 0,
    "groups": []
}



Log
Message
Since symfony/http-foundation 5.2: The "HEADER_X_FORWARDED_ALL" constant is deprecated, use either "HEADER_X_FORWARDED_FOR | HEADER_X_FORWARDED_HOST | HEADER_X_FORWARDED_PORT | HEADER_X_FORWARDED_PROTO" or "HEADER_X_FORWARDED_AWS_ELB" or "HEADER_X_FORWARDED_TRAEFIK" constants instead. in /var/www/html/vendor/symfony/deprecation-contracts/function.php on line 25
Level
warning
Log
Message
Since symfony/http-foundation 5.2: The "HEADER_X_FORWARDED_ALL" constant is deprecated, use either "HEADER_X_FORWARDED_FOR | HEADER_X_FORWARDED_HOST | HEADER_X_FORWARDED_PORT | HEADER_X_FORWARDED_PROTO" or "HEADER_X_FORWARDED_AWS_ELB" or "HEADER_X_FORWARDED_TRAEFIK" constants instead. in /var/www/html/vendor/symfony/deprecation-contracts/function.php on line 25
Level
warning
Query
Query
select
  count(*) as aggregate
from
  `users`
Time
2.45
Connection name
mysql
Query
Query
select
  count(*) as aggregate
from
  `settings`
Time
0.41
Connection name
mysql
Query
Query
select
  *
from
  `users`
where
  `id` = ?
  and `users`.`deleted_at` is null
limit
  1
Time
0.6
Connection name
mysql
0
1
Query
Query
select
  `permission_groups`.*,
  `users_groups`.`user_id` as `pivot_user_id`,
  `users_groups`.`group_id` as `pivot_group_id`
from
  `permission_groups`
  inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id`
where
  `users_groups`.`user_id` = ?
Time
1.56
Connection name
mysql
0
1
Query
Query
select
  count(*) as aggregate
from
  `assets`
where
  `assets`.`assigned_to` is null
  and exists (
    select
      *
    from
      `status_labels`
    where
      `assets`.`status_id` = `status_labels`.`id`
      and `deployable` = ?
      and `pending` = ?
      and `archived` = ?
      and `status_labels`.`deleted_at` is null
  )
  and `assets`.`deleted_at` is null
Time
0.73
Connection name
mysql
0
1
1
0
2
0
Query
Query
select
  count(*) as aggregate
from
  `assets`
where
  `assigned_to` > ?
  and `assets`.`deleted_at` is null
Time
0.58
Connection name
mysql
0
0
Query
Query
select
  count(*) as aggregate
from
  `assets`
where
  exists (
    select
      *
    from
      `status_labels`
    where
      `assets`.`status_id` = `status_labels`.`id`
      and `deployable` = ?
      and `pending` = ?
      and `archived` = ?
      and `status_labels`.`deleted_at` is null
  )
  and `assets`.`deleted_at` is null
Time
0.52
Connection name
mysql
0
0
1
0
2
1
Query
Query
select
  count(*) as aggregate
from
  `assets`
where
  exists (
    select
      *
    from
      `status_labels`
    where
      `assets`.`status_id` = `status_labels`.`id`
      and `deployable` = ?
      and `pending` = ?
      and `archived` = ?
      and `status_labels`.`deleted_at` is null
  )
  and `assets`.`deleted_at` is null
Time
0.49
Connection name
mysql
0
0
1
1
2
0
Query
Query
select
  count(*) as aggregate
from
  `assets`
where
  exists (
    select
      *
    from
      `status_labels`
    where
      `assets`.`status_id` = `status_labels`.`id`
      and `deployable` = ?
      and `pending` = ?
      and `archived` = ?
      and `status_labels`.`deleted_at` is null
  )
  and `assets`.`deleted_at` is null
Time
0.54
Connection name
mysql
0
0
1
0
2
0
Query
Query
select
  *
from
  `users`
where
  `users`.`id` = ?
  and `users`.`deleted_at` is null
limit
  1
Time
0.87
Connection name
mysql
0
1
Query
Query
select
  *
from
  `users`
where
  `email` = ?
  and `users`.`deleted_at` is null
limit
  1
Time
0.98
Connection name
mysql
0
<REDACTED>
Query
Query
select
  *
from
  `password_resets`
where
  `email` = ?
limit
  1
Time
0.73
Connection name
mysql
0
<REDACTED>
Query
Query
delete from
  `password_resets`
where
  `email` = ?
Time
1.15
Connection name
mysql
0
<REDACTED>
Query
Query
insert into
  `password_resets` (`email`, `token`, `created_at`)
values
  (?, ?, ?)
Time
3.29
Connection name
mysql
0
<REDACTED>
1
<REDACTED>
2
2022-05-16T10:09:58.628535Z
Log
Message
TypeError: Argument 1 passed to App\Http\Controllers\Users\UsersController::App\Http\Controllers\Users\{closure}() must be an instance of App\Http\Controllers\Users\Message, instance of App\Models\User given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php on line 66 and defined in /var/www/html/app/Http/Controllers/Users/UsersController.php:628
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(66): App\Http\Controllers\Users\UsersController->App\Http\Controllers\Users\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php(144): Illuminate\Auth\Passwords\PasswordBroker->sendResetLink()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Auth\Passwords\PasswordBrokerManager->__call()
#3 /var/www/html/app/Http/Controllers/Users/UsersController.php(630): Illuminate\Support\Facades\Facade::__callStatic()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Users\UsersController->sendPasswordReset()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle()
#12 /var/www/html/app/Http/Middleware/AssetCountForSidebar.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\AssetCountForSidebar->handle()
#14 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#16 /var/www/html/app/Http/Middleware/CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#18 /var/www/html/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#20 /var/www/html/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#35 /var/www/html/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#37 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#39 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#41 /var/www/html/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#43 /var/www/html/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#48 /var/www/html/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#50 /var/www/html/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#52 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#61 /var/www/html/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /var/www/html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#67 {main}
Level
error
```

### Additional context

Service was initially setup as a docker container and is currently
I am using the alpine variant
snipe-it sits behind traefik

to update the system, I back up everything and just download new image and rebuild container, wait for update scripts/migrations to finish

**Comment by AkimoA** [comment] 2022-05-16 10:53
Just encountered the same issue , only difference here is  it runs native outside docker

**Comment by snipe** [comment] 2022-05-16 17:01
I can confirm this bug - working on it now.

**Comment by snipe** [comment] 2022-05-16 18:33
This is fixed on master now

**Closed as completed by snipe** 2022-05-16 18:33 UTC

**Comment by AkimoA** [comment] 2022-05-16 18:44
confirmed working again , thanks for the quick fix

**Comment by snipe** [comment] 2022-05-16 18:45
No problem, thanks for the quick and detailed report!

**Comment by AkimoA** [comment] 2022-05-16 18:46
i dont take kudos for the report since i just hopped the bandwagon  ;)

**Comment by snipe** [comment] 2022-05-16 18:47
We still appreciate the quick bug reports :) We obviously have been testing this extensively over the past months, but some combinations of use cases are hard to replicate, so we're always glad to be able to patch things quickly. :)

**Comment by AkimoA** [comment] 2022-05-16 18:58
Dang it its still present but not in the bulkview  but in the individual user page just getting debug logs gimme a sec

**Comment by AkimoA** [comment] 2022-05-16 19:03
So same Error as above when klicking on the individual user page  Passwort resend link button 

`#16 /var/www/html/snipeit/app/Http/Middleware/CheckForTwoFactor.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForTwoFactor->handle()
#18 /var/www/html/snipeit/app/Http/Middleware/CheckUserIsActivated.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckUserIsActivated->handle()
#20 /var/www/html/snipeit/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckLocale->handle()
#22 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#24 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#26 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#28 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#30 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#31 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#32 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#33 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#34 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#35 /var/www/html/snipeit/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Livewire\DisableBrowserCache->handle()
#37 /var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#39 /var/www/html/snipeit/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
#41 /var/www/html/snipeit/app/Http/Middleware/PreventBackHistory.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\PreventBackHistory->handle()
#43 /var/www/html/snipeit/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\SecurityHeaders->handle()
#45 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#47 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#48 /var/www/html/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForDebug->handle()
#50 /var/www/html/snipeit/app/Http/Middleware/CheckForSetup.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CheckForSetup->handle()
#52 /var/www/html/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#54 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#56 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#58 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#59 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#61 /var/www/html/snipeit/app/Http/Middleware/NoSessionStore.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\NoSessionStore->handle()
#63 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#65 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /var/www/html/snipeit/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#67 {main}  `

**Comment by snipe** [comment] 2022-05-16 19:04
Checking now

**Comment by snipe** [comment] 2022-05-16 19:08
Fixed on master now

**Comment by AkimoA** [comment] 2022-05-16 19:10
Confirmed another Winner ;)
