### ISSUE TITLE
[Feature Request]: Internal Transfer

### ISSUE THREAD

**Issue by VinnyPolar** [grokability/snipe-it#15795] opened 2024-11-11 17:37 UTC
### Is your feature request related to a problem? Please describe.

Today. considering a scenario of accessory control in a large company with many employees, it becomes necessary to lend accessories among users. Only administrators could do this., However, without a systematic request option, it becomes flawed and easy to be circumvented without any type of registration.

### Describe the solution you'd like

My solution idea is to create a button that requests the transfer of accessories/assets/licenses between users, where the admin is only notified, but the users need to accept and systematicaly change the ownership of the employees who have the accessory. Excample: Vinicus wants to transfer a sample to Joia, Vinicius opens the request and João accepts it An email is sent to the admin informing him of this change, and the system changes the user with whom that particular accessory or asset is.

### Describe alternatives you've considered

I considered the idea of keeping this informal but there will always be a failure through the user who may forget to send a messa or look for an admin to do this, because in the end it is more convenient to have less work for the users

**Comment by snipe** [comment] 2024-11-14 12:56
Duplicate of #5834

**Closed as completed by snipe** 2024-11-14 12:56 UTC
