### ISSUE TITLE
[Feature Request]: Have multiple companies, but only give users access to specific companies

### ISSUE THREAD

**Issue by kkailll** [grokability/snipe-it#12688] opened 2023-03-17 06:49 UTC
### Is your feature request related to a problem? Please describe.

People associated with specific companies need to check the assets of specific companies

### Describe the solution you'd like

I have tried multicompany access before, but it is still not suitable for the needs

### Describe alternatives you've considered

I have tried multicompany access before, but it is still not suitable for the needs

**Comment by snipe** [comment] 2023-03-19 02:22
Duplicate of #8477

**Closed as completed by snipe** 2023-03-19 02:22 UTC
