### ISSUE TITLE
Signature window offset and too small

### ISSUE THREAD

**Issue by ArcheNoah77** [grokability/snipe-it#8603] opened 2020-10-23 17:18 UTC
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When signing for an asset, the signature window cant be used full size and the signature (or the pen i write with) is offset, ca. 1cm to the right.
It happens on all devices in all browsers.

**Expected behavior**
Use the full signature window

**Screenshots**
![image](https://user-images.githubusercontent.com/25475591/97033829-3a106d00-1564-11eb-8351-e79fcf78a0f5.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 5.0.2
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 7.2.24

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Internet Exporer, New Edge

**Comment by snipe** [comment] 2020-11-02 21:59
So this is fun... 

<img width="405" alt="Screen Shot 2020-11-02 at 1 56 36 PM" src="https://user-images.githubusercontent.com/197404/97923707-48ece180-1d13-11eb-8c4d-39ff2cfe7a6a.png">

(See #8656) 

It's too big and too small. Schrödinger signature box :D 

We're looking into this.

**Comment by snipe** [comment] 2020-11-02 22:01
Can anyone tell me if this happens only on mobile v desktop?

**Comment by tarlety** [comment] 2020-11-03 07:40
The `signature-pad.min.css` is missing.

It looks like `webpack.mix.js` tries to minify `signature-pad.css`, but it's just not there.

```
mix
    .copy('./resources/assets/css/signature-pad.css', './public/css/dist')
    .minify('./public/css/build/signature-pad.css');
```

Here is my attempt to fix it (b031593) by correct copy target path and commit minified css file.

```
mix
    .copy('./resources/assets/css/signature-pad.css', './public/css/signature-pad.css')
    .minify('./public/css/signature-pad.css');
```

## Quick fix

Download the minified css file (b031593) and signature pad size shall be correct.

```
$ curl https://raw.githubusercontent.com/tarlety/snipe-it/b0315930659ded6fe1583cca21eafb2aafa744e3/public/css/build/signature-pad.min.css -o /var/www/html/public/css/signature-pad.min.css
```

**Comment by snipe** [comment] 2020-11-03 07:42
We call it directly in the file. 

https://github.com/snipe/snipe-it/blob/master/resources/views/account/accept-asset.blade.php#L14

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by snipe** [comment] 2020-11-03 07:43
If you copy `signature-pad.css` in `public/css` to `public/css/signature-pad.min.css` does that help?

**Comment by snipe** [comment] 2020-11-03 07:44
(Should not need to re-run npm for assets)

**Comment by tarlety** [comment] 2020-11-03 08:11
> If you copy `signature-pad.css` in `public/css` to `public/css/signature-pad.min.css` does that help?

On my self-hosted instance, yes it does help.
I am using snipe-it 5.0.4.

**Comment by snipe** [comment] 2020-11-03 08:13
Okay, that's on develop now, will be in the next release

**Comment by denzfarid** [comment] 2020-11-03 17:49
> The `signature-pad.min.css` is missing.
> 
> It looks like `webpack.mix.js` tries to minify `signature-pad.css`, but it's just not there.
> 
> ```
> mix
>     .copy('./resources/assets/css/signature-pad.css', './public/css/dist')
>     .minify('./public/css/build/signature-pad.css');
> ```
> 
> Here is my attempt to fix it ([b031593](https://github.com/snipe/snipe-it/commit/b0315930659ded6fe1583cca21eafb2aafa744e3)) by correct copy target path and commit minified css file.
> 
> ```
> mix
>     .copy('./resources/assets/css/signature-pad.css', './public/css/signature-pad.css')
>     .minify('./public/css/signature-pad.css');
> ```
> 
> ## Quick fix
> 
> Download the minified css file ([b031593](https://github.com/snipe/snipe-it/commit/b0315930659ded6fe1583cca21eafb2aafa744e3)) and signature pad size shall be correct.
> 
> ```
> $ curl https://raw.githubusercontent.com/tarlety/snipe-it/b0315930659ded6fe1583cca21eafb2aafa744e3/public/css/build/signature-pad.min.css -o /var/www/html/public/css/signature-pad.min.css
> ```

thanks man! I really appreciate,
I tried the quick fix
and it's working

Firefox dekstop 82.0.2 (64-bit)
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/1294403/98021688-310e7e00-1e37-11eb-9e5f-fcf019f2feb5.gif)


mobile version iphone x, portrait
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/1294403/98021870-6dda7500-1e37-11eb-87e3-c4ebec15eaba.gif)

mobile version iphone x , landscape
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/1294403/98021955-8cd90700-1e37-11eb-9b43-fa70177f8bf4.gif)

**Comment by snipe** [comment] 2020-11-03 17:51
Awesome, thanks for the confirmation!

**Closed as completed** 2020-11-03 17:51 UTC
Labels: 📝 signature

**Comment by denzfarid** [comment] 2020-11-03 17:58
> If you copy `signature-pad.css` in `public/css` to `public/css/signature-pad.min.css` does that help?

confirmed!
I also tried this way
and it works too
`cp resources/assets/css/signature-pad.css public/css/signature-pad.min.css`

![ezgif com-video-to-gif(6)](https://user-images.githubusercontent.com/1294403/98022913-cc542300-1e38-11eb-9ed3-c3dac3cd6626.gif)

**Comment by snipe** [comment] 2020-11-03 18:02
I think the issue was that the `asset-acceptance.blade.php` was looking in the wrong dir for the minified file.

`<link rel="stylesheet" href="{{ mix('css/signature-pad.min.css') }}">`
(not working)

vs 

`<link rel="stylesheet" href="{{ mix('css/build/signature-pad.min.css') }}">`
(working)

**Comment by denzfarid** [comment] 2020-11-03 18:06
> signature-pad.min.css

maybe,
because previously I did not find the file
signature-pad.min.css in the public/css directory, but when that file is added, PHEW!!! , it seems like magic

**Comment by snipe** [comment] 2020-11-03 18:09
It's the `build` part that was missing. Webpack minifies the source css from the `resources/assets/css` file, and puts it into the `public/css/build` directory, but our CSS link in that blade was omitting the `build` part of the path I think.

**Comment by denzfarid** [comment] 2020-11-03 18:13
> It's the `build` part that was missing. Webpack minifies the source css from the `resources/assets/css` file, and puts it into the `public/css/build` directory, but our CSS link in that blade was omitting the `build` part of the path I think.

absolutely right and i agree with that,

thank you so much @snipe and all team 🙏🏼

**Comment by snipe** [comment] 2020-11-03 18:14
No problem - I'm glad we could get you sorted. :)

**Comment by ArcheNoah77** [comment] 2020-11-04 07:33
Thanks for the help! I will try it in the next days.
