### ISSUE TITLE
[Feature Request]: Accessories issuing on Assets not only Users

### ISSUE THREAD

**Issue by mirso1703** [grokability/snipe-it#11426] opened 2022-06-29 15:36 UTC
### Is your feature request related to a problem? Please describe.

If you can consider unable to issue an accessory to a device, then yes.

### Describe the solution you'd like

Best would be an option to select user or asset to issue it on. Makes more sense sometimes to issue an accessory on a asset tag/device then on a user.

**Comment by snipe** [comment] 2022-06-29 16:22
Duplicate of #8763

**Closed as completed by snipe** 2022-06-29 16:22 UTC
