### ISSUE TITLE
User drop down list is not appearing while the time of checkout

### ISSUE THREAD

**Issue by v0ldemort** [grokability/snipe-it#8205] opened 2020-07-06 07:41 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode: No
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) : Yes

**Describe the bug**
I am restoring a MySQL backup in Snipeit-version v4.7.2. Everything is working fine, but while I am check-in or checkout an asset, there is no list appearing in the Location block and also user list while checking out the asset. Meanwhile, there is all users are appearing while I am opening the Peoples tab.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/65954696/86568110-01835e00-bf8a-11ea-8236-6c13ede5660e.png)

**Server (please complete the following information):**
 - Snipe-IT Version - v4.7.2
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]- ubuntu 16.04

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? - Fresh install and restoring a backup
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT- docker
- Include what you've done so far in the installation and if you got any error messages along the way. - No
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2020-07-06 18:34
We'd need the info from your app logs in order to tell you why the list isn't loading.

**Comment by snipe** [comment] 2020-07-06 22:18
This looks like a duplicate of #8192

**Closed as completed by snipe** 2020-07-06 22:18 UTC
