### ISSUE TITLE
[Feature Request]: Custom fields for licenses

### ISSUE THREAD

**Issue by kudzu3000** [grokability/snipe-it#13377] opened 2023-07-27 18:09 UTC
### Is your feature request related to a problem? Please describe.

Not related to an existing problem. 

### Describe the solution you'd like

I know this has been asked before, but I'd like to throw my two cents in.  We would love the ability to see which software has PII, MFA or 2FA capable, SSO Capable and so on.    I think a great deal many companies would find that useful.  Right now we're tracking software as assets just so we can have that ability.

**Comment by snipe** [comment] 2023-07-31 12:43
Duplicate of #4261 - this is on the v7 roadmap.

**Closed as completed by snipe** 2023-07-31 12:43 UTC
