### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by koustavshee** [grokability/snipe-it#14598] opened 2024-04-14 04:06 UTC
### Is your feature request related to a problem? Please describe.

There is no option to add custom fields in the accessoris, refillable items (i.e. other than Assets)

### Describe the solution you'd like

Please add options to add custom fields in other sections too

**Comment by snipe** [comment] 2024-04-14 15:19
Duplicate of https://github.com/snipe/snipe-it/issues/4261

**Closed as completed by snipe** 2024-04-14 15:19 UTC
