### ISSUE TITLE
[Feature Request]: Flexable reporting

### ISSUE THREAD

**Issue by ChrisWinkel** [grokability/snipe-it#14166] opened 2024-01-25 09:20 UTC
### Is your feature request related to a problem? Please describe.

Missing feature, to create and save reports settings,.

### Describe the solution you'd like

Now if you create a custom report, the second time you need to fill in everything again.
and like missing the option to say, give me all assets that are older the X years.

**Comment by snipe** [comment] 2024-01-26 19:34
Duplicate of #4616 - this is already under development

**Closed as completed by snipe** 2024-01-26 19:34 UTC
