### ISSUE TITLE
[Feature Request]: different asset tag prefix for each category

### ISSUE THREAD

**Issue by Vishnup3210** [grokability/snipe-it#13990] opened 2023-12-02 18:48 UTC
### Is your feature request related to a problem? Please describe.

is there any possible way to add different assettag prefixes for each category of assets

### Describe the solution you'd like

seperate unique prefix for each category of asests

**Comment by snipe** [comment] 2023-12-05 13:14
Duplicate of #9013

**Closed as completed by snipe** 2023-12-05 13:14 UTC
