### ISSUE TITLE
Dashboard customization

### ISSUE THREAD

**Issue by thetiagomatos** [grokability/snipe-it#9151] opened 2021-02-17 09:54 UTC
**Server (please complete the following information):**
 - Snipe-IT Version: 5.1.0
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu Server 18.04
 - Web Server: [e.g. Apache, IIS] nginx
 - PHP Version 7.2.24

**Is your feature request related to a problem? Please describe.** No.

**Describe the solution you'd like**

I would love to be able to customize the dashboard with default views. 
For example, I'd like to be able to remove everything and add things of my own. A view for furniture, like a filter but with a separate section, another for computers, another to network devices... etc.
I don't know how to describe this, but it would be amazing, this would officially be the king of asset management software.

I know it is a lot to ask but please consider it, I'm pretty sure there would be more people interested in this.

**Describe alternatives you've considered**

**Additional context**

**Comment by aitzlinger** [comment] 2021-06-22 11:19
Hi Snipe-IT Team,

I aslo would need customizeable Dasboards:

Server:

Snipe-IT Version: 4.7.8

Is your feature request related to a problem? 
--> It's not related to a Problem

A clear and concise description of what the problem is. 
--> I would need to display to a dedicated usergroup dedictated Licenses. And to an other usergroup other licenses.
So that all the usergroups know what Licenses they have.

Describe the solution you'd like
A clear and concise description of what you want to happen.
Creating simple multible dasboards with a subset of all the Licenses and add Useres with viewing permission to the Dasboards.
So that this dedicated users can access the customized dasboard browserbased and get to know what Licenses are available for them.  
So we would have the single point of "truth" for all the licensing topics

Describe alternatives you've considered
Building a Grafana Dasboard our own.

**Comment by snipe** [comment] 2022-09-28 23:46
Duplicate of https://github.com/snipe/snipe-it/issues/7297

**Closed as completed by snipe** 2022-09-28 23:46 UTC
