### ISSUE TITLE
[Feature Request]: Option to hide username in "Checked Out To" field

### ISSUE THREAD

**Issue by yetanothersys-admin** [grokability/snipe-it#12819] opened 2023-04-12 07:32 UTC
### Is your feature request related to a problem? Please describe.

It's just that with the username next to the users name in the asset list, the field gets pretty wide if the username is an email address and the name is long.
I haven't seen any option to disable this new feature.

### Describe the solution you'd like

An option to disable this somewhere. We dont really need to see the username of our users since it is their email address. It also blocks other fields that we want to show in the asset list.

### Describe alternatives you've considered

Custom column width for specific columns?

**Comment by snipe** [comment] 2023-04-12 13:40
Duplicate of #12718

**Closed as completed by snipe** 2023-04-12 13:40 UTC
