### ISSUE TITLE
[Feature Request]: Ability to optionally make standard fields mandatory

### ISSUE THREAD

**Issue by Mike-NP** [grokability/snipe-it#11519] opened 2022-07-17 19:52 UTC
### Is your feature request related to a problem? Please describe.

The new feature to "hide" optional information when creating assets is a great idea but is now causing issues when we actually require some of that information.

I need a way to make some standard fields mandatory.  

### Describe the solution you'd like

It would be great if we could have the ability to optionally make "standard" fields (eg Asset Name, Purchase Date) mandatory in a similar way to how this is done for custom fields.

### Describe alternatives you've considered

I've looked at using the required option in custom fields to do this, however it would duplicate a lot of information, and I'd need to then find a way of updating the new custom fields for all existing records.

**Comment by snipe** [comment] 2022-07-18 16:52
> I need a way to make some standard fields mandatory.

Hiring optional information didn't modify the requiredness of any of the fields, so I don't think that's related here.

**Comment by snipe** [comment] 2022-07-18 16:54
Duplicate of #7814

**Closed as completed by snipe** 2022-07-18 16:54 UTC
