### ISSUE TITLE
Feature Request: Reassign Asset

### ISSUE THREAD

**Issue by sabait** [grokability/snipe-it#9893] opened 2021-08-02 20:26 UTC
**Is your feature request related to a problem? Yes
Often times assets go directly from one use to another. The process of Checking-in, then checking out can be a bit tedious because usually after the check-in,  the page changes into a different screen and not the last asset that was checked in. 

**Describe the solution you'd like**
Having the option to ressign asset would essentially check in, then check out in one step, removing the need to search for the device a second time to check it in. 

**Describe alternatives you've considered**
It could also be part of the check-in process (new field: reassing to).

**Comment by sabait** [comment] 2021-08-02 20:44
One use case I have at the moment is that we have many assets that are assigned to People and I want to change them to location. I want to do this on a per user basis.

**Comment by Oddalmighty** [comment] 2021-08-04 16:17
I second this feature. This is something I've been trying to find a workaround for for a while. We also typically transfer assets from one user to another (namely when an employee changes worksites or leaves our agency). Each user typically has several device assigned to them (laptop, docking station, multiple monitors, headset, printer, etc.). When the user moves or leaves, we have to check in all the assets and then check them out to whoever is replacing them or to the area manager until they're reassigned. I feel like this creates so much more work and also room for error.

**Comment by adamsksbottle** [comment] 2021-09-09 20:18
+1

**Comment by snipe** [comment] 2024-08-14 11:54
Duplicate of #5834 and #8280

**Closed as completed by snipe** 2024-08-14 11:54 UTC
