### ISSUE TITLE
Error 500 when editing an asset (v6.0.1)

### ISSUE THREAD

**Issue by tikokito123** [grokability/snipe-it#11134] opened 2022-05-18 00:03 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I tried to edit an asset (does have custom fields, but not checkbox. that created versions before (5.1.5)). after saving any changes it throws me to a 500 error page.

### Reproduction steps

1.clicked on asset I have in the list
2. actions
3. edit model
4. change Notes
5. click on save
6. error 500
...

### Expected behavior

none, only at /var/log/...apache2 I can see 500

### Snipe-IT Version

6.0.1

### Operating System

linux(k8s)

### Web Server

n/a

### PHP Version

n/a

**Comment by snipe** [comment] 2022-05-18 00:07
Need error logs.

**Comment by snipe** [comment] 2022-05-18 00:07
Duplicate of #11132

**Closed as completed by snipe** 2022-05-18 00:07 UTC
