### ISSUE TITLE
API untauthorized on Windows Server/IIS

### ISSUE THREAD

**Issue by PedroSantosfrj** [grokability/snipe-it#9132] opened 2021-02-12 11:06 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Testing the API, either with Postman or cUrl, returns a unauthorized error

**To Reproduce**
  curl --location --request GET '192.168.0.24:801/api/v1/users' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer MY_API_KEY'

Returns: {"error":"Unauthorized or unauthenticated."}

Same on Postman

**Expected behavior**
It should return the users

**Screenshots**
![imagem](https://user-images.githubusercontent.com/78865173/107757670-c31f0000-6d1d-11eb-9363-fb25748b226b.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.1 - build 5811 (master)
 - OS: Windows Server 2012 r2
 - Web Server: IIS
 - PHP Version 7.4.1

**Error Messages**
{"error":"Unauthorized or unauthenticated."}

- Include any additional information you can find in `storage/logs` and your webserver's logs.
[storage_debugbar.zip](https://github.com/snipe/snipe-it/files/5971185/storage_debugbar.zip)

- Include the output from `php -m` (this should display what modules you have enabled.)
- $ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
imap
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

**Additional context**
- Is this a fresh install or an upgrade? 
- Fresh install, but since then I've ran php upgrade.php without change on the results
 
- What OS and web server you're running Snipe-IT on
Windows Server 2012 r2 with IIS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

- Include what you've done so far in the installation, and if you got any error messages along the way.
Everything in the front end seems to be working, so the only thin I did was an php upgrade.php which upgraded Snipe-IT, but did't sove the API issue.

- Indicate whether or not you've manually edited any data directly in the database
No

I've seen a similar issue here, but the problem seemed to be with Apache configuration. I'm wondering if there is something in IIS that I'm doing wrong.
I attached the only "log" file entry i could find that's generated when I try to test the API. ../storage/debugbar.

**Comment by Mariu7** [comment] 2021-02-18 22:47
@PedroSantosfrj I might be wrong but you "authorization" does not have correct setup. I don't see "Bearer" in front of token:
![image](https://user-images.githubusercontent.com/25581906/108431686-dfee9280-724b-11eb-99a7-6bec6e255a52.png)

**Comment by snipe** [comment] 2021-02-18 22:48
@Mariu7 I think your assessment is correct here. It 100% needs `Bearer ` in front of the API key.

**Comment by Mariu7** [comment] 2021-02-18 22:49
@snipe Just trying to help great product community :) Will see if that was a problem.

**Comment by snipe** [comment] 2021-02-18 22:50
@Mariu7 It was definitely *a* problem. We'll see if it's *the* problem :D 

(Meaning it would never have worked without the `Bearer ` bit, but there might be more issues.)

**Comment by PedroSantosfrj** [comment] 2021-02-19 09:11
Sorry to tell that that isn't the issue...that was just a bad screenshot I took without the Bearer in front of the API key while trying different options to get it to work.
That being said, I believe there must be some issue in the verification of the key. Is there any way I can "disable" the key verification for testing purposes?

**Comment by snipe** [comment] 2021-02-19 09:25
Not exactly sure what to suggest then. 


```
curl --location --request GET 'http://92.168.0.24:801/api/v1/users' \
--header 'Authorization: Bearer YOUR-BEARER-TOKEN' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' 
```

Should pretty much be all you need. When you ran `php upgrade.php`, what was the output?

**Comment by snipe** [comment] 2021-03-17 22:58
Duplicate of #9157

**Closed as completed by snipe** 2021-03-17 22:58 UTC
