### ISSUE TITLE
[Feature Request]: Incomplete Data Retrieval from Active Directory

### ISSUE THREAD

**Issue by erkanbuyukbayraktaroglu** [grokability/snipe-it#15254] opened 2024-08-08 15:42 UTC
### Is your feature request related to a problem? Please describe.

We have implemented LDAP integration to retrieve user information from Active Directory, including fields like Employee Number, Department, Manager, Email, Telephone Number, Job Title, Country, and Location. However, we're unable to retrieve the Company information due to the absence of a corresponding field in Snipe.

### Describe the solution you'd like

I would like to request the addition of a "Company" field in Snipe that can be integrated with Active Directory. This enhancement would allow us to automate the synchronization of company information for users, ensuring that our data is complete and up-to-date.

**Comment by snipe** [comment] 2024-08-10 17:34
Duplicate of #10698

**Closed as completed by snipe** 2024-08-10 17:34 UTC
