### ISSUE TITLE
[Feature Request]: Adding Serial Numbers to License

### ISSUE THREAD

**Issue by jguoBioXcel** [grokability/snipe-it#13449] opened 2023-08-14 18:39 UTC
### Is your feature request related to a problem? Please describe.

We purchase licenses that have a unique serial numbers per one product key.

For example, 1 product key has 5 unique serial numbers. Current "bypass" is creating multiple single licenses with different keys.

### Describe the solution you'd like

Add a similar text field as "Product Key" but name it "Serial Numbers"
![serial number field](https://github.com/snipe/snipe-it/assets/73493434/cc22e539-1cdd-4cdb-99fb-49755610a230)

### Describe alternatives you've considered

Created multiple licenses with 1 license.

![image](https://github.com/snipe/snipe-it/assets/73493434/9d07527b-18bf-4aff-aa19-1eb2f8b436aa)

**Comment by snipe** [comment] 2023-09-21 15:24
Duplicate of #4729

**Closed as completed by snipe** 2023-09-21 15:24 UTC
Labels: :heart: feature request
