### ISSUE TITLE
Dropdown menu falls

### ISSUE THREAD

**Issue by JetDanTe** [grokability/snipe-it#7974] opened 2020-04-16 20:25 UTC
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I open any dropdown menu it`s can disappear. Look at the video.

**To Reproduce**
1. Go to any edit and try to change dropdown menu values.
2. See error
3. Repeated on demo-site

**Expected behavior**
I except to choose values in menu without enabling debug mode.

**Screenshots**
[video.zip](https://github.com/snipe/snipe-it/files/4489547/video.zip)

**Server (please complete the following information):**
 - Snipe-IT Version v4.9.2 - build 4352 (master)
 - OS: Ubuntu 18.04 server
 - Web Server: Apache2
 - PHP Version 7.2.24-0ubuntu0.18.04.4
 - Laravel Version5.5.48

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome(Version 81.0.4044.92 (Official Build) (64-bit)), Firefox 75.0 (64-bit), mobile safari (latest)
 

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS13.3
 - Browser Safari
 - Latest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stack trace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **NO**
- Include any additional information you can find in `storage/logs` and your webserver's logs
`[2020-04-07 23:18:43] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order' cannot be null (SQL: insert into `custom_field_custom_fieldset` (`custom_field_id`, `custom_fieldset_id`, `order`, `required`) values (5, 2, , 0)) {"userId":1,"email":"vlad.fedyakin@apostera.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order' cannot be null (SQL: insert into `custom_field_custom_fieldset` (`custom_field_id`, `custom_fieldset_id`, `order`, `required`) values (5, 2, , 0)) at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order' cannot be null at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'order' cannot be null at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)#55 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/snipeit/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))`
 **- Errror from chrome:** all.js?id=8ec0e00558ab4b60acb8:4 GET http://apo-snipe-it/api/v1/locations/selectlist?page=14 405 (Method Not Allowed)

**Additional context**
- Is this a fresh install or an upgrade? **Fresh install from git**
- What OS and web server you're running Snipe-IT on  **Ubuntu 18.04 server**
- What method you used to install Snipe-IT **install.sh**
- Include what you've done so far in the installation and if you got any error messages along the way. **No errors, all clear**
- Indicate whether or not you've manually edited any data directly in the database **No manual edit**

**Comment by kitelessd** [comment] 2020-04-21 23:02
Getting this exact same error. Same OS Level and build version. I installed strictly from the install.sh

**Comment by JetDanTe** [comment] 2020-04-22 04:43
@snipe any ideas?

**Comment by AngstyPie** [comment] 2020-05-06 13:32
Hello!
We're having the same issue. We thought we may have done something wrong, but we installed from scratch again with the same error appearing, and then I noticed it apparently does the same thing on the Demo site.
I turned debug mode on our site and I noticed that when you click a dropdown menu there are ajax calls that keep checking new page offsets until it crashes with a "too many attempts" exception.
![image](https://user-images.githubusercontent.com/64907682/81182204-81d21680-8f7b-11ea-86ce-180a70676ee0.png)
...
![image](https://user-images.githubusercontent.com/64907682/81182302-9e6e4e80-8f7b-11ea-8c87-c53126bd1918.png)

To reproduce on the demo site I believe this would happen under any dropdown menu, but it definitely happened by going to "Create Component" and then opening "categories". Then I just wait with the dropdown menu opened for about 30 seconds or so.

On my site I noticed that the ajax requests keep counting up if I close and reopen other menus, so you don't necessarily have to have a menu open for 30 seconds to reproduce. You can also keep opening and closing dropdown menus until the exception occurs.

**Comment by JetDanTe** [comment] 2020-05-07 10:50
Hi!
I find where it is "configured". It is https://snipe-it.readme.io/reference#api-throttling
When we open any dropdown menu CPU loading jump up.
To save our system from overloading "laravel"(I don't know who exactly ) trotted request per one minute.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#api-throttling">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by AngstyPie** [comment] 2020-05-07 13:04
Thanks for the info, JetDanTe. We can certainly just crank that up. Maybe I'm naive, but it seems like the dropdown menus shouldn't loop forever stating it's "loading results".

**Comment by raychar** [comment] 2020-05-11 03:49
> Thanks for the info, JetDanTe. We can certainly just crank that up. Maybe I'm naive, but it seems like the dropdown menus shouldn't loop forever stating it's "loading results".

Agree,So many useless requests!

**Comment by peawet08** [comment] 2020-05-13 12:03
I also have this issue and when I use the dropdown lists I see cpu spike.

is there a way to limit the calls  to when a key is pressed?

**Comment by JetDanTe** [comment] 2020-05-13 14:30
> I also have this issue and when I use the dropdown lists I see cpu spike.
> 
> is there a way to limit the calls to when a key is pressed?

Yes, I`m answered below.

**Comment by peawet08** [comment] 2020-05-13 15:13
> > I also have this issue and when I use the dropdown lists I see cpu spike.
> > is there a way to limit the calls to when a key is pressed?
> 
> Yes, I`m answered below.

Hi,  The change you mentioned controls the number of calls the api can receive before it blocks responses from the api until the next minute expires.  It doesn't control the frequency of which the calls are made by the javascript linked to the dropdown.

I am currently the only user of the system.  I login and go to a dropdown.  There is no way I am clicking that dropdown 120 times in 60 secs for the api restriction to kick in and block access.  I changed this to 240 and was still just as quickly blocked.

**Comment by raychar** [comment] 2020-05-14 01:49
Hey guys, #8035  can fix the bug，but just for the moment.

**Comment by peawet08** [comment] 2020-05-14 17:00
> Hey guys, #8035 can fix the bug，but just for the moment.

EXCELLENT!  This seems to have done the trick.  

Thanks

**Comment by snipe** [comment] 2020-07-09 18:55
Closed as duplicate of #8035 - really great sleuthing here tho! The convo is happening in #8035 and we'll find a more permanent fix shortly.

**Closed as completed by snipe** 2020-07-09 18:55 UTC

**Comment by snipe** [comment] 2020-07-09 19:00
(This looks like it's probably a bug in Select2 - I haven't seen any tickets on it in their repo, but seems pretty consistent. We might offer a patch, not sure yet.)

**Comment by JetDanTe** [comment] 2020-10-19 11:08
Hello!
Will you fix this issue?
