### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by tomfortmuller** [grokability/snipe-it#12208] opened 2022-12-06 19:45 UTC
### Is your feature request related to a problem? Please describe.

Our IT department frequently use SnipeIT on a tablet (iPad) so that users can use a stylus to sign for their equipment instead of a mouse. However, it's a cumbersome process to create a password for a user, log out as admin, log in as the user, have the user sign, then sign back in as admin.

### Describe the solution you'd like

A "Login as User" link on the users index page and the single user view would speed up this process considerably.

**Comment by snipe** [comment] 2022-12-06 20:53
This is something already on deck. Duplicate of #3750

**Closed as completed by snipe** 2022-12-06 20:53 UTC
