### ISSUE TITLE
Items in create model do not show. /hardware/create

### ISSUE THREAD

**Issue by CJKIT** [grokability/snipe-it#9129] opened 2021-02-12 09:08 UTC
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode 

- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Items in create model do not show.

**To Reproduce**
1. Go to 'http://192.168.1.12/hardware/create'
2. Click on 'Create Asset Model'
3. Scroll down to 'Manufacturer:'
4. See error  : Not listed.

**Expected behavior**
Help fix the problem.

**Screenshots**
[https://drive.google.com/file/d/1lYuT1j3fMjjthmWQSjgvO2rh7KBfXEWP/view?usp=sharing](url)

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.1 - build 5811 (master)
 - OS: Windows Server 2016
 - Web Server: ISS
 - PHP Version 7.4.1
--

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Browser Crome
 - Version  88.0.4324.150

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- storage/logs [https://drive.google.com/file/d/1E5_K84DcakMXC2GhUoZC9DYsneYlX6qq/view?usp=sharing](url)
- extension=php_mysqli.dll
extension=php_mbstring.dll
extension=php_gd2.dll
extension=php_curl.dll
extension=php_exif.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_fileinfo.dll
[PHP_LDAP]
extension=php_ldap.dll

**Additional context**
- Upgrade from v5.0.10 to v5.1.1
- OS Windows Server 2016  running Snipe-IT on ISS
- What method you used to install Snipe-IT : Git-64-bit
- The database has not changed. But I just changed the Password for Administrator Go before upgrading .

**Comment by d-l-h** [comment] 2021-02-15 15:13
I am facing the exact same problem! And it does even affect the demo
<img width="601" alt="image" src="https://user-images.githubusercontent.com/20615379/107963652-bc57ed80-6fa8-11eb-8563-187c0b63614e.png">

**Comment by sw-mreyes** [comment] 2021-02-16 11:35
Might be related to a missing/removed javascript function:
![Screenshot from 2021-02-16 12-34-46](https://user-images.githubusercontent.com/49025941/108057863-7dcb3d00-7053-11eb-9355-716030c11620.png)
EDIT: Yep, formatDatalist is defined in `resources/assets/js/snipeit_modals.js`, however formatDatalistSafe is not. It is present in `resources/assets/js/snipeit.js` tho.

**Comment by sw-mreyes** [comment] 2021-02-16 12:03
I can confirm that copy-pasting the function `formatDatalistSafe` from `resources/assets/js/snipeit.js` to `resources/assets/js/snipeit_modals.js` will fix this issue. I also tried moving the `formatDatalistSafe` declaration to the top-level scope, which seemed to have no effect.

**Comment by SwimmingFish849** [comment] 2021-02-18 10:52
I am still having this issue even after applying the changes/doing a git pull

**Comment by sw-mreyes** [comment] 2021-02-18 11:02
~~Try bundling the resources with  `npm run production` (install dependencies using `npm install`)~~.
I am not a snipeit dev, so I might have screwed something up when pushing the bundled files in my PR,
also please keep in mind that my PR merely contains a temporary fix/suggestion for a fix.

**Comment by snipe** [comment] 2021-02-18 11:21
@sw-mreyes All JS that’s required should be compiled into the JS files that ship with Snipe-IT, as I’m sure you know. Advising users to mangle the compiled assets generally only ends in tears, as it means their local repos end up out of sync with the ones we issue (and then they can’t update easily, etc.)

Your PR hasn’t yet been merged. When and if it’s merged, new JS/CSS assets will be generated and issued with a release. Generally speaking we try not to copy+paste code in the JS files - especially since the modal code gets compiled into all.js.

The PR is awaiting review by one other dev on our team. If it’s approved, we’ll issue new assets.

We appreciate everyone’s patience. Git is a harsh mistress, and manually editing files that typically come with the repo can create a big headache for everyone, especially if they’re not using a development instance.

**Comment by SwimmingFish849** [comment] 2021-02-18 11:23
Thanks, I appreciate it

**Comment by snipe** [comment] 2021-02-18 12:47
@sw-mreyes Noticing your strikethrough, I wanted to mention - you didn't do anything wrong. If you opened a PR, you're a Snipe-IT dev. (Sorry lol - thems the rules). 

When you make changes to the JS or CSS in Snipe-IT and make a PR, in general, you *should* be shipping your compiled assets - partly because it makes our lives easier, and partly because at least we know your JS actually compiles :)

It's just that people who use Snipe-IT in anger who are *not* developers at all, and therefore not always that familiar with npm or composer or git can get themselves into hot water when folks try to tell them to take an action that they don't know how to back out of.

You're doing great, and we appreciate it :) It's just difficult to quantify everyone's level of experience, so we try to keep it simple.

**Closed as completed** 2021-02-19 18:05 UTC

**Comment by CJKIT** [comment] 2021-02-20 02:29
> @sw-mreyes Noticing your strikethrough, I wanted to mention - you didn't do anything wrong. If you opened a PR, you're a Snipe-IT dev. (Sorry lol - thems the rules).
> 
> When you make changes to the JS or CSS in Snipe-IT and make a PR, in general, you _should_ be shipping your compiled assets - partly because it makes our lives easier, and partly because at least we know your JS actually compiles :)
> 
> It's just that people who use Snipe-IT in anger who are _not_ developers at all, and therefore not always that familiar with npm or composer or git can get themselves into hot water when folks try to tell them to take an action that they don't know how to back out of.
> 
> You're doing great, and we appreciate it :) It's just difficult to quantify everyone's level of experience, so we try to keep it simple.

@snipe @sw-mreyes  Thanks. <3
