### ISSUE TITLE
Add plus or minus to consumables item

### ISSUE THREAD

**Issue by c1thunder** [grokability/snipe-it#10796] opened 2022-03-08 01:38 UTC
### Snipe-IT Version

5.4.1

### Operating System

Server 2016

### Web Server

IIS

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

We always restock our toners/catridges and because we have so many toners model, it is quite hassle to click edit first and then update the amount. It will be a nice feature if there is a small plus or minus quantity so we can click whatever amount we need.

### Describe the solution you'd like A clear and concise description of what you want to happen.

 It will be a nice feature if there is a small plus or minus quantity so we can click whatever amount we need. Please refer to the image about my suggestion
![2022-03-08 09_29_26-Consumables __ PCGroup Asset Management and 17 more pages - Work - Microsoft​ Ed](https://user-images.githubusercontent.com/20919681/157148544-0063e907-c46e-4c71-8ce2-9ec95a1718b9.png)

**Comment by snipe** [comment] 2022-03-08 02:19
Closing as duplicate of #5881

**Closed as completed by snipe** 2022-03-08 02:19 UTC
