### ISSUE TITLE
Snipe IT LDAP user photo integration

### ISSUE THREAD

**Issue by helpdesksulekha** [grokability/snipe-it#11348] opened 2022-06-20 10:55 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have integrated Snipe it with local AD in ldap sync and able to get users through sync. But not able to get the AD photo to Snipe it. I get only option to upload a new photo against the user.

How to bring in the AD photo through LDAP sync to Snipe IT? Can someone help?

### Reproduction steps

Need LDAP sync for AD photo for user attributes.

### Expected behavior

Need AD photo sync through LDAP

### Snipe-IT Version

Version v6.0.4 - build 8050 (master)

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4.30

### Operating System

Windows

### Browser

Chrome / Brave

**Comment by SonGokussj4** [comment] 2022-06-21 11:50
I would love this as well.

**Comment by snipe** [comment] 2022-06-22 17:08
Duplicate of #10979

**Closed as completed by snipe** 2022-06-22 17:08 UTC
