### ISSUE TITLE
[Feature Request]: Enable Cumulative Asset Count for Nested Locations

### ISSUE THREAD

**Issue by NebelKreis** [grokability/snipe-it#15752] opened 2024-10-30 07:28 UTC
### Is your feature request related to a problem? Please describe.

In Snipe-IT, under the “Locations” view, the system displays the correct asset count for each specific sub-location (such as rooms within a building). However, it does not aggregate these counts at the parent location level.

For example:
* **Main Location:** _Building 1_
  * **Sub-Locations:**
    * _Room 1_ with 2 devices
    * _Room 2_ with 2 devices

In this scenario, **Building 1** still shows 0 devices, even though **Room 1** and **Room 2** have devices assigned. This results in limited visibility into the total asset count by main location.

### Describe the solution you'd like

I would like Snipe-IT to support cumulative asset counting for nested locations. This feature should sum up the assets of all sub-locations (e.g., rooms) and display the total count at the parent location level (e.g., for buildings).

A configuration setting could be added to enable or disable this cumulative counting, giving administrators the option to turn it on or off according to their organization’s needs.

### Describe alternatives you've considered

A possible alternative is to add a new column under “Locations” named “Cumulative Assets” that displays the aggregated asset count for each location, including its sub-locations. This would make the cumulative asset total visible without modifying the individual location counts.

### Additional context

This feature would improve inventory visibility for organizations that rely on hierarchical location structures.

**Comment by snipe** [comment] 2024-10-30 09:27
Duplicate of #4546

**Closed as completed by snipe** 2024-10-30 09:27 UTC
