### ISSUE TITLE
Bulk Edit not working when only 1 asset selected

### ISSUE THREAD

**Issue by davisrael** [grokability/snipe-it#13774] opened 2023-10-21 10:51 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When selecting only 1 asset from a list of assets and attempting to bulk edit (i.e. to update Current location and default location), the values are not updated after save.

### Reproduction steps

1.Show a list of assets
2. check **one** list row
3. choose **Edit** from the top left dropdown
4. select **Go**
5. uncheck **Delete values for this asset**
6. change location
7. Leave radio **Update default location AND actual location** selected
8. press **Save**
...

### Expected behavior

Location and Default location of the selected asset are updated

### Snipe-IT Version

v6.2.3 - build 11759 (master)(hosted)

### Operating System

hosted

### Web Server

hosted

### PHP Version

hosted

### Operating System

MacOS Sonoma

### Browser

Google Chrome

### Version

118.0.5993.96 (Official Build) (x86_64)

**Comment by Godmartinz** [comment] 2023-10-23 19:44
I am unable to reproduce this. 🤔  The location continues to update.

**Comment by davisrael** [comment] 2023-10-25 19:21
Hi @Godmartinz , thx for picking this up. I'd love to illustrate, but since I'm having issues to export my screen recording from the company network (in order to compress it to a reasonable size below the 10 MB limit), I cannot provide you with some proof. Just be assured - it won't update - neither location nor default location.

**Comment by davisrael** [comment] 2023-10-25 22:05
in case there's no option to reproduce, I may produce the recording on a different machine and recode to upload here.

**Comment by snipe** [comment] 2024-07-31 08:14
I see a commit tied to this - are you still experiencing this issue on v7.0.10?

**Comment by davisrael** [comment] 2024-09-02 12:19
I can confirm this to be fixed in `v7.0.11 - build 14904 (master)(hosted)`

**Comment by marcusmoore** [comment] 2024-09-03 16:29
Thanks for the update. Going to close this 😄

**Closed as completed by marcusmoore** 2024-09-03 16:29 UTC
Labels: :question:  not sure if bug
