### ISSUE TITLE
User list not showing

### ISSUE THREAD

**Issue by anh1989** [grokability/snipe-it#11469] opened 2022-07-06 03:10 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

--help

### Reproduction steps

1. Don't show users
2.
3.
...

### Expected behavior

Don't show users

### Screenshots

![image](https://user-images.githubusercontent.com/108050291/177459709-22eddca4-277d-4d12-9d7f-0b4b422aa079.png)

### Snipe-IT Version

6.0.6

### Operating System

windown server 2016

### Web Server

iis 10

### PHP Version

7.4.30

### Additional context

I have entered a lot of user information, but it is not displayed

**Comment by anh1989** [comment] 2022-07-06 03:15
![image](https://user-images.githubusercontent.com/108050291/177460421-2363fef4-bc23-4570-8f49-d3d09a079f75.png)

**Comment by snipe** [comment] 2022-07-06 03:16
Hi - sorry you're having trouble. As mentioned in the Issue Template, we need a stack trace and browser console errors in order to help you. 

You can either provide the contents of your `storage/logs/laravel.log` (please do not attach files, just paste in the log lines that occur when you trigger the error, you can turn `APP_DEBUG=true` and then trigger the error and show us what's on the screen, or you can tail the log file. More information is available [in the documentation](https://snipe-it.readme.io/docs/getting-help).

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/advanced-debugging

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/getting-help">Getting Help</a></strong></div><div>If you're having trouble setting up Snipe-IT, don't worry!</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/advanced-debugging">Advanced Debugging</a></strong></div><div>Snipe-IT ships with the Laravel Debugbar, an amazing piece of software that lets you introspect much further into the framework and application to troubleshoot issues that may be a little harder to track down. To enable the debugbar, set the following in your .env file, and clear your config cache: ...</div></blockquote>

**Comment by snipe** [comment] 2022-07-06 03:17
(This is probably a duplicate of #11353)

**Comment by snipe** [comment] 2022-07-06 03:21
(Also next time please actually fill in the info we ask for. Error logs, whether it was an upgrade, if so, from what version to what new version, *how* you upgraded, etc.)

**Comment by pykler** [comment] 2023-05-20 16:17
I was having the same issue, deployed using Docker, the api was making http requests but the site was setup with https. The whole idea of having to manually specify an APP_URL seems bogus! could have been developed to not care how its being served.

~if this is the same issue, make sure that the APP_URL matches the url exactly of how the site is deployed.~

Edit: that didn't do anything the api is still being requested as http ... debugging further
Edit2: looks like all urls are loading as http not https, my frontend nginx was redirecting to https ... cant figure this one out
Edit3: looks like I need this, https://snipe-it.readme.io/docs/reverse-proxies

**Comment by snipe** [comment] 2023-10-26 14:18
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Closed as completed by snipe** 2023-10-26 14:18 UTC
Labels: :no_entry_sign:  not a bug
