### ISSUE TITLE
Validation bug when creating a new asset on PHP8+

### ISSUE THREAD

**Issue by Ajtak** [grokability/snipe-it#10840] opened 2022-03-19 10:34 UTC
### Debug mode

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

On PHP8+ It is not possible to create a new asset unless I fill in the Supplier field. When I click Save, I get a validation error: **The selected supplier id is invalid**.

On php7.4 this works correctly. Asset without Supplier can be created.

### Reproduction steps

1. Create new Asset
2. Fill field Company, Asset Tag, Serial, Model and Status.
3. Click to Save button. Validation error will be shown, and other filled fields is cleared.

### Expected behavior

Create asset without fill Supplier field on PHP8+

### Screenshots

![Animation](https://user-images.githubusercontent.com/4963819/159117524-adf3d8fa-4e76-4be2-80dd-b89e929513ce.gif)

### Snipe-IT Version

 v6.0.0-RC-5 - build 6772 (merges/master_down_to_develop_march_16)

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.0.12; 8.1.4

**Comment by snipe** [comment] 2022-03-19 13:43
Excellent bug report, thank you. I have absolutely no idea why that would trigger only on v8, but I’ll take a look.

**Comment by snipe** [comment] 2022-03-19 22:33
This is honestly a mystery to me.

The validation rules on assets is:

```php
protected $rules = [
        'name'            => 'max:255|nullable',
        'model_id'        => 'required|integer|exists:models,id',
        'status_id'       => 'required|integer|exists:status_labels,id',
        'company_id'      => 'integer|nullable',
        'warranty_months' => 'numeric|nullable|digits_between:0,240',
        'physical'        => 'numeric|max:1|nullable',
        'checkout_date'   => 'date|max:10|min:10|nullable',
        'checkin_date'    => 'date|max:10|min:10|nullable',
        'supplier_id'     => 'nullable|exists:suppliers,id|numeric',
        'location_id'     => 'exists:locations,id|nullable',
        'rtd_location_id' => 'exists:locations,id|nullable',
        'asset_tag'       => 'required|min:1|max:255|unique_undeleted',
        'status'          => 'integer',
        'serial'          => 'unique_serial|nullable',
        'purchase_cost'   => 'numeric|nullable',
        'next_audit_date' => 'date|nullable',
        'last_audit_date' => 'date|nullable',
    ];
```

As above, supplier ID is nullable, which should allow it to be... well.. null, and should circumvent the other requirements. I have no idea 1) why this is only happening on PHP8 and 2) why it's only happening on suppliers. We have lots of other fields that are optional that also do a cross check in the table IF an id is passed, so why that one? 

![awiens](https://user-images.githubusercontent.com/197404/159140701-f3f9b4d3-f71f-40ce-8a38-aa1edd3a6b43.jpg)

**Comment by snipe** [comment] 2022-03-19 22:39
FYI, I *can* reproduce this locally. Which is good, but still terrible because I cannot explain point one or two above. 

![test-rinse-repeat](https://user-images.githubusercontent.com/197404/159140847-87524756-0ead-4256-a759-e7f767ac9dd9.gif)

**Comment by snipe** [comment] 2022-03-19 23:21
Ugh, I figured it out. Should be fixed on `develop` now.

**Closed as completed by snipe** 2022-03-19 23:21 UTC
