### ISSUE TITLE
SAML Error 403 Forbidden

### ISSUE THREAD

**Issue by mmusah480** [grokability/snipe-it#10526] opened 2022-01-17 12:19 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I enabled SAML login on Snipe-IT, however, when I click on login via SAML, I get a Sad Panda. Error 403 error message.

### Reproduction steps

- I am on snipe it v5.3.7
- php v7.4
- Running on windows Server 2016
- SAML login enabled

### Expected behavior

When I click on login with SAML, I should be redirected to the login with Office page to enter office credentials but instead I get a 403 error page asking me to contact my administrator.

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/93027530/149768396-7c837ac8-eb19-4a98-a033-95a59fa22c17.png)

### Snipe-IT Version

5.3.0

### Operating System

windows

### Web Server

IIS

### PHP Version

7.4

### Operating System

Windows

### Browser

Chrome, Edge

### Version

97.0.4692.71

### Error messages

```shell
Sad panda. You are not authorized to do the thing. Maybe return to the dashboard, or contact your administrator.
```

**Comment by arousseaumtl** [comment] 2022-03-02 15:12
Having the same issue while running snipe-it in a docker container.. Have tried ubuntu and alpine Linux base system, and relaxing directory permissions in container. Saml setting is enabled in database, but this error is still present.

**Comment by snipe** [comment] 2022-03-21 14:51
Duplicate of #10055

**Closed as completed by snipe** 2022-03-21 14:51 UTC
Labels: saml
