### ISSUE TITLE
Snipe IT blank page windows 10 standalone testing wamp server

### ISSUE THREAD

**Issue by k3sun** [grokability/snipe-it#8812] opened 2020-11-25 08:53 UTC
![blank](https://user-images.githubusercontent.com/74946625/100203789-04351e80-2f3e-11eb-9f06-0adb398bae13.jpg)

Snipe IT blank page when i run localhost.

apache httpd.conf
</IfModule>
<virtualHost *:80>
<Directory "C:/wamp/www/snipeit/public/">
	Allow From All
	AllowOverride All
	Options +Indexes
	Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipeit/public/"
	ServerName "http://www.U8LET4O.com"
</VirtualHost>

httpd.vhosts.conf
<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot C:\wamp\www\snipeit\public
  <Directory C:\wamp\www\snipeit\public>
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
  </Directory>
</VirtualHost>

windows host file:
Copyright (c) 1993-2009 Microsoft Corp.

 102.54.94.97 rhino.acme.com # source server
 38.25.63.10 x.acme.com # x client host

 localhost name resolution is handled within DNS itself.
 127.0.0.1 localhost
 ::1 localhost
127.0.0.1 snipeit.local

127.0.0.1 localhost
127.0.0.1 activate.adobe.com
127.0.0.1 3dns-2.adobe.com #192.150.22.22

.env
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:4oMv5x4im884cGHcTmwFyLZ9VTzRzC1btDhTmgGXYCE=
APP_URL=http://www.U8LET4O.com
APP_TIMEZONE='Asia/Singapore'
APP_LOCALE=en
MAX_RESULTS=500

**Comment by snipe** [comment] 2020-11-25 08:54
Please do not post duplicate issues. Closing as duplicate of #8812

**Closed as completed by snipe** 2020-11-25 08:54 UTC
