### ISSUE TITLE
Post update import problem

### ISSUE THREAD

**Issue by enesbutunn** [grokability/snipe-it#9758] opened 2021-06-28 11:29 UTC
After the Snipe IT 5.1.7 update, the "import" screen returns the attached errors.
No data entry is made.

![image](https://user-images.githubusercontent.com/79334518/123629514-09808180-d81d-11eb-97d0-4b1a1f5e4991.png)
![image](https://user-images.githubusercontent.com/79334518/123629580-1b622480-d81d-11eb-89b2-9fb2160f241a.png)

**Comment by cloudymcduck** [comment] 2021-06-28 17:54
I have been having issues posting to Snipe using the API and just cannot get it to work. Saw this issue and confirmed the page is blank for us as well. Wondering if it's related to my issue...

**Comment by snipe** [comment] 2021-06-28 18:19
This is resolved in 5.1.8

**Closed as completed by snipe** 2021-06-28 18:19 UTC

**Comment by snipe** [comment] 2021-06-28 18:36
Duplicate of #9743
