### ISSUE TITLE
production.ERROR: undefined variable: colors_array in /var/www/snipe-it/app/Http/Controllers/Api/StatulabelsController.php:198

### ISSUE THREAD

**Issue by anonmanis** [grokability/snipe-it#9266] opened 2021-03-10 04:56 UTC
- [/] I have enabled debug mode 
- [/] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
navbar background color is white. production.ERROR: undefined variable: colors_array in /var/www/snipe-it/app/Http/Controllers/Api/StatulabelsController.php:198

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.2 (Fresh Install) and just upgraded to 5.1.3
 - OS: CentOS 7
 - Web Server: Apache/httpd
 - PHP Version 7.2.34

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
![Screenshot (10)](https://user-images.githubusercontent.com/32705894/110578293-0e022b00-8197-11eb-904b-ade97b634a2b.png)

**Additional context**
- Is this a fresh install or an upgrade? Fresh installed 5.1.2 and just upgraded to 5.1.3
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git Installation/manual

Please help me

**Comment by snipe** [comment] 2021-03-10 05:01
What happens if you set colors for all of your status labels?

**Comment by snipe** [comment] 2021-03-10 05:03
The code that sets that is 

```php
if ($statuslabel->color!='') {
    $colors_array[] = $statuslabel->color;
} else {
    $colors_array[] = Helper::defaultChartColors($default_color_count);
    $default_color_count++;
}
```

Do you not have any status labels set up?

**Comment by snipe** [comment] 2021-03-10 05:13
Go ahead and do a fresh pull from master and see if that resolves your issue.

**Comment by anonmanis** [comment] 2021-03-10 05:45
nothing change.
still got the same error
![Screenshot (12)](https://user-images.githubusercontent.com/32705894/110582237-7dc7e400-819e-11eb-90b7-0bd8364b7fca.png)

**Comment by snipe** [comment] 2021-03-10 06:13
What happens if you set colors for all of your status labels?

How many assets do you have per status label?

**Comment by anonmanis** [comment] 2021-03-10 06:19
How do I set colors for all my status labels ?

I have 6 status labels, and per status labels there are 1-3 assets

**Comment by snipe** [comment] 2021-03-10 06:19
Go to your Status Labels page and edit the status labels to give them colors.

**Comment by snipe** [comment] 2021-03-10 06:20
<img width="1157" alt="Screen Shot 2021-03-09 at 10 20 23 PM" src="https://user-images.githubusercontent.com/197404/110585462-ad86d580-8125-11eb-8df8-23b706e0a86d.png">

**Comment by anonmanis** [comment] 2021-03-10 06:41
The chart color change, but the sidebar is still same
![Screenshot (14)](https://user-images.githubusercontent.com/32705894/110587162-de0e5400-81a5-11eb-97a6-f7d983daba98.png)

I've tried changing the skin on the setting, but nothing happened/changed, I've tried custom css too and the result like this
![Screenshot (15)](https://user-images.githubusercontent.com/32705894/110587446-4cebad00-81a6-11eb-9b07-3c9e9c650dd3.png)

I just want the normal snipe-it.

**Comment by snipe** [comment] 2021-03-10 08:48
I'm currently unable to reproduce this locally, on the regular demo or the develop demo, so I'm not exactly sure what's going on here.

**Comment by deivishome** [comment] 2021-04-06 20:51
I have version 5.1.4 and it works well, i created a test label with different color from the color picker, i changed the default color theme and the header with other from the color picker and it worked well.

**Comment by snipe** [comment] 2022-11-28 20:01
I believe this was fixed many versions ago - closing for now.

**Closed as completed by snipe** 2022-11-28 20:01 UTC
