### ISSUE TITLE
500 error when adding/edditing asset models

### ISSUE THREAD

**Issue by 4kmartin** [grokability/snipe-it#12925] opened 2023-04-26 18:54 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have installed Snipe-IT on a RHEL9 server using Apache as the web server.
i installed it via the install.sh script.
The issue occurs only when adding/editing models from the asset models screen.
If i add a new model via the add Asset screen it works fine.
debug view and larivel.log  both have the following error:
`The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipeit/resources/views/models/edit.blade.php)`

link to stacktrace: https://flareapp.io/share/x7KNJdaP

also i did find a previous ticket (#11203) that had same issue described as me.
i followed those remediation steps and it did not fix the issue. the referenced file:  livewire-components.php is never created
also of note i did chmod 777 the cache file at one point and that didnt work either

some additional pictures that may or may not help:
![image](https://user-images.githubusercontent.com/46980246/234673455-75f1ee49-825a-463e-ad53-bf11dc0d8be4.png)
![image](https://user-images.githubusercontent.com/46980246/234673654-a3b1805c-8147-454c-b327-aa579af23cf7.png)

### Reproduction steps

1. go to asset models screen
2. click create new
3.
...

### Expected behavior

bring up menu to add new asset model

### Snipe-IT Version

v6.1.0 - build 10161 (master)

### Operating System

RHEL 9

### Web Server

Apache

### PHP Version

8.0.27

### Additional context

this is a fresh install

**Comment by snipe** [comment] 2023-04-26 18:55
Duplicate of #12911

**Closed as completed by snipe** 2023-04-26 18:55 UTC
