### ISSUE TITLE
[Feature Request]: New functions

### ISSUE THREAD

**Issue by pjann42** [grokability/snipe-it#13052] opened 2023-05-18 13:31 UTC
### Is your feature request related to a problem? Please describe.

Hello, I'm new here, including with Snipe-IT. I would like to implement the functionality that already exists for assets (custom fields) for consumables. Is it very complicated? How can I do that?

### Describe the solution you'd like

I would like to know if it is very complicated to implement this in the source code.

**Comment by snipe** [comment] 2023-06-08 19:03
Duplicate of https://github.com/snipe/snipe-it/issues/4261.

(Yes, it's complicated, that's why we're still working on it :) )

**Closed as completed by snipe** 2023-06-08 19:03 UTC
