### ISSUE TITLE
docker: Upload filesize

### ISSUE THREAD

**Issue by mtettke123** [grokability/snipe-it#9658] opened 2021-06-03 08:30 UTC
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode (How to enable in docker?)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using the dockler image, upload filesize is not 8 MB

**To Reproduce**
1. Go to any asset,
2. Click on 'files'
3. click on upload
4. chosse a file with a size > 5 MB (?) but < 8 MB
5. Enjoy the error message

**Expected behavior**
The file should be uploaded, no error should be displayed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/82048170/120609854-e5669600-c452-11eb-9cbe-d689b053758d.png)

**Server (please complete the following information):**
 - Snipe-IT Version: Version v5.1.5 - build 6055 (master)
 - OS: Debian 10 with docker

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: 88.0.1

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, it works in the demo:

![grafik](https://user-images.githubusercontent.com/82048170/120610357-5e65ed80-c453-11eb-99cd-3203e6bcda14.png)

- Include any additional information you can find in `storage/logs` and your webserver's logs. does not exist in docker
- Include the output from `php -m` (this should display what modules you have enabled.) (docker)

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on (docker)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) docker
- Include what you've done so far in the installation, and if you got any error messages along the way. no errors but this one
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by mtettke123** [comment] 2021-06-03 08:46
added: here is the reason. So simple.
https://github.com/snipe/snipe-it/issues/6251

PLEASE update the docker image!

**Comment by snipe** [comment] 2021-06-03 09:21
I'm happy to take a PR to resolve this.

**Comment by snipe** [comment] 2021-06-03 09:21
Closing as duplicate of #6251

**Closed as completed by snipe** 2021-06-03 09:21 UTC
