### ISSUE TITLE
[Feature Request]: MS Activedirectory Group Matting

### ISSUE THREAD

**Issue by jarrodCoombes** [grokability/snipe-it#13639] opened 2023-09-21 01:05 UTC
### Is your feature request related to a problem? Please describe.

Not related to a problem, but related to our desire to automate as many things as possible.

### Describe the solution you'd like

We would like to be able map Snipe groups to AD groups

e.g Staff ->  CN=Snipe-Staff,OU=Users,DC=domain,DC=tld

Users in that AD group, should be automatically add into the Snipe group when the AD sync runs and/or removed as needed.

This is a very similar functionality that you have with regards to locations (ie a location can be mapped to an OU).  

### Describe alternatives you've considered

Manually putting users into groups would be very time consuming, as we add and remove users constantly. At the end of the summer it's not unusual for us to have to add and remove well over 300 users.

**Comment by snipe** [comment] 2023-09-21 09:48
Duplicate of #4877

**Closed as completed by snipe** 2023-09-21 09:48 UTC
