### ISSUE TITLE
Child Assets Not Displayed

### ISSUE THREAD

**Issue by Murod-o** [grokability/snipe-it#15885] opened 2024-11-25 15:27 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When a regular user tries to view their assigned assets, not all related child assets are displayed. For example, if User "Test" has four assets assigned (Workstation, Monitor, Smartphone, and SIM Card), the hierarchy assigns the Monitor to the Workstation, which is then assigned to the user. Similarly, the SIM Card is assigned to the Smartphone, which is also assigned to the user.

However, when the user views their assets, only two parent assets (e.g., Workstation and Smartphone) are displayed. The child assets (Monitor and SIM Card) are not directly visible in the user’s view.

For admin users, the issue is partially similar: they can only see the parent assets and must click on each parent asset to view the assigned child assets. This behavior is inconsistent and seems flawed, as the expected behavior is to display all assets (including child assets) associated with the user in their view.

Interestingly, when generating a printout of assigned assets, all assets, including child assets, are displayed correctly. This discrepancy suggests that the child assets are being handled correctly in the backend but are not properly reflected in the user interface for both regular users and admins.

This inconsistency creates confusion and limits usability, making it a significant bug.

### Reproduction steps

Assign Assets to a User with Hierarchy

Assign a Workstation to a user (e.g., "User Test").
Assign a Monitor as a child asset of the Workstation.
Similarly, assign a Smartphone to the user.
Assign a SIM Card as a child asset of the Smartphone.
Log in as a Regular User

Log in with the user account to which the assets were assigned (e.g., "User Test").
View Assigned Assets

Navigate to the section where the user can view their assigned assets.
Observe the Issue

Only the parent assets (Workstation and Smartphone) are displayed.
The child assets (Monitor and SIM Card) are not directly visible in this view.
Log in as an Admin User

Log in with an admin account.
View the Same User's Assets

Navigate to the assigned assets for "User Test."
Observe that only the parent assets are listed.
To view the child assets, the admin must click on each parent asset to expand and see its child assets.
Generate a Printout of Assigned Assets

Use the print function to generate a report of the assigned assets for "User Test."
Observe that the printout correctly includes both parent and child assets.

### Expected behavior

Expected Behavior
All assets, including child assets, should be displayed directly in the user's assigned assets view, without requiring additional clicks or navigation.

Actual Behavior
Child assets are not visible in the regular user view and are only partially accessible through the admin view, creating an inconsistency in how assets are displayed.

### Screenshots

Test User
![image](https://github.com/user-attachments/assets/57f6c0c4-6f9d-4990-bec5-5a9883f098a3)
![image](https://github.com/user-attachments/assets/331c586c-22da-4141-9728-ff266775cd53)

Admin
![image](https://github.com/user-attachments/assets/ec2014d5-d16c-4857-8bd2-de8d4a7ca05c)
![image](https://github.com/user-attachments/assets/41d2c7b2-ab2e-4717-b3fd-d19f9213f69f)
![image](https://github.com/user-attachments/assets/059d95f0-a68a-4e35-be30-1ec7934ee1b7)
![image](https://github.com/user-attachments/assets/2e76bc9a-04dc-4592-8d4c-7b7031b3af9b)

### Snipe-IT Version

v7.1.14 build 15942 (g3bf33aa68)

### Operating System

Windows

### Web Server

Apache-Webserver

### PHP Version

8.1.30

### Additional context

From my perspective, this is a general bug. Since I am using a self-hosted version, I have not created a ticket for this issue. Thank you for your support!

**Comment by snipe** [comment] 2024-11-25 17:18
Duplicate of #13479

**Closed as completed by snipe** 2024-11-25 17:18 UTC
