### ISSUE TITLE
Assign multiple companies to users

### ISSUE THREAD

**Issue by jovibroz** [grokability/snipe-it#9024] opened 2021-01-19 11:50 UTC
**Server (please complete the following information):**
 - 5.0.12
 - Ubuntu 20.04.1 LTS
 - Apache 2.4.41
 - 7.4.3

**Is your feature request related to a problem? Please describe.**
Nope, just lack of functionality.

**Describe the solution you'd like**
Select companies to be assigned to normal users

**Describe alternatives you've considered**
There is no alternative

**Additional context**

**Comment by jovibroz** [comment] 2021-09-30 22:05
We needs it.

**Comment by snipe** [comment] 2021-09-30 22:06
Duplicate of #8477

**Closed as completed by snipe** 2021-09-30 22:06 UTC

**Comment by jovibroz** [comment] 2021-09-30 22:08
This shouldn't be that hard to set up.. (easy said as always :)

I think of it as folder permissions. 

User 1 have access to three companies like Pepsi, Coca Cola and Adidas.
User 2 have access to two companies Pepsi and Independent Truck Company.

Etc..

Ready for v6? Deal? :) :octocat:

**Comment by snipe** [comment] 2021-09-30 22:09
It is, unfortunately, much harder than it seems - and testing it is even more complicated. 

It will absolutely not be in v6.

**Comment by jovibroz** [comment] 2021-09-30 22:15
Damn.. :)
But for serious.. what would be the best workaround..? Until (and if) companies can be user assigned?

Multiple logins probably.. wooh.. this won't be easy to figure out how to do..

Cross access to assets belonging to different companies, without being a super-user..hmmm

Thanks for the quick reply!
