### ISSUE TITLE
parent id and id must be different importing location

### ISSUE THREAD

**Issue by wendelit** [grokability/snipe-it#8807] opened 2020-11-24 20:32 UTC
#### Expected Behavior (or desired behavior if a feature request)

the location would be added

-----

#### Actual Behavior

I get an error of:

`Checking location: B2-1
-- Searching for Parent Name: hylla-B
Parent: hylla-B - ID: 5
- Non-parent Location B2-1 could not be created: {"parent_id":["The parent id and id must be different."]}`

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
Version v5.0.5-pre - build 5457 (master)
- Version of PHP you're running
7.2.24
- Version of MySQL/MariaDB you're running
5.6.50-1debian9
- What OS and web server you're running Snipe-IT on
Docker container on rancher-os on X86 server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Triggered wen running the `php artisan snipeit:import-locations ` command

I did try to change the rules in app/Models/Location.php to not include `id|different:id` but that just produced an other error:
`{"parent_id":["The selected parent id is invalid."]}`

the csv file looks like this, and the error happens on row `B1-1 | SEK | Malmö | hylla-B | SE`

Name | Currency | City | Parent Name | Country
A1-1 | SEK | Malmö | hylla-A | SE
A1-2 | SEK | Malmö | hylla-A | SE
A1-3 | SEK | Malmö | hylla-A | SE
A2-1 | SEK | Malmö | hylla-A | SE
A2-2 | SEK | Malmö | hylla-A | SE
A2-3 | SEK | Malmö | hylla-A | SE
A3-1 | SEK | Malmö | hylla-A | SE
A3-2 | SEK | Malmö | hylla-A | SE
A3-3 | SEK | Malmö | hylla-A | SE
hylla-B | SEK | Malmö |   | SE
B1-1 | SEK | Malmö | hylla-B | SE
B1-2 | SEK | Malmö | hylla-B | SE
B1-3 | SEK | Malmö | hylla-B | SE
B2-1 | SEK | Malmö | hylla-B | SE
B2-2 | SEK | Malmö | hylla-B | SE
B2-3 | SEK | Malmö | hylla-B | SE
B3-1 | SEK | Malmö | hylla-B | SE
B3-2 | SEK | Malmö | hylla-B | SE
B3-3 | SEK | Malmö | hylla-B | SE

**Comment by snipe** [comment] 2020-11-24 20:45
Duplicate of #8794

**Closed as completed by snipe** 2020-11-24 20:45 UTC
