### ISSUE TITLE
Category Wise we can choose the asset numbering

### ISSUE THREAD

**Issue by padaki04** [grokability/snipe-it#15012] opened 2024-07-03 12:50 UTC
### Is your feature request related to a problem? Please describe.

Eg: If Asset is Computer : {Company Name}/Comp/{Number} It should start with begin
If the asset is Furniture : {Company Name}/Furcn/{Number}It should start with begin

### Describe the solution you'd like

Eg: If Asset is Computer : {Company Name}/Comp/{Number} It should start with begin
If the asset is Furniture : {Company Name}/Furcn/{Number}It should start with begin

### Describe alternatives you've considered

Eg: If Asset is Computer : {Company Name}/Comp/{Number} It should start with begin
If the asset is Furniture : {Company Name}/Furcn/{Number}It should start with begin

**Comment by snipe** [comment] 2024-07-03 21:47
Duplicate of #3286

**Closed as completed by snipe** 2024-07-03 21:47 UTC
