### ISSUE TITLE
[Feature Request]: Pull user photos from LDAP

### ISSUE THREAD

**Issue by jeffkjolley** [grokability/snipe-it#15597] opened 2024-10-01 21:00 UTC
### Is your feature request related to a problem? Please describe.

No issue.

### Describe the solution you'd like

Please consider pulling LDAP synced user's photos from the LDAP attribute 'thumbnailPhoto'.

**Comment by snipe** [comment] 2024-10-02 10:34
Duplicate of #10979

**Closed as completed by snipe** 2024-10-02 10:34 UTC
