### ISSUE TITLE
[Feature Request]: Add the Company to the LDAP Sync

### ISSUE THREAD

**Issue by Support-AEI** [grokability/snipe-it#14411] opened 2024-03-11 14:09 UTC
### Is your feature request related to a problem? Please describe.

When using full multiple-company support, users have to be assigned to their company to see the correct assets. Currently, syncing the company is not supported in the LDAP Sync.

### Describe the solution you'd like

Add a Company field to the LDAP Settings that can be synced.

**Comment by snipe** [comment] 2024-03-11 16:47
Duplicate of #14033

**Closed as completed by snipe** 2024-03-11 16:47 UTC
