### ISSUE TITLE
Upgrade to 5.0.1

### ISSUE THREAD

**Issue by CoventryIT** [grokability/snipe-it#8591] opened 2020-10-22 20:10 UTC
#### Expected Behavior (or desired behavior if a feature request)

After the upgrade the web page would load to login screen or right into the dash bored. 

-----

#### Actual Behavior

Whoops, looks like something went wrong.

-----

#### Please confirm you have done the following before posting your bug report:

- [ YES] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade
- Version of Snipe-IT you're running 
5.0.1
- Version of PHP you're running
7.2.15
- Version of MySQL/MariaDB you're running
10.0
- What OS and web server you're running Snipe-IT on
Windows Server 2012r2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(1/1) FatalThrowableErrorCall to undefined method Laravel\Passport\Passport::withCookieSerialization()
--
in AuthServiceProvider.php line 92
at AuthServiceProvider->boot()
at call_user_func_array(array(object(AuthServiceProvider), 'boot'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(AuthServiceProvider), 'boot'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(AuthServiceProvider), 'boot'), array(), null)in Container.php line 549
at Container->call(array(object(AuthServiceProvider), 'boot'))in Application.php line 792
at Application->bootProvider(object(AuthServiceProvider))in Application.php line 775
at Application->Illuminate\Foundation\{closure}(object(AuthServiceProvider), 27)
at array_walk(array(object(EventServiceProvider), object(LogServiceProvider), object(RoutingServiceProvider), object(AuthServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FormRequestServiceProvider), object(FoundationServiceProvider), object(NotificationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ViewServiceProvider), object(ServiceProvider), object(ServiceProvider), object(ServiceProvider), object(TrustedProxyServiceProvider), object(ImageServiceProvider), object(PassportServiceProvider), object(ServiceProvider), object(ServiceProvider), object(PasswordStrengthServiceProvider), object(BackupServiceProvider), object(ZiggyServiceProvider), object(DumbPasswordServiceProvider), object(AppServiceProvider), object(AuthServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(SettingsServiceProvider), object(ValidationServiceProvider), object(MacroServiceProvider), object(LdapServiceProvider), object(SamlServiceProvider), object(MailServiceProvider), object(QueueServiceProvider), object(TranslationServiceProvider), object(ValidationServiceProvider), object(HashServiceProvider)), object(Closure))in Application.php line 776
at Application->boot()in BootProviders.php line 17
at BootProviders->bootstrap(object(Application))in Application.php line 213
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Trying to open the site after the upgrade
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
This is not reproducible on the demo 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
I've never edited the database. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by CoventryIT** [comment] 2020-10-22 20:15
Previously my version was: v4.9.5

**Comment by snipe** [comment] 2020-10-22 20:17
Duplicate of #8540

**Closed as completed by snipe** 2020-10-22 20:17 UTC
