### ISSUE TITLE
error 500 when adding an asset

### ISSUE THREAD

**Issue by cmeis** [grokability/snipe-it#9153] opened 2021-02-17 11:45 UTC
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to add a new asset (the first on a fresh install), I get an 500 error when saving. The asset also is NOT added.

**To Reproduce**
Add asset, filling out serialnumber, selecting a model, filling in custom fields (associated with the model), status set to "pending".
Then clicking the save button.

**Expected behavior**
The asset should be added.

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.1 build 5811
 - OS: CentOS 7.9.2009
 - Web Server: Apache
 - PHP Version: 7.4.15

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Chrome
 - Version: 88.0.4324.150

**Error Messages**
Error message:
==========
LOG[12:41:15] LOG.error: Array to string conversion {"userId":1,"exception":{}}

Stacktrace:
=======
[12:41:15] LOG.error: ErrorException: Array to string conversion in /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Str.php:419
Stack trace:
#0 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Str.php(419): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(56): Illuminate\Support\Str::replaceArray()
#2 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/QueryException.php(39): Illuminate\Database\QueryException->formatMessage()
#3 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(670): Illuminate\Database\QueryException->__construct()
#4 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#5 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(464): Illuminate\Database\Connection->run()
#6 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): Illuminate\Database\Connection->statement()
#7 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#8 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#9 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1385): Illuminate\Database\Query\Builder->insertGetId()
#10 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(840): Illuminate\Database\Eloquent\Builder->__call()
#11 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(805): Illuminate\Database\Eloquent\Model->insertAndSetId()
#12 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(668): Illuminate\Database\Eloquent\Model->performInsert()
#13 /home/snipe-it/public_html/snipe-it/app/Models/Asset.php(196): Illuminate\Database\Eloquent\Model->save()
#14 /home/snipe-it/public_html/snipe-it/app/Http/Controllers/Assets/AssetsController.php(177): App\Models\Asset->save()
#15 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Assets\AssetsController->store()
#16 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#17 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#18 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#19 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#20 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle()
#23 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/AssetCountForSidebar.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\AssetCountForSidebar->handle()
#25 /home/snipe-it/public_html/snipe-it/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#27 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForTwoFactor->handle()
#29 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/CheckLocale.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckLocale->handle()
#31 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#33 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#35 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#37 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#39 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#40 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#41 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#42 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
#43 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#44 /home/snipe-it/public_html/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#46 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\SecurityHeaders->handle()
#48 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#50 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForDebug->handle()
#52 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/CheckForSetup.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\CheckForSetup->handle()
#54 /home/snipe-it/public_html/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
#56 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#58 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#60 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#62 /home/snipe-it/public_html/snipe-it/app/Http/Middleware/NoSessionStore.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\NoSessionStore->handle()
#64 /home/snipe-it/public_html/snipe-it/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#65 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\Cors\HandlePreflight->handle()
#66 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#68 /home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#69 /home/snipe-it/public_html/snipe-it/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle()
#70 {main}

Exception:
=======
Array to string conversion
/home/snipe-it/public_html/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Str.php#419
ErrorException
        $result = array_shift($segments);

        foreach ($segments as $segment) {
            $result .= (array_shift($replace) ?? $search).$segment;
        }

        return $result;

- YES, the error has been reproduced on the demo installation just a minute ago! Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include the output from `php -m` (this should display what modules you have enabled.)

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on: CentOS 7 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): git/composer
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by cmeis** [comment] 2021-02-17 11:52
Just saw I got the same problem on an older test installation on a dev machine. Snipe-IT version there is v5.1.0 build 5772, rest of the environment is comparable (CenntOS 7, same PHP version, ... - but a different VM!).

**Comment by nghia-dang** [comment] 2021-02-18 08:52
This also happens with v5.1.0 when adding an asset with a custom checkbox, but ticking the options when adding. It doesn't happen if no options are checked when adding.

**Comment by cmeis** [comment] 2021-02-18 08:57
Yes, just tested. The asset I wanted to add had custom checkboxes in every instance where the error occured. Removing those user defined checkboxes let me add the asset.

**Comment by nghia-dang** [comment] 2021-02-18 09:17
I'm really hoping they fix this bug for the checkboxes. There is also a directly related issue where the checkbox option labels do not show correct in the asset view or emails either ...along with this bug..  Instead it shows something like {1,1,1,1}

**Comment by LeeSharman** [comment] 2021-02-19 12:35
I get this when checking an asset out to a location. Refresh the page and the asset has checked out

**Comment by snipe** [comment] 2021-02-19 15:54
This is a known issue with checkbox custom fields. We have a few fixes on master, but  don't believe @inietov has fixed the issue completely. For right now, the solution is to not use checkboxes for custom fields.

**Comment by inietov** [comment] 2021-02-25 04:44
@cmeis @nghia-dang 
In develop branch (Version v5.1.2-pre - build 5831) the issue is already fixed. I love if you could test in that branch to see if the issue is already fixed, because I continue iterating over the checkbox type in custom fields, and more eyes are always valuable.

**Comment by LeeSharman** [comment] 2021-02-25 07:28
I upgraded to version 5.1.1 build 5811 and that seems to have resolved the issue.

**Comment by cmeis** [comment] 2021-02-25 09:35
I updated a test install to 5.1.2-pre build 5831 and the issue really seems to be fixed.
I can add assets with custom fields using checkboxes. I can also checkout those assets etc.
In my (albeit short) tests I was not able to produce any of the observed errors anymore.

Good job! ;-) (So now just waiting for this to make it into stable for our production instances.)

**Comment by inietov** [comment] 2021-02-26 00:56
Thanks for the feedback! I'm closing this now, as I think everything is in order.

**Closed as completed by inietov** 2021-02-26 00:56 UTC
Labels: :hand: bug, in progress, custom fields
