### ISSUE TITLE
error after upgrading to 5.0.7

### ISSUE THREAD

**Issue by ajoyrajan1979** [grokability/snipe-it#8802] opened 2020-11-24 00:51 UTC
#### Expected Behavior (or desired behavior if a feature request)

page should open as normal 

-----

#### Actual Behavior

Whoops Something went wrong error

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? no
- Version of Snipe-IT you're running - 4.9.5
- Version of PHP you're running - 7.4.4
- Version of MySQL/MariaDB you're running 10.2.0.5599
- What OS and web server you're running Snipe-IT on - Server2016 and IIS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error -  Yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - startup page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Failed to load resource 500
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. no
![snipeit error on uprgade](https://user-images.githubusercontent.com/56373887/100032121-534e5700-2e4b-11eb-870b-1c59af3ef9ea.png)
![snipeit error on uprgade-Browser](https://user-images.githubusercontent.com/56373887/100032124-55181a80-2e4b-11eb-969f-41a177899ffe.png)

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2020-11-24 19:44
Duplicate of #8798

**Closed as completed by snipe** 2020-11-24 19:44 UTC
