### ISSUE TITLE
[Feature Request]: Components - Multiple Serials to a component and checkout Serial 

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#13722] opened 2023-10-08 10:07 UTC
### Is your feature request related to a problem? Please describe.

Currently in Components you can have multiple Components to one component listing but only 1 serial number. 

### Describe the solution you'd like

Have a + button next to the serials, to be able to add additional Serial numbers. So if you have 5 items under the component you can add all 5 serial numbers.

Then when you checkout the item, You can 
Select Asset
Select QTY,  and also Select Serial number of the component you want to move to that asset. 
If you select more than 1 in QTY, you should be able to select the amount of qty's in serial numbers. 

https://github.com/snipe/snipe-it/assets/114973646/56849cea-8a4e-42b2-a471-80b49a97f78f

**Comment by MarcHagen** [comment] 2024-01-07 22:36
See #4421 and also there is a PR #12278.
the bottom line is, if you need serial tracking, create them as assets.

**Comment by snipe** [comment] 2024-08-17 09:34
Duplicate of #4421

**Closed as completed by snipe** 2024-08-17 09:34 UTC
