### ISSUE TITLE
[Feature Request]: can SNIPE IT add quantity to check out Consumables

### ISSUE THREAD

**Issue by jonathanroots** [grokability/snipe-it#11456] opened 2022-07-04 00:43 UTC
### Is your feature request related to a problem? Please describe.

the current version is check ONE quantity, if we check out the same item for quantity 5, we have check out 5 times. It waste time.

### Describe the solution you'd like

I used web based snipe IT. version 5.4.4 build 6829
HOPE:
Add "quantity" ________ between selected users and notes.

A few users have the same request on other threads.

Other inventory software has this feature.

see my picture below. 

Thanks you very much!

### Describe alternatives you've considered

It is simple, just add quantity ________ between users and notes. 

### Additional context

![add_qty-to-comsuable](https://user-images.githubusercontent.com/108305221/177063375-b2bf90d6-a358-4bed-ac6d-e8ae6b522f77.jpg)
![add_qty-to-comsuable](https://user-images.githubusercontent.com/108305221/177063380-283d4508-63c6-41ae-8878-37696f2f4d2c.jpg)

**Comment by snipe** [comment] 2022-07-04 00:46
This is a duplicate of other issues posted here.

#9406

**Closed as completed by snipe** 2022-07-04 00:46 UTC
