### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by eadamson-13** [grokability/snipe-it#11539] opened 2022-07-20 16:39 UTC
### Is your feature request related to a problem? Please describe.

I want to be able to sequentially assign asset tags but within an asset model... so if I have 5 Ipad pro's they will be assigned 1-5 rather than the next sequential tag in my entire inventory of items

### Describe the solution you'd like

I want to be able to sequentially assign asset tags but within an asset model... so if I have 5 Ipad pro's they will be assigned 1-5 rather than the next sequential tag in my entire inventory of items

**Comment by Isotop7** [comment] 2022-07-20 19:28
Please update the title of the feature request with a short description to identify it.

**Comment by snipe** [comment] 2022-07-20 19:32
This is kind of a duplicate of #3286 - so closing it anyway

**Closed as completed by snipe** 2022-07-20 19:32 UTC
