### ISSUE TITLE
[Feature Request]: Signature in "Assign Asset" Workflow

### ISSUE THREAD

**Issue by phw-lopa** [grokability/snipe-it#14859] opened 2024-06-12 07:17 UTC
### Is your feature request related to a problem? Please describe.

Current Situation with enforced Signatures is that I hand out an asset to a user. The User gets an Email and can put their Signature in Snipe-IT afterwards. 

### Describe the solution you'd like

I'd like to have the option to have the signature-screen (Image 1) after clicking this button: (Image2)

<img width="1375" alt="image" src="https://github.com/snipe/snipe-it/assets/108896676/7808d01e-5c93-4e13-8dfb-6f5e09cdd26f">

<img width="964" alt="image" src="https://github.com/snipe/snipe-it/assets/108896676/e04dc496-0858-4aca-aa12-2c44ce1875f9">

### Additional context

In our IT-Department we have a dedicated PC for Snipe-It where we can check-out Assets. Attached to this PC is a Signature-Pad for easier writing the signatures. I don't want to run after people not signing that they got an asset. Also I don't want my users to need to use snipe-it. It should be IT-internal and the users don't need additional help how to sign an asset.

**Comment by snipe** [comment] 2024-06-12 08:53
Duplicate of #3750. (This is planned after v7 launches on Monday)

**Closed as completed by snipe** 2024-06-12 08:53 UTC
