### ISSUE TITLE
Problem with Bulk Checkin

### ISSUE THREAD

**Issue by qu1dam** [grokability/snipe-it#15109] opened 2024-07-17 16:16 UTC
### Debug mode

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When an individual user has Accessories and/or Consumables on him and after I want to do Bulk Checkin / Delete Users by clicking on that user, a list of everything he has on him appears.
When I click on the box that I want to bulk check in on that user, I select the status and click submit. on the Dashboard and under Recent Activity as well as under user history, it does not show me the correct checkin Accessories and/or Consumables, but writes random ones that were not under that user at all.

### Reproduction steps

I've checked the above with multiple versions of the app as well as the latest available, but the problem still persists.

### Expected behavior

Under Recent Activity as well as under User History after Bulk Checkin / Delete Users it should show the exact Accessories and/or Consumables or anything else that was actually on it.

### Snipe-IT Version

v7.0.9 

### Operating System

Ubuntu, Windows

### Web Server

Apache, IIS

### PHP Version

8.1.2 or greater

**Comment by snipe** [comment] 2024-07-19 23:10
I'm not able to reproduce this. 

<img width="1388" alt="Screenshot 2024-07-20 at 12 06 44 AM" src="https://github.com/user-attachments/assets/1a60126f-d6c2-4445-bf92-792df9ed08f7">
<img width="1488" alt="Screenshot 2024-07-20 at 12 08 10 AM" src="https://github.com/user-attachments/assets/bdfa0ddb-2b42-4459-81b3-4728658a2ccb">
<img width="1482" alt="Screenshot 2024-07-20 at 12 09 31 AM" src="https://github.com/user-attachments/assets/a395e450-e1e4-426c-8436-64ec0951026e">
<img width="1491" alt="Screenshot 2024-07-20 at 12 09 55 AM" src="https://github.com/user-attachments/assets/c1cb6b3d-e9ab-4169-9510-767163faca78">
<img width="1482" alt="Screenshot 2024-07-20 at 12 10 19 AM" src="https://github.com/user-attachments/assets/f479dfd8-ea0c-4e92-90d8-6c1955444cd7">

**Comment by qu1dam** [comment] 2024-07-20 06:50
Totally clean installation, without any previous editing.
Manually added three accessories that were assigned to the user, then removed and not even the name of the exact accessories is shown, as can be seen in the photos below
![1](https://github.com/user-attachments/assets/0b634787-c935-47eb-b649-ded95f472502)
![2](https://github.com/user-attachments/assets/ffb9a2e5-1b3b-4a12-8d15-eaa4b32d71ca)
![3](https://github.com/user-attachments/assets/8f643dea-8a82-42f0-bf82-f500bf993bd5)
![4](https://github.com/user-attachments/assets/415ddd4f-6b20-4363-ba25-00c96695f195)

**Comment by snipe** [comment] 2024-07-20 06:56
Can you reproduce it on the demo? https://demo.snipeitapp.com

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by qu1dam** [comment] 2024-07-20 07:03
I want to try that before, and try right now but i can't, because Bulk Checkin has been disabled for the demo installation.

**Comment by snipe** [comment] 2024-07-20 07:16
Ah, rats, you're right. (We have to do that because folks otherwise try to delete the demo users. Sigh.)

**Comment by qu1dam** [comment] 2024-07-20 08:25
Can you temporarily enable that option or create an additional instance?
In addition, I see that you did the test only with licenses, but not with Accessories and/or Consumables

**Comment by snipe** [comment] 2024-07-20 08:26
I can't - people will do all kinds of awful things on the demo.

I did the test with everything locally, multiple times.

**Comment by snipe** [comment] 2024-07-20 08:31
https://github.com/user-attachments/assets/d85e069a-2aff-4612-a8e9-468133c5e2d1

**Comment by snipe** [comment] 2024-07-20 12:15
@marcusmoore @bzeus can you see if you can reproduce this?

**Comment by qu1dam** [comment] 2024-07-20 12:58
Thank you for your effort.
But I really don't understand how this is possible with me?
And I say, whether I installed a new instance of SnipeIT or an already used one, sometimes the Accessories and/or Consumables get mixed up and show the wrong ones that the user had after bulk checkin, while sometimes they are blank as I sent in the last photos.

**Comment by snipe** [comment] 2024-07-20 13:21
I don't know either. I showed you my video. I'll have Marcus and Birgit take a look on Monday.

**Comment by qu1dam** [comment] 2024-07-20 19:44
I have tested several times and it seems that assets Bulk Checkout works, but unfortunately not on Accessories and/or Consumables

**Comment by marcusmoore** [comment] 2024-07-23 00:46
I was able to trigger it after it seemingly working just fine for a few attempts.

Check out the blank spots in the history table on the user's page:
![user history](https://github.com/user-attachments/assets/7db0ceea-7567-4b60-aa67-c60203f8ba48)

You can see it worked ok until the 11:59PM attempt and then blanks started appearing.

Check out the `item_ids` that are being stored on the last chunk of action log items:
![database](https://github.com/user-attachments/assets/bf80c72c-67fe-410c-9409-19f3653dfdce)

Those `item_ids` don't match at all. I don't even have accessories or consumables in my database with an id higher than 4.

There is some weird mapping or something happening. Still diving in.

**Comment by qu1dam** [comment] 2024-07-23 07:16
Hello Marcus, thank you for your efforts in reproducing the error.

If you don't have a lot of items, sometimes blank spots appear.

While there are several items, although I'm not 100% sure if it has anything to do with it, the Accessories are completely mixed up and appear totally different from those that were added to the user during the bulk checkout.

**Comment by marcusmoore** [comment] 2024-07-24 21:18
FYI: I have started a fix for this on [this branch](https://github.com/marcusmoore/snipe-it/tree/fixes/bulk-checkin-logging).

**Comment by qu1dam** [comment] 2024-07-25 16:18
Great, thanks for the effort

**Comment by huifei0129** [comment] 2024-07-30 01:35
Can we "Bulk Checkin" some of the user items, not all items ?
For example, user has 100 items, but i only want to check in 90 items one time.
thank you

**Comment by marcusmoore** [comment] 2024-08-08 17:19
Thanks for reporting this @qu1dam. It is fixed in #15221 and will be included in the next release, v7.0.11, so I'm going to close this. Please re-open or tag me if you still have issues after upgrading.

@huifei0129 please open a [feature request](https://github.com/snipe/snipe-it/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.yml&title=%5BFeature+Request%5D%3A+) so we can talk about and track.

**Closed as completed by marcusmoore** 2024-08-08 17:19 UTC
