### ISSUE TITLE
Snipe-it doesn't work after proxy

### ISSUE THREAD

**Issue by konstantin-921** [grokability/snipe-it#9432] opened 2021-04-14 19:30 UTC
#### Please confirm you have done the following before posting your bug report:

- [+] I have enabled debug mode 
- [+] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am trying to deploy snipe-it helm chart on my kubernetes cluster.

Some resources like js and css have the hostname without https://, so they won't load. Any changes to APP_URL have no effect. Command "echo $APP_URL" returns value from values.yml as expected, but this has no effect on the actual URL.

Nginx proxy dont rewrite queries.

```
server {
  server_name snipeit-fl.mydomain.com;
  listen 10.0.10.10:80;
  listen 10.0.10.10:443 ssl;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

  client_max_body_size 1024m;
  proxy_read_timeout 3000s;

  ssl_session_cache    shared:SSL:10m;
  ssl_session_timeout  10m;

  ssl_protocols TLSv1.2;

  resolver 8.8.4.4 8.8.8.8 valid=300s;
  resolver_timeout 10s;

  ssl_prefer_server_ciphers on;

  ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-
  ssl_dhparam /etc/ssl/private/dhparams.pem;

  ssl_certificate<----->/etc/nginx/ssl/my.crt;
  ssl_certificate_key<->/etc/nginx/ssl/my.key;

  location / {
    more_clear_headers Server;
    proxy_pass http://cluster_1/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

}
```

Related issues - https://github.com/snipe/snipe-it/issues/8543, https://github.com/snipe/snipe-it/issues/4685

Variables are set.
APP_URL=https://snipeit-fl.mydomain.com
APP_TRUSTED_PROXIES=0.0.0.0/0 

**Screenshots**
![Selection_002](https://user-images.githubusercontent.com/34741216/114767636-8ea4e000-9d70-11eb-8b8d-4fb392ec879c.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.3
 - OS: Ubuntu in Docker container

**Comment by snipe** [comment] 2021-04-14 20:15
Duplicate of #9179

**Closed as completed by snipe** 2021-04-14 20:15 UTC
