### ISSUE TITLE
Create custom fields with data type Users, Company, Localizations, Category, etc

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#10047] opened 2021-09-06 13:28 UTC
**Server (please complete the following information):**
 - Snipe-IT Version v5.1.8 - build 6257 (develop)  
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
I need to create custom fields where I can select users Users, Company, location, etc.

**Describe the solution you'd like**
the ability to create new custom fields that use Models, Category, Users, Localizations, etc as field content

**Comment by snipe** [comment] 2021-09-14 03:21
Closing as duplicate of #4261

**Closed as completed by snipe** 2021-09-14 03:21 UTC
