### ISSUE TITLE
Signature column not selectable

### ISSUE THREAD

**Issue by narfACS** [grokability/snipe-it#10593] opened 2022-02-02 08:18 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When a user accepts a asset and signs for it, we can't view the signature column under their history. It is not selectable from the dropdown menu. It does show it was accepted with a tick and when you print report it does show it there.

### Reproduction steps

1. Assign an asset to user as test
2. They get email saying to accept
3. The click link in email and sign for asset
...

### Expected behavior

Show signature column under user history with image of signature.

### Screenshots

![snipe-it signature column](https://user-images.githubusercontent.com/98874362/152117313-562d17ff-dcca-4f62-a73c-82ee31d666b5.jpg)

### Snipe-IT Version

5.3.8

### Operating System

windows 10

### Web Server

apache

### PHP Version

8.0.10

**Comment by narfACS** [comment] 2022-02-02 08:23
Sorry, forgot to add that Request signature is selected under settings > generel settings and under categories "require users to confirm acceptance" is ticked.

**Comment by snipe** [comment] 2022-02-02 19:37
I'm unable to reproduce this locally or on the demo. :( 

In that blade code, the only thing that we look at as to whether to offer that field to be available is:

```
 @if  ($snipeSettings->require_accept_signature=='1')
                    <th class="col-md-3" data-field="signature_file" data-visible="false"  data-formatter="imageFormatter">{{ trans('general.signature') }}</th>
@endif
```

So if that setting is enabled, it should be a selectable option.

**Comment by narfACS** [comment] 2022-02-03 06:08
Thanks Snipe for the reply. Can I change that blade code to always show signature? And where is that blade code under the snipe-it folder? 

I have also unticked the required fields, restarted the server, and tried again by ticking them but still no change.

**Comment by AkimoA** [comment] 2022-05-05 15:37
Same problem here Signature in the column selector  isnt there at all . Version 5.4.4

**Comment by donron7** [comment] 2022-05-21 02:09
Same here - 6.0.1.

**Comment by snipe** [comment] 2022-05-21 04:26
There is already a PR open that fixes this - just need to be QA'd and merged.

**Closed as completed** 2022-08-25 01:12 UTC
