### ISSUE TITLE
php artisan key:generate

### ISSUE THREAD

**Issue by dst0007** [grokability/snipe-it#13559] opened 2023-09-01 08:58 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

php artisan key:generate
In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /www/wwwroot/snipe-it/vendor/laravel/frame
  work/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32

### Reproduction steps

1.php artisan key:generate
2.In Request.php line 334:
  Symfony\Component\HttpFoundation\Request::create(): Argument #1 ($uri) must be of type string, null given, called in /www/wwwroot/snipe-it/vendor/laravel/frame
  work/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php on line 32
3.
...

### Expected behavior

no

### Snipe-IT Version

6.1.2

### Operating System

Centos7.9

### Web Server

Nginx 1.22.1

### PHP Version

8.1

**Comment by snipe** [comment] 2023-09-01 11:51
Duplicate of #10572 - check your APP_URL

**Closed as completed by snipe** 2023-09-01 11:51 UTC
