### ISSUE TITLE
User to be member of multiple companies

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#10300] opened 2021-11-11 11:30 UTC
### Snipe-IT Version

5.3.1

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I'm looking at setting up a single Snipe-IT instance to manage ~20 schools. The ability to setup companies is great, as we don't want most of our schools to be able to see each other's assets.

However, I do have a few staff who work for multiple schools. They don't need to see all assets, so I don't really want to give them super admin. equally, there are other staff who only need access to individual schools, so creating a company to cover multiple schools is not really an option.

### Describe the solution you'd like A clear and concise description of what you want to happen.

What would be great is having the ability to grant individual users access to multiple companies.

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Unknown.  I'm a new customer.

**Comment by JoriPS1** [comment] 2021-11-15 17:18
+1

This would be great for my instance as well. I'm in a situation where I only have 1 company, however there are other groups that maintain their own software licenses.  It would be great to allow them to assign software licenses to users of the broader company, while not allowing others groups to see the license information.  Currently have to make them a super admin or get rid of the idea of segregating everything.

**Comment by achitofel** [comment] 2022-02-02 15:59
+1

**Comment by snipe** [comment] 2023-03-19 02:22
Duplicate of #8477

**Closed as completed by snipe** 2023-03-19 02:22 UTC
