### ISSUE TITLE
very annoying consumables bug

### ISSUE THREAD

**Issue by szalayzoli11** [grokability/snipe-it#10865] opened 2022-03-23 19:57 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you tick image in consumables dont stay there when you click out to other categories and click back!

### Reproduction steps

1.
2.
3.
...
...

### Expected behavior

appering image at all time

### Snipe-IT Version

all

### Operating System

win

### Web Server

apache2

### PHP Version

7.4

**Comment by snipe** [comment] 2022-03-29 11:17
Are you talking about the column selections? This is a known bug. Closing as duplicate of #10141

**Closed as completed by snipe** 2022-03-29 11:17 UTC
