### ISSUE TITLE
Kiosk mode 

### ISSUE THREAD

**Issue by Glorou** [grokability/snipe-it#11013] opened 2022-05-04 23:14 UTC
### Snipe-IT Version

5.4.3

### Operating System

Debian

### Web Server

Apache

### PHP Version

7.4.29

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I want my admins to check things out as themselves quickly when using a kiosk workstation instead of having to login themselves.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Add a setting to specify a "kiosk" account that is an admin but will force the following:
When checking out an item it will display an additional field to select an administrator(list all admin or super admin users)
selecting this field would be mandatory and would then impersonate that administrator for audit purposes and the kiosk account would not be recorded as the Admin for checkout actions.

**Comment by snipe** [comment] 2022-05-04 23:30
Duplicate of #5994

**Closed as completed by snipe** 2022-05-04 23:30 UTC
