### ISSUE TITLE
[Feature Request]: listing Assets from Location included child locations

### ISSUE THREAD

**Issue by iaef445** [grokability/snipe-it#12280] opened 2022-12-27 09:34 UTC
### Is your feature request related to a problem? Please describe.

Would it be possible to list & export assets from a location and its child locations?

### Describe the solution you'd like

Add in export and in "Assigned Assets" of a location a checkbox "include child locations" where all assets of this location and child locations of this locations be listed

**Comment by snipe** [comment] 2024-10-30 09:29
Duplicate of #4546

**Closed as completed by snipe** 2024-10-30 09:29 UTC
