### ISSUE TITLE
Deactivated users receive HTTP 500 error page on login

### ISSUE THREAD

**Issue by uberbrady** [grokability/snipe-it#8739] opened 2020-11-13 20:02 UTC
I've seen several reports of this now, here on GH as well as with our own customers.

If a user is deactivated, when they try to log in - presuming, of course, that they got their username and password right - they receive a 500 error. A helpful error page might be nicer and less confusing to our end-users and their admins. Probably with some verbiage (some of which may be pre-defined in Laravel) - like, "Your user account is not activated, so you cannot log in."

**Comment by snipe** [comment] 2020-11-13 20:04
I'm on it - ty for the heads up

**Comment by snipe** [comment] 2020-11-13 20:04
@uberbrady can you point me to an existing issue? Hopefully one with a stack trace? If not, I'll just see if I can reproduce locally

**Comment by uberbrady** [comment] 2020-11-13 20:09
Oh, this may also *only* have to do with LDAP users - I may have even found the line:

https://github.com/snipe/snipe-it/blob/644084658a9f838039711b74d15b9b27e7875d4f/app/Services/LdapAd.php#L148

**Comment by snipe** [comment] 2020-11-13 21:31
Closing as duplicate of #8689

**Closed as completed by snipe** 2020-11-13 21:31 UTC
Labels: :hand: bug, auth
