### ISSUE TITLE
[Feature Request]: Set asset tags prefix by categories

### ISSUE THREAD

**Issue by yunjie-yao** [grokability/snipe-it#11057] opened 2022-05-12 02:30 UTC
### Is your feature request related to a problem? Please describe.

Now the asset tag prefix can only set one, but I want to set different prifix for different categories.
<img width="612" alt="1652322244(1)" src="https://user-images.githubusercontent.com/46948556/167979609-3c10a8e6-3be3-493e-90ef-a7c67a379ffb.png">
For example: I have two categories

1. laptop
2. server

For laptop, I want to set the asset tags prefix as "LAP"
For server, I want to set the asset tags prefix as "SER"
etc...

### Describe the solution you'd like

Add new field to categories as tag prefix, so we can set prefix from categories.

**Comment by snipe** [comment] 2022-05-13 12:36
Duplicate of #9013

**Closed as completed by snipe** 2022-05-13 12:36 UTC
