### ISSUE TITLE
Dropdown Menus Aren't Working

### ISSUE THREAD

**Issue by LSNIGHTSHOT** [grokability/snipe-it#12839] opened 2023-04-14 16:50 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When creating a new asset, license, accessory, or anything for that matter. None of the drop down menus are populating

### Reproduction steps

1. Create New
2. Select Asset
3. Select Company dropdown 
4. Never loads
...

### Expected behavior

To load preconfigured options

### Screenshots

<img width="748" alt="Screenshot 2023-04-14 at 11 49 21 AM" src="https://user-images.githubusercontent.com/73556517/232107108-a3f9b844-29c9-471d-bddf-2c1852c1b10d.png">

### Snipe-IT Version

6.1.0

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

8.0.28

### Operating System

Mac

### Browser

Edge

### Version

112.0.1722.46

**Comment by snipe** [comment] 2023-04-16 07:36
Can you reproduce this on the demo?

**Comment by snipe** [comment] 2023-04-16 07:37
Duplicate of #12829

**Closed as completed by snipe** 2023-04-16 07:37 UTC
