### ISSUE TITLE
[Feature Request]: custom fields on Accessory

### ISSUE THREAD

**Issue by OdinMegan** [grokability/snipe-it#14176] opened 2024-01-26 22:42 UTC
### Is your feature request related to a problem? Please describe.

When Checkout Accessory i use the notes field for a serial number

### Describe the solution you'd like

Custom field option for assets also for a Accessory

**Comment by snipe** [comment] 2024-01-27 20:02
Duplicate of #4261

**Closed as completed by snipe** 2024-01-27 20:02 UTC
