### ISSUE TITLE
Ready to Deploy view shows deployed assets if Search filter applied

### ISSUE THREAD

**Issue by htoogethr** [grokability/snipe-it#13523] opened 2023-08-24 12:37 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When you open the "Ready to Deploy" asset view, only deployable but not deployed assets show up.
However, as soon as you use the Search field, the results also contain deployed assets.

### Reproduction steps

1. Have assets with state "Deployable"
2. Check out some of them
3. Go to "Ready to Deploy" view from sidebar menu (filter: `status=RTD`)
4. As expected, only assets show up with deployable statuses that are not checked out
5. Enter a query in Search field and search

### Expected behavior

Only assets matching the following conditions show up:
* Matching the Search query
* Having a deployable status
* Not being deployed / checked out

### Snipe-IT Version

v6.1.1 build 10847 (g2ac4449ea)

### Operating System

CloudLinux 7.9

### Web Server

Apache 2.4.57

### PHP Version

8.1.22

**Comment by snipe** [comment] 2023-08-28 11:45
Duplicate of #13380 - this was already fixed on master.

**Closed as completed by snipe** 2023-08-28 11:45 UTC
