### ISSUE TITLE
Edit Model, Resets Custom Fields (Even if using same fieldset)

### ISSUE THREAD

**Issue by jayavman** [grokability/snipe-it#15249] opened 2024-08-08 01:57 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If you go to an asset and change the model it then resets the custom fields

### Reproduction steps

1.Edit Asset
2. Edit model to a different model
3. as soon as you change the model on the page, it resets the custom fields and you have to reenter the information

...

### Expected behavior

Keep custom fields and not need to re-enter information ** If its using the same fieldset as the previous model**

### Snipe-IT Version

v7.0.5 build 14092 (g294fb1f77)

### Operating System

almalinux

### Web Server

apache

### PHP Version

8.1.29

**Comment by snipe** [comment] 2024-08-08 11:14
How often does this come up? Seems like a fringe case

**Comment by jayavman** [comment] 2024-08-08 11:19
It comes up a lot. So when we do a lifecycle change on an asset. We keep the same asset number but update the asset with the new item. Majority of the time it has a new model change. When you do this the custom fields will reset.

**Comment by snipe** [comment] 2024-08-08 11:30
When you say asset number, you mean tag? What’s the reason for this workflow? It seems like that defeats a lot of the purpose of the system, since it’s now an entirely different object. (I’m not judging, just trying to understand the reason.)

**Comment by jayavman** [comment] 2024-08-08 11:38
How we do things is. Our asset tags remain forever.

Eg. 

Asset tag is 12082
We have a Panasonic projector dz120

But when that is end of life we update the information of that asset to the new projector 
Panasonic dz890

With new serial information and custom field data that needs to be modified.
Then in the history we can see that asset id has had 2 projector changes in the history. 

We do this to track change out of items as asset ids can never be changed.

Issue is that now if we change the model information it removes all the information in the custom field when you change the model

**Comment by snipe** [comment] 2024-08-08 11:48
Huh - I’ve never heard of a workflow like that. Guess there’s still room for surprises in this project. Thanks for sharing that workflow with us.

**Comment by snipe** [comment] 2024-08-08 11:50
@marcusmoore @Godmartinz can one of you two take a look at this since I’m on vacation?

**Comment by marcusmoore** [comment] 2024-08-08 16:52
I believe this is the same as #15007. I started some work on it already and can pick it back up.

**Comment by snipe** [comment] 2024-10-03 09:35
Duplicate of https://github.com/snipe/snipe-it/issues/15007

**Closed as completed by snipe** 2024-10-03 09:35 UTC
