### ISSUE TITLE
Import View Not Showing (v5.1.7)

### ISSUE THREAD

**Issue by isaacsabas** [grokability/snipe-it#9748] opened 2021-06-25 12:12 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading my instance from v5.1.5 to v5.1.7, everything is working fine except for the Import page. When I click on it, it doesn't load any.

**To Reproduce**
1. From version 5.1.5, upgrade via Git to v5.1.7
2. Logout then logged back in, all is fine.
3. Clicked on the Import menu, and the Import content (div app content) doesn't load anything.

**Expected behavior**
The import page should be displayed.

**Screenshots**
![Screenshot from 2021-06-25 19-58-10](https://user-images.githubusercontent.com/86474211/123421947-1c623e80-d5f0-11eb-967b-569e7cae80e0.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.7
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.4.12

**Desktop (please complete the following information):**

**Error Messages**
[2021-06-25 03:52:47] production.ERROR: Unable to encode attribute [first_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.

[2021-06-25 03:52:47] production.ERROR: Illuminate\Database\Eloquent\JsonEncodingException: Unable to encode attribute [first_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded. in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/JsonEncodingException.php:33#20

**Additional context**
- Intuz Instance (AWS AMI)

**Comment by ghapstech** [comment] 2021-06-25 12:37
Same issue here after upgrade from 5.1.5 to 5.1.7

**Comment by snipe** [comment] 2021-06-25 14:12
Huh, we didn’t touch the importer at all in the past few versions, but I’ll take a look

**Comment by MuratDoganer** [comment] 2021-06-26 16:33
Can confirm this as well, also cli importer is not working either (it says successful, but nothing appears)

**Comment by aliaxonbaig** [comment] 2021-06-27 06:49
Same issue, Importer not available.

**Comment by isaacsabas** [comment] 2021-06-28 01:14
Hi there, anyone who is experiencing the same?

**Comment by cloudymcduck** [comment] 2021-06-28 17:56
I have been having issues posting to Snipe using the API and just cannot get it to work. Saw this issue and confirmed the page is blank for us as well. Wondering if it's related to my issue...

**Comment by snipe** [comment] 2021-06-28 18:22
The Vue,js screens (API keys, importer, etc) are now fixed in 5.1.8

**Closed as completed by snipe** 2021-06-28 18:22 UTC

**Comment by snipe** [comment] 2021-06-28 18:36
Duplicate of #9743
