### ISSUE TITLE
Customized Dashboard Request

### ISSUE THREAD

**Issue by ezhilkpm** [grokability/snipe-it#11851] opened 2022-09-19 16:10 UTC
### Is your feature request related to a problem? Please describe.

In Main Dashboard have All Location and  Asset Categories and the request to add some details to the dashboard is Customized Dashboard.

We have more location sites and some materials deployed and non-deployed. we have an issue getting in a single view. To request to add the same in All locations including the deployed, undeployed, and pending details in the dashboard.

Example
Location-wise Details: Request in Dashboard.

Name	Deployed	undeployed	pending	Archived Total
India	20	           25	                 10	        15            70
US	        30	           20	                  5	         4             59

### Describe the solution you'd like

Help to monitor and plan quickly.

**Comment by snipe** [comment] 2022-09-28 23:45
Duplicate of #7297

**Closed as completed by snipe** 2022-09-28 23:45 UTC

**Comment by lewisvm40** [comment] 2023-10-26 09:42
Hi there,

Any news on this feature? would be very helpful to have this feature and it looks as though most requests for this get closed down with no actual reply...
