### ISSUE TITLE
[Feature Request]: LDAP Group mapping

### ISSUE THREAD

**Issue by devvonmonahan** [grokability/snipe-it#12483] opened 2023-02-08 12:10 UTC
### Is your feature request related to a problem? Please describe.

When users get imported to SnipeIT, you can now (in the recent version/s) select a default group on SnipeIT for them to be added to.
Depending on a users' role within the company, we'd like to give them different permissions. Although the new default group gives us base permissions to start from, it'd be nice to implement this into details from their AD account - specifically group membership.

### Describe the solution you'd like

With the new default group feature added in one of the recent updates (might've been 6.0.14) I'd quite like to see a mapping between SnipeIT groups and LDAP AD groups.

Any user who is a member of Group1 in Active Directory will be assigned SnipeIT-Group1 on SnipeIT based on previously configured group synchronization.

This allows changes to be done in Active Directory, especially useful for instances where a template account with group memberships already added exists.

If this were to be implemented, a check every LDAP sync would need to be done to confirm membership hasn't been revoked/altered. 

### Describe alternatives you've considered

Manually assign groups

**Comment by snipe** [comment] 2023-09-21 09:48
Duplicate of #4877

**Closed as completed by snipe** 2023-09-21 09:48 UTC
Labels: :heart: feature request
