### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by alikhazal** [grokability/snipe-it#13772] opened 2023-10-19 19:22 UTC
### Is your feature request related to a problem? Please describe.

- In Snipte-IT we can do only custom fields for assets. It would be great if we can have Custom fields for the components and accessories.

- SuperAdmin, can add data to the system but he/she doesn't show in the User list creating issues for us to assign accessories and assets to him/her.

### Describe the solution you'd like

- It would be great if we can have Custom fields for the components and accessories.
- Let SuperAdmin account appear in the users list so that one can assign assets to it.
Thanks.

**Comment by snipe** [comment] 2023-10-23 11:50
Duplicate of #4261

**Closed as completed by snipe** 2023-10-23 11:50 UTC
