### ISSUE TITLE
[Feature Request]: Bulk checkout accessories

### ISSUE THREAD

**Issue by kamsobe** [grokability/snipe-it#11504] opened 2022-07-13 15:35 UTC
### Is your feature request related to a problem? Please describe.

Accessories must be checked out to a person 1 at a time. 

This is similar to request #7351, a request that I'm not sure why is closed since people have since updated that they are interested in seeing it becoming implemented.

### Describe the solution you'd like

Especially since Predefined Kits do not include Accessories...so I cannot automatically assign multiple Accessories that way, Accessories should have the ability to be assigned in bulk. Similarly to the existing Bulk Checkout that is available for Assets.

### Describe alternatives you've considered

Creating an asset for every single accessory... However, this would cause us to miss out on the very valuable automatic low inventory warnings.

**Comment by snipe** [comment] 2022-07-13 16:59
Duplicate of #6928

**Closed as completed by snipe** 2022-07-13 16:59 UTC
