### ISSUE TITLE
[Feature Request]: Custom Fields for Locations

### ISSUE THREAD

**Issue by kipperpig** [grokability/snipe-it#11865] opened 2022-09-22 11:42 UTC
### Is your feature request related to a problem? Please describe.

We assign our assets to locations rather than users because of the type of industry we are in.
As such each location is required to have further details against it, Site ID, Cell ID, Access details, etc etc

The current fields within Locations isn't sufficient.

### Describe the solution you'd like

Similar to Models, add custom fields/fieldsets to Locations.

### Describe alternatives you've considered

Currently have the fields under models which isn't ideal as we have to update location and then the details in the asset and add a note to say why we've updated it. Would rather just check the item in and update the Location.

**Comment by snipe** [comment] 2022-09-30 02:01
Duplicate of #4261

**Closed as completed by snipe** 2022-09-30 02:01 UTC
