### ISSUE TITLE
[Feature Request]: Transfer button between locations

### ISSUE THREAD

**Issue by Dev00te** [grokability/snipe-it#11532] opened 2022-07-19 21:05 UTC
### Is your feature request related to a problem? Please describe.

Hello,

I saw that this feature is not available (I hope not) Can a button be added that will enable the transfer of components, consumables and accessories between locations?

### Describe the solution you'd like

If such a thing can be added, the transfer can easily take place. I think it can work for those who use it in the form of more than one company.

**Comment by hallarks54** [comment] 2022-07-26 13:19
:(

**Comment by Black-Pawn-C7** [comment] 2024-07-12 18:07
This would help us a lot to. I would like to add Assets to the list and that that thez are then not checked out. We have The Problem that we have multiple locations and child locations and that one can not move assets to them without eicher checking in and out or editing the asset (which we would like not to do since there is no Permission that only allows for change location)

**Comment by snipe** [comment] 2024-08-14 11:54
Duplicate of #5834 and #8280

**Closed as completed by snipe** 2024-08-14 11:54 UTC
