### ISSUE TITLE
Let consumibles be consumed by locations

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#10057] opened 2021-09-08 10:08 UTC
### Snipe-IT Version

Version v5.1.8 - build 6257

### Operating System

ubuntu 20.04

### Web Server

apache

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Consumibles can only be consumed by users, but there's cases that locations or assets can consume things

### Describe the solution you'd like A clear and concise description of what you want to happen.

let us select users and locations that consume consumibles

**Comment by snipe** [comment] 2021-09-11 00:46
Closed as duplicate of #9634

**Closed as completed** 2021-09-11 01:38 UTC
