### ISSUE TITLE
[Feature Request]: Consumables need improvement

### ISSUE THREAD

**Issue by swift2512** [grokability/snipe-it#15855] opened 2024-11-20 10:45 UTC
### Is your feature request related to a problem? Please describe.

You should be able to check-out consumables not only to users, but also to assets. We all know that printer, not the user, user paper, toner, drums, etc. Yet, we can have a person who's responsible for the consumables. Also, we should be able to check-in consumables because mistakes happen., people switch jobs, etc. Also, we can't get rid of assigned consumables in any way - consumables are forever. (You can delete it, but then you will lose history.)

### Describe the solution you'd like

1. Ability to checkout to people and assets.
2. Ability to check-in components.
3. Ability to manually expire consumables assigned to assets. (Total amount of this consumable is reduced by one in corresponding consumable list and entry about this is put in asset's history.)

**Comment by snipe** [comment] 2024-11-20 13:14
This is a duplicate of several other issues and you can already checkin components.

**Closed as completed by snipe** 2024-11-20 13:14 UTC
