### ISSUE TITLE
Only "Asset" can use custom fileds ? Consumables, Accessories, Components, Software Licenses can not use?

### ISSUE THREAD

**Issue by huifei0129** [grokability/snipe-it#15189] opened 2024-07-30 03:37 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Only "Asset" can use custom fileds ? 
Consumables, Accessories, Components, Software Licenses can not use custom fileds ?

![image](https://github.com/user-attachments/assets/ab83e05c-63d7-4171-ba62-eade01afd813)
![image](https://github.com/user-attachments/assets/b10fbc19-7a84-49c2-829f-eb3cd764971a)

### Reproduction steps

1. Only "Asset" can use custom fileds ? 
2. Consumables, Accessories, Components, Software Licenses can not use custom fileds ?
3.
...

### Expected behavior

help 

### Snipe-IT Version

 Version v7.0.9 - build 14371 (master)

### Operating System

Ubuntu, Windows

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

**Comment by snipe** [comment] 2024-07-31 08:08
That is correct - custom fields are currently only available on assets. Duplicate of https://github.com/snipe/snipe-it/issues/4261

**Closed as completed by snipe** 2024-07-31 08:08 UTC
