### ISSUE TITLE
Cant view more than 20 models

### ISSUE THREAD

**Issue by kaddirov** [grokability/snipe-it#9107] opened 2021-02-06 15:12 UTC
Hi
i'm used the latest version (v5.1.1 - build 5811)
i can't view more than 20 models in asset models and i can't go to page 2 (no button),for view the new model  created i must search by the model name

**Comment by kaddirov** [comment] 2021-02-06 17:12
in version 5.1.0 I had less than 10 model and today i wanted to complete the list of models (more then 40) when i had added new models i don't had previous button
![snipe-it](https://user-images.githubusercontent.com/34181387/107124913-ce4dd800-68a6-11eb-8c25-7f3cbeb80e47.jpg)

**Comment by mexx3001** [comment] 2021-02-08 07:43
I have the same problem. I have created more than 100 models and only see 10.

**Comment by UserGoodtm** [comment] 2021-02-08 11:28
I confirm that I have the same error, no page selection available

**Comment by Thiritin** [comment] 2021-02-09 17:56
I have the same, error its even in the demo.

**Comment by bendaugherty** [comment] 2021-02-15 14:02
We have over 700 models and we only could see 500, then we changed the number per page to lower, to see if that refreshed the Next option, just made it worse, now we can only see 50 and have no other option.  We are using v 5.1.1.

**Comment by anarute** [comment] 2021-02-17 19:57
I confirm I have the same issue running the same version reported ( Version v5.1.1 - build 5811 (master) )

**Comment by slax-creator** [comment] 2021-02-18 12:35
Can confirm as well. Version v5.1.0 - build 5772 - could only see 20 models, changed to view 10 and the drop down menu is gone and I am stuck viewing 10 entries.

**Comment by snipe** [comment] 2021-02-18 12:51
I still don't have an explanation for this. We have not seen this in the wild with *any* of our customer instances - which please understand doesn't mean I don't believe you - I do - I just can't reproduce it, which makes it super hard to fix. 

Here's a shot in the dark - what skins/extra CSS/etc are you all using? Can you try doing a control+f/cmd+f on the page for "Previous" and see if maybe it's there but unseeable due to a weird CSS issue? (Viewing source won't help, since that's all generated via javascript on page load).

Also, @kaddirov - if you could answer literally any of the questions we ask in the original issue template (browser, what you did, did you clear cookies, is there anything in logs, what version of PHP, etc etc) it would help push this issue forward.

**Comment by slax-creator** [comment] 2021-02-18 13:19
@snipe no custom CSS or skin at all. Fairly fresh install - just cycled through 1 or 2 preinstalled themes to see how they look, but changed back to default. There was a broken element after i changed the theme - screenshot below
![image](https://user-images.githubusercontent.com/79136892/108362405-fbc64a00-71f3-11eb-9ae6-ab8397ad47fc.png)

So maybe something is broken in the the theme and it carried over to the default theme?
Just checked your Snipe IT demo webpage and it has the same problem. So you might want to take a look there.

**Comment by anarute** [comment] 2021-02-18 15:34
@snipe even rolling back to 5.1.1 you can't reproduce? I can reproduce it in the docker image as well as in a local install running the local development server with `php artisan serve` checkout out to the `v5.1.1` tag
Checking out to the `master` branch fixes it so it's definitely not a local config 

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The list of models shows only 20 models and the navigation buttons are not shown

**To Reproduce**
Steps to reproduce the behavior:
1. Go to the Asset models page

**Expected behavior**
That all the models and the navigation menu were displayed correctly

**Screenshots**
![models-bug2](https://user-images.githubusercontent.com/333447/108365718-49cc5500-71d6-11eb-9b24-03d4be4e7bae.gif)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: ubuntu and debian
 - Web Server: apache and locally with `php artisan serve`
 - PHP Version 7.4.10

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser : Firefox and Chrome


**Error Messages**
no errors in the debug footer nor in the console

**Additional context**
- Is this a fresh install or an upgrade? 
happens in fresh install and in the docker image for this version

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
in production just ran `docker-compose pull` and it fetched this version and the bug appeared
locally I switched to the tag v5.1.1, run `composer install --no-dev --prefer-source`, then run the server with `php artisan serve` and the bug appeared

**Comment by snipe** [comment] 2021-02-18 19:11
TYSM @anarute and @slax-creator - this gives me at few places to start at least. 

> Just checked your Snipe IT demo webpage and it has the same problem. So you might want to take a look there.

@slax-creator if you can tell me which specific page, I definitely will. We repopulate the demo database on a cron and we definitely don't have more than 20 asset models at any given time.

@anarute I can see your debugger bar there, which is great (and TYSM for gif/video - everything helps) - can you tell what queries you're seeing in the query tab of the debugger. You'll see a few on page load load, and then you'll see a few pop up as ajax load.

**Comment by snipe** [comment] 2021-02-18 19:13
(Also, anything in your browser console, like some JS that didn't load, or anything?)

And everybody tried clearing their cookies and all the normal stuff, I'd hope.

**Comment by slax-creator** [comment] 2021-02-19 09:05
@snipe nothing in the console. It's the /models page, clearing cookies fixes the 10/20 items dropdown menu disappear problem until you change it again. But the "Previous 1-2-3...Next" buttons are never there to begin with (that's ofcourse on my install of SnipeIT where there are many models).

**Comment by snipe** [comment] 2021-02-25 21:07
This is actually a duplicate of #9085

**Closed as completed by snipe** 2021-02-25 21:07 UTC
Labels: :hand: bug, :woman_technologist: ready for dev
