### ISSUE TITLE
Custom Fields - incorrect sort order for numerical

### ISSUE THREAD

**Issue by pogovault** [grokability/snipe-it#15458] opened 2024-09-06 21:49 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

custom fields of numerical type are sorted in table alphabetically instead of numeric order

### Reproduction steps

1. create custom field i.e "Monitors", FormElement: Text Box, Format: NUMERIC
2. add it to fieldset (or create a new one), add that fieldset to asset model and create five new assets
3. fill in "Monitors" with numbers 4, 8, 32, 1, 16
4. list all assets and in table sort by "Monitors", (ascending)
...

### Expected behavior

The assets should be sorted in ascending order (1, 4, 8, 16, 32). Instead they are sorted in alphabetical order (1, 16, 32, 4, 8).

### Screenshots

not sorted:
![noSort](https://github.com/user-attachments/assets/f916065c-d503-4d1b-a490-7d2c952a25d9)

ascending sort:
![ascending](https://github.com/user-attachments/assets/ea84a0f5-0d48-4e65-a947-e620a80952f3)

### Snipe-IT Version

7.0.11

### Operating System

Ubuntu (docker)

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows 10

### Browser

Chrome

### Version

128.0.6613.120

**Comment by snipe** [comment] 2024-09-09 00:12
Duplicate of #11634

**Closed as completed by snipe** 2024-09-09 00:12 UTC
