### ISSUE TITLE
[Feature Request]: Signatures without EMail-Account

### ISSUE THREAD

**Issue by atuschen** [grokability/snipe-it#11903] opened 2022-10-02 06:52 UTC
### Is your feature request related to a problem? Please describe.

I need to get signatures on asset assignment from external peoples without email account.

### Describe the solution you'd like

It would be nice if administrators could just click a button on assignment to get the EULA/Terms an conditions with the signature field.
It would be nice if this were possible on a tablet  - Users come into the office, get the assets and just sign.
No need for an email address.

### Describe alternatives you've considered

There are none so far.

For now I've disabled the user-check in /app/Http/Controller/Account/AcceptanceController.php
This way I can call the Signature-page as another user from the email-link.

### Additional context

I'm working at a carrier company and we have a lot of drivers from subcontractors getting telematics-equipment (handheld-scanners, MDE/MDT).
These drivers do not have an email-account (only the subcontractor has), but I need the signature from the drivers at the time they get their devices.

**Comment by snipe** [comment] 2022-10-05 01:28
Duplicate of #8414

**Closed as completed by snipe** 2022-10-05 01:28 UTC
