### ISSUE TITLE
Horizontal bar also on top

### ISSUE THREAD

**Issue by bilias** [grokability/snipe-it#14377] opened 2024-03-06 09:37 UTC
### Is your feature request related to a problem? Please describe.

When you have items with many fields either on assets or licenses, accessories etc
the horizontal scrolling bar goes only at bottom.

When you have many items and select show all items (100+) and want to see the top right items fields you have to scroll down, change the bar and then back up.
If you want to see more fields to the right you have to repeat.

### Describe the solution you'd like

Would be nice if the horizontal bar was also at the top.
Even better if it stayed there when you scroll up and down. In that case it could be only one bar but always visible and not only at the bottom

**Comment by snipe** [comment] 2024-03-07 14:11
Duplicate of https://github.com/snipe/snipe-it/issues/5779 - unfortunately this is currently a limitation of the JS library we use.

**Closed as completed by snipe** 2024-03-07 14:11 UTC
