### ISSUE TITLE
Feature Request: Multi-Item checkout at User page.

### ISSUE THREAD

**Issue by MWR-Napavine** [grokability/snipe-it#9773] opened 2021-06-30 16:07 UTC
**Server (please complete the following information):**
 - Snipe-IT VersionL v5.1.6 - build 6109
 - OS: Snipe-IT Web Hosted (Unknown)
 - Web Server: Snipe-IT Web Hosted (Unknown)
 - PHP Version: 7.3.23

**Is your feature request related to a problem? Please describe.**
I will be using Snipe-IT to keep track of assets assigned to students in the next school year. The workflow for a Snipe-IT user to checkout multiple items should start at the target user's page.

**Describe the solution you'd like**
When the student is assigned a laptop, charger, and textbooks, It would be convenient if this could be easily done at the User's  Info page. What makes sense to me is to add a new button (Perhaps Green, to have it stand out from the other blue and red buttons) on the user's Info tab that is labeled "Check out item(s) to this user". Clicking this button should go to the Bulk Checkout form with the user field already assigned to the user in question.

**Describe alternatives you've considered**
Instead of using the bulk checkout form, an embedded or otherwise dedicated checkout form could be created. But the bulk checkout form seems to be sufficient. 

Here's an alternative idea: Perhaps a "Quick Checkout" text field that quickly assigns an asset to the user, but will prompt if the item is somehow not ready for deployment? That way you never leave the User's page.

**Additional context**
This link could also be in the Assets, Licenses, Accessories, and Consumables tabs as well. The Quick Checkout idea could also appear in each of the other tabs.

Any "Quick Checkout" option may need to allow setting a check-in date, or have some kind of configurable default (like a 1 year from today).

![UserCheckoutButtonSnipeIT](https://user-images.githubusercontent.com/48335860/123995250-fb4c7580-d982-11eb-806c-d25809b44db1.png)

**Comment by snipe** [comment] 2021-06-30 19:37
That's already on the roadmap

**Comment by MWR-Napavine** [comment] 2021-06-30 19:54
> That's already on the roadmap

Cool. Thanks! Do we know when we might see it?

**Comment by snipe** [comment] 2021-06-30 19:59
I don't have a timeline for that right now - we have literally hundreds of requests to get to.

**Comment by snipe** [comment] 2021-06-30 19:59
Hoping we can squeeze it into v6 tho, which should be out around Sept

**Comment by snipe** [comment] 2022-07-13 17:00
Duplicate of Duplicate of #6928

**Closed as completed by snipe** 2022-07-13 17:00 UTC
