### ISSUE TITLE
Check out multiple items at once to a user

### ISSUE THREAD

**Issue by ntutech** [grokability/snipe-it#9379] opened 2021-04-01 04:01 UTC
Hi,
I tried the Demo and i realise there isn't a way to check out multiple Consumables or Accessories at one time. This is useful for a user who wants 5 reams of paper (Consumable) and the admin has to check out 5 times? Or for cables (Accessories), where the user wants 10 of them as he is in charge of a space. Is there a solution to this?

**Comment by snipe** [comment] 2021-04-01 20:05
Closed as a duplicate of 6,000 issues.

It's on the docket, folks, I swear.

**Closed as completed by snipe** 2021-04-01 20:05 UTC
