### ISSUE TITLE
Add new section for contracts

### ISSUE THREAD

**Issue by Rolotov** [grokability/snipe-it#14861] opened 2024-06-12 09:49 UTC
### Is your feature request related to a problem? Please describe.

Is there a way to add a new section in SnipeIT such as Assets or Licence?

### Describe the solution you'd like

I wanted to add a new section for Contractes

**Comment by snipe** [comment] 2024-06-12 11:43
Duplicate of #5345

**Closed as completed by snipe** 2024-06-12 11:43 UTC
