### ISSUE TITLE
[Feature Request]: Consumable bulk checkout

### ISSUE THREAD

**Issue by BlueNoob** [grokability/snipe-it#12892] opened 2023-04-23 05:44 UTC
### Is your feature request related to a problem? Please describe.

For example, I need checkout 100 CAT-6 cables to Leon, at present, I need manually check out for 100 times.

### Describe the solution you'd like

Consumable bulk checkout

### Describe alternatives you've considered

Check 1*CAT-6 cable, 100 times ...

**Comment by ak-piracha** [comment] 2023-05-19 14:51
Hello @BlueNoob,
Your request for a bulk checkout feature for consumables sounds like a valuable addition to the application. This feature would definitely streamline the process of checking out multiple units of the same consumable to a single user, saving users time and improving overall user experience.

To ensure that we fully understand your needs, could you please provide a bit more detail about your requirements? Here are a few questions:

**Check-out Interface:** Would you like this feature to be available on the same check-out page used for individual items, or would you prefer a separate interface for bulk checkouts?

**Quantities:** How would you like to specify the quantity of the consumable that you are checking out? Would you like a simple input field where you can enter the number, or would a selection dropdown be more suitable?

**Comment by ak-piracha** [comment] 2023-05-19 14:58
Here's a screenshot of the bulk checkout feature.

In this screenshot, you'll notice a few key things:

**QTY**: This is where the user can input the number of consumables they wish to check out in bulk. As you can see, I've implemented it with an input field that accepts numeric values only.

**Error Handling**: If the quantity entered exceeds the available consumables, an error message is displayed, as indicated in the lower part of the screenshot.

This implementation aims to streamline the process of checking out multiple units of the same consumable, saving time and improving user experience.

Please take a look and let me know your thoughts. Is this in line with the feature enhancements you envisioned?

Looking forward to your feedback.

<img width="1338" alt="image" src="https://github.com/snipe/snipe-it/assets/88882041/d04eee51-90da-4bdf-b695-e62100f18658">

**Comment by snipe** [comment] 2023-05-20 04:08
Duplicate of #5140

**Closed as completed by snipe** 2023-05-20 04:08 UTC

**Comment by BlueNoob** [comment] 2023-05-21 06:14
> Here's a screenshot of the bulk checkout feature.
> 
> In this screenshot, you'll notice a few key things:
> 
> **QTY**: This is where the user can input the number of consumables they wish to check out in bulk. As you can see, I've implemented it with an input field that accepts numeric values only.
> 
> **Error Handling**: If the quantity entered exceeds the available consumables, an error message is displayed, as indicated in the lower part of the screenshot.
> 
> This implementation aims to streamline the process of checking out multiple units of the same consumable, saving time and improving user experience.
> 
> Please take a look and let me know your thoughts. Is this in line with the feature enhancements you envisioned?
> 
> Looking forward to your feedback.
> 
> <img alt="image" width="1338" src="https://user-images.githubusercontent.com/88882041/239564825-d04eee51-90da-4bdf-b695-e62100f18658.png">

Thanks, exatcly, in which version can I see this? 
I checked the online demo, also not supported.
