### ISSUE TITLE
Checking a Consumable Out to an Asset/Location

### ISSUE THREAD

**Issue by tsdigital** [grokability/snipe-it#10066] opened 2021-09-09 22:39 UTC
### Snipe-IT Version

v5.1.8 build 6257 (gb5bb74b8c)

### Operating System

Snipe-IT SaaS

### Web Server

Snipe-IT SaaS

### PHP Version

7.3.23

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

The biggest problem is that people aren't always the ones using consumables. Printers utilize paper and toner. It's hard to associate the usage of a consumable like paper to a single user for something like an MFP. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

Assigning/checking out a consumable to location or asset would be ideal. It would also help to track which printers are incurring the most "maintenance" without just pulling print counts on each printer. 

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

A service user in Snipe-IT is what we have been using, but we only have a single service account. I have been tempted to create a service account for each printer, but I felt that could create a maintenance nightmare later. 

### Additional context Add any other context or screenshots about the feature request here.

This has been requested in the following places - #10057, #9760, #9164, #8976, #8763, #8912, #8272, but did not look to be listed as Feature Requests.

**Comment by francogp** [comment] 2021-09-10 10:57
https://github.com/snipe/snipe-it/issues/10057

**Comment by snipe** [comment] 2021-09-11 00:38
Closing as duplicate of #9760, #9634, and #10057

**Closed as completed by snipe** 2021-09-11 00:38 UTC
