### ISSUE TITLE
Bulk check out / check in of Accessories

### ISSUE THREAD

**Issue by cbradley80** [grokability/snipe-it#10995] opened 2022-04-29 01:28 UTC
### Snipe-IT Version

5.4.1

### Operating System

Win10

### Web Server

?

### PHP Version

7.4.28

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

More of a question - is there a way to check out / check in multiple accessories at the same time? We have employees who are issued uniforms and such, which are listed as accessories.  I wanted to see if there was a way to check out or check in multiple items at the same time to save our admin personnel some time.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I wanted to see if there was a way to check out or check in multiple items at the same time to save our admin personnel some time.

**Comment by snipe** [comment] 2022-07-13 17:00
Duplicate of #6928

**Closed as completed by snipe** 2022-07-13 17:00 UTC
