### ISSUE TITLE
Can't Select/Upload SAML IdP Metadata XML File in Safari

### ISSUE THREAD

**Issue by bahhhhh** [grokability/snipe-it#8669] opened 2020-11-03 19:19 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm working on enabling SAML integration. When trying to upload the SAML IdP metadata file (an `.xml` file), Finder isn't allowing me to select the file.

**To Reproduce**
1. Go to Settings
2. Go to SAML
3. Click on the "Select File..." button
4. The `.xml` file isn't selectable

**Expected behavior**
I should be able to select an `.xml` file to upload to our Snipe-IT instance

**Screenshots**
![File selection issue](https://i.imgur.com/yLjWwuF.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v.5.0.4
 - [snipe/snipe-it Docker image](https://hub.docker.com/r/snipe/snipe-it/)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)
 - Browser: Safari 14.0 (15610.1.28.1.9, 15610)

**Smartphone (please complete the following information):**
N/A

**Error Messages**
N/A

**Additional context**
N/A

**Comment by denzfarid** [comment] 2020-11-04 02:02
have you tried with other browsers?
i use firefox and google chrome they can do that

confirmed cannot browse `.xml` file if using safari
**Version 14.0 (15610.1.28.1.9, 15610)**
<img width="1236" alt="gambar" src="https://user-images.githubusercontent.com/1294403/98060476-40fc8100-1e7c-11eb-8edd-6448145e0d7f.png">

**Comment by bahhhhh** [comment] 2020-11-04 19:32
> have you tried with other browsers?
> i use firefox and google chrome they can do that
> 
> confirmed cannot browse `.xml` file if using safari
> **Version 14.0 (15610.1.28.1.9, 15610)**

I'm also having login issues, so I can't try other browsers 😕 See [issue 8670](https://github.com/snipe/snipe-it/issues/8670)

**Comment by snipe** [comment] 2020-11-10 05:18
You can always login with your local user by adding `/?nosaml` to the base Snipe-IT url

**Comment by bahhhhh** [comment] 2020-11-10 22:12
Ah right - thanks, @snipe! I was able to login in Chrome using the local admin.

**Comment by snipe** [comment] 2020-11-13 02:47
This should be fixed on develop now and will be in the next tagged release

**Comment by snipe** [comment] 2020-11-13 02:48
(For those curious, it's because XML can have a mime-type of `text/xml` *or* `application/xml`, and we were only checking for the text mime type.)

**Closed as completed by snipe** 2020-11-13 02:47 UTC

**Comment by snipe** [comment] 2020-11-13 02:49
> From the RFC ([3023](https://tools.ietf.org/html/rfc3023)), under section 3, XML Media Types:

>> If an XML document -- that is, the unprocessed, source XML document -- is readable by casual users, text/xml is preferable to application/xml. MIME user agents (and web user agents) that do not have explicit support for text/xml will treat it as text/plain, for example, by displaying the XML MIME entity as plain text. Application/xml is preferable when the XML MIME entity is unreadable by casual users.
