### ISSUE TITLE
Custom dashboard views 

### ISSUE THREAD

**Issue by thetiagomatos** [grokability/snipe-it#10400] opened 2021-12-07 15:58 UTC
### Snipe-IT Version

5.3.1

### Operating System

Ubuntu

### Web Server

nginx

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Not related to a problem.

### Describe the solution you'd like A clear and concise description of what you want to happen.

It would be perfect to be able to customize the dashboard with filtered views of our choosing, just to save that time that we take consulting the (eg) assets board and applying the filter to find what we want. 
Is this something on your scope?

Thank you!

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Allow us to modify the views that are currently on the dashboard to display the info we want.

**Comment by snipe** [comment] 2022-09-28 23:46
Duplicate of https://github.com/snipe/snipe-it/issues/7297

**Closed as completed by snipe** 2022-09-28 23:46 UTC
