### ISSUE TITLE
CC Email Functionality Issue After Update to Version 7.0.13

### ISSUE THREAD

**Issue by impgitsubs** [grokability/snipe-it#15658] opened 2024-10-14 11:48 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi Team,

I have encountered an issue after updating to the latest version of the software (v7.0.13). In the previous version (v7.0.12), when checking in or checking out assets for users, an email was sent to the end-user, and the admin distribution list (DL) was copied via CC. However, after the update to v7.0.13, the CC functionality is no longer working.

### Reproduction steps

Check out or check in an asset to a user.
Observe the email sent to the end-user.
Check if the admin DL address is included in the CC field.

### Expected behavior

The admin DL address should be copied in the CC field of the email, as it was in version 7.0.12.

### Snipe-IT Version

v7.0.13

### Operating System

CentOS Linux 7

### Web Server

Apache/2.4.6

### PHP Version

PHP 8.3.8

**Comment by snipe** [comment] 2024-10-14 12:34
Duplicate of #15641

**Closed as completed by snipe** 2024-10-14 12:34 UTC
