### ISSUE TITLE
If I'm maintaining the two companies the two companies having the different asset numbering

### ISSUE THREAD

**Issue by padaki04** [grokability/snipe-it#15011] opened 2024-07-03 12:46 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If I'm maintaining the two companies the two companies having the different asset numbering 
eg  Company is example 1. XYZ Asset tagging should be different Eg xyz0001
if 2. company will be ZXY Asset tagging should be different Eg zxy0001

### Reproduction steps

If I'm maintaining the two companies the two companies having the different asset numbering 
eg  Company is example 1. XYZ Asset tagging should be different Eg xyz0001
if 2. company will be ZXY Asset tagging should be different Eg zxy0001

### Expected behavior

If I'm maintaining the two companies the two companies having the different asset numbering 
eg  Company is example 1. XYZ Asset tagging should be different Eg xyz0001
if 2. company will be ZXY Asset tagging should be different Eg zxy0001

### Snipe-IT Version

v7.0.6 

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

PHP 8.1.2 or greater

**Comment by snipe** [comment] 2024-07-03 12:47
Duplicate of #3286

**Closed as completed by snipe** 2024-07-03 12:47 UTC
