### ISSUE TITLE
Logo Path Incorrect

### ISSUE THREAD

**Issue by chaddblanchard** [grokability/snipe-it#9117] opened 2021-02-09 19:27 UTC
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The logo in the navigation bar doesn't show up. The path is invalid. Happens in the online demo as well. 

**To Reproduce**
1. Have a logo defined in setting and reload Snipe. Logo isn't shown in nav bar. 

**Expected behavior**
The logo defined in settings shows in the nav bar

**Screenshots**
![image](https://user-images.githubusercontent.com/23637034/107416601-494b0480-6ada-11eb-8480-c36636d8ebe3.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.1.
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 88

**Error Messages**
404 - not found

**Comment by bsu445** [comment] 2021-02-11 15:22
it's looking for the logo in path SNIPE-IT/uploads/...png
correct path SNIPE-IT/public/uploads/

**Comment by viclou** [comment] 2021-02-12 21:53
duplicate of [https://github.com/snipe/snipe-it/issues/8766](url)

**Closed as completed** 2021-04-19 13:34 UTC
