### ISSUE TITLE
Docker Image missing for 5.2.0

### ISSUE THREAD

**Issue by Exordian** [grokability/snipe-it#10092] opened 2021-09-16 19:13 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Docker image on dockerhub missing for 5.2.0 

https://hub.docker.com/r/snipe/snipe-it/tags?page=1&ordering=last_updated

### Reproduction steps

-

### Expected behavior

-

### Snipe-IT Version

5.2.0

### Operating System

-

### Web Server

-

### PHP Version

-

**Comment by snipe** [comment] 2021-09-16 19:21
Closing as duplicate of #10065

**Closed as completed by snipe** 2021-09-16 19:21 UTC
