### ISSUE TITLE
Inactive LDAP user throws exception

### ISSUE THREAD

**Issue by gramakri** [grokability/snipe-it#8772] opened 2020-11-17 23:53 UTC
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Have an inactive LDAP user. Try to login as inactive user.  Page throws "500 | Server Error"

**To Reproduce**
1. Have LDAP login enabled
2. Login with a user who has the inactive db field set to 0
3. See error

**Expected behavior**
Should report login failure instead

**Screenshots**
![image](https://user-images.githubusercontent.com/82041/99464279-9741d900-28ec-11eb-81c7-2a54f9e512ab.png)

**Server (please complete the following information):**
 - Snipe-IT Version 5.0.7
 - OS: Docker/Cloudron
 - PHP Version 7.3

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Error Messages**
```
[2020-11-17 23:29:20] production.ERROR: Return value of App\Services\LdapAd::ldapLogin() must be an instance of App\Models\User, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Services\\LdapAd::ldapLogin() must be an instance of App\\Models\\User, null returned at /app/code/app/Services/LdapAd.php:150)
[stacktrace]
#0 /app/code/app/Http/Controllers/Auth/LoginController.php(146): App\\Services\\LdapAd->ldapLogin()
#1 /app/code/app/Http/Controllers/Auth/LoginController.php(207): App\\Http\\Controllers\\Auth\\LoginController->loginViaLdap()
#2 [internal function]: App\\Http\\Controllers\\Auth\\LoginController->login()
#3 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#4 /app/code/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#5 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#7 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#8 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /app/code/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RedirectIfAuthenticated->handle()
#11 /app/code/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#13 /app/code/app/Http/Middleware/CheckForTwoFactor.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForTwoFactor->handle()
#15 /app/code/app/Http/Middleware/CheckLocale.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckLocale->handle()
#17 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /app/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#21 /app/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#23 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#25 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#27 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#29 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /app/code/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#32 /app/code/app/Http/Middleware/SecurityHeaders.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\SecurityHeaders->handle()
#34 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /app/code/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForDebug->handle()
#38 /app/code/app/Http/Middleware/CheckForSetup.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\CheckForSetup->handle()
#40 /app/code/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#42 /app/code/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#44 /app/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#46 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#48 /app/code/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle()
#50 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#52 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#53 /app/code/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle()
#54 {main}
```

**Additional context**
- This is a fresh install (on Cloudron)

**Comment by gramakri** [comment] 2020-11-17 23:56
From what I could debug: https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L148 returns null because user exists and activated is 0. This results in the code throwing an exception.

**Comment by uberbrady** [comment] 2020-11-17 23:57
Yeah, this is actually a strict-typing error - that function is not 'supposed' to return null. Let me see if I can reproduce it in my environment.

Thanks for the detailed bug report, and thanks for taking a stab at debugging it for us!

**Comment by gramakri** [comment] 2020-11-17 23:59
@uberbrady One additional info is that the "activated" field is not set by the Cloudron package. I guess because this is new in 5.0.7. And if it helps, the database table looks like this. Crash happens when trying to login as "girish" . It works fine when trying to login as admin.

```
mysql> select * from users;
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+------------------------------------+------------+----------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
| id | email                | password                                                     | permissions                                                            | activated | activation_code | activated_at | last_login          | persist_code | reset_password_code | first_name | last_name    | created_at          | updated_at          | deleted_at | website | country | gravatar | location_id | phone | jobtitle | manager_id | employee_num | avatar | username | notes                              | company_id | remember_token | ldap_import | locale | show_in_list | two_factor_secret | two_factor_enrolled | two_factor_optin | department_id | address | city | state | zip  |
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+------------------------------------+------------+----------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
|  1 | admin@cloudron.local | $2y$10$P/4tBsdIAFqMG3BoOajhq.p2nt1WjH1o6RAGLw8US3olu3IPAcSZu | {"admin":1,"user":1,"superuser":1,"reports.view":1, "licenses.keys":1} |         1 | NULL            | NULL         | 2020-11-17 23:43:33 | NULL         | NULL                | Snipe-IT   | Admin        | 2020-11-17 23:28:45 | 2020-11-17 23:43:33 | NULL       | NULL    | NULL    | NULL     |        NULL | NULL  | NULL     |       NULL | NULL         | NULL   | admin    | NULL                               |       NULL | NULL           |           0 | en     |            1 | NULL              |                   0 |                0 |          NULL | NULL    | NULL | NULL  | NULL |
|  2 | removed       | $2y$10$qCkWZcG7x3Dt0HvOviF.4uLvV1bxXlrnAVgJNkrIY73qHRw7gBoHi | NULL                                                                   |         0 | NULL            | NULL         | NULL                | NULL         | NULL                | Girish     | Ramakrishnan | 2020-11-17 23:28:59 | 2020-11-17 23:49:41 | NULL       | NULL    | NULL    | NULL     |        NULL |       |          |       NULL |              | NULL   | girish   | Imported on first login from LDAP2 |       NULL | NULL           |           1 | en     |            1 | NULL              |                   0 |                0 |          NULL | NULL    | NULL | NULL  | NULL |
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+------------------------------------+------------+----------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
2 rows in set (0.00 sec)
```

**Comment by snipe** [comment] 2020-11-18 00:17
The activated flag has been part of Snipe-IT since the very beginning. It doesn't mean the LDAP parlance of activated, which is why we changed the phrasing to "Login enabled"

**Comment by gramakri** [comment] 2020-11-18 00:21
So, the bug itself is clear but I don't know why/what :-)

1. isLdapSync returns true since ldap_active_flag is not set in https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L283

2. This means that the code gets to https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L148 and the it crashes in ->first() since activated (the user db field) is still 0 (I am not sure where this is set). (EDIT: it comes from setUserModel - https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L215)

Also note that this is a bug in 5.0.7 only. It all works in 5.0.6.

**Comment by uberbrady** [comment] 2020-11-18 00:25
We changed a little bit about how we handle active/inactive in v5.0.7 - let me poke around and hopefully I can come up with something. Though I may have a few more questions for you @gramakri - thanks again for the detailed bug report!

**Comment by uberbrady** [comment] 2020-11-18 00:36
Ok, I can replicate this on my local instance, at least. They have to be **deactivated** in the database, but still **active** in AD - and it should be that if I re-sync them, they should flip back over to 'active'.

**Comment by gramakri** [comment] 2020-11-18 00:36
@uberbrady Thanks for looking into this :) Last comment since I ended up debugging this a bit. The main issue is in this branch of code - https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L324 . When ldap_active_flag is not set, it simply returns null (thus the user ends up getting added with activated bit as 0).

Maybe line 326 means `===` ? (https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L326)

But it still fails in line 332 again because ldap_active_flag is not there in ldap settings - https://github.com/snipe/snipe-it/blob/de6f3f866fe1c64d80589cbf41f45f6312001330/app/Services/LdapAd.php#L332.

I am happy to test whenever a patch is ready. Also, I am not a PHP developer, so take the above fwiw ;-)

**Comment by uberbrady** [comment] 2020-11-18 01:36
@gramakri PR is up - mind you, we *still* respect the DB's "activation" setting here (we have many users who want to specifically choose who can and cannot log in, and we still need to respect that).

**Comment by uberbrady** [comment] 2020-11-18 02:14
@gramakri But I think I've definitely seen some stuff where the active flag is incorrectly being toggled to `0` per your point - are you using AD? Are your users 'normal users'? Or something weirder than that? We can handle all of:

https://github.com/snipe/snipe-it/blob/6ebdfdbabbcc2b3daa9bc21791739df07d6ca2c1/app/Services/LdapAd.php#L41-L52

**Comment by uberbrady** [comment] 2020-11-18 02:27
I absolutely just saw an _initial_ sync import a user as inactive, but a later sync seemed to toggle them back to active. That's definitely **a** bug, but not all of the bug here.

**Comment by gramakri** [comment] 2020-11-18 02:28
@uberbrady This is not AD (we have a custom LDAP server). The LDAP settings we use are

```
        $settings->ldap_enabled = 1;
        $settings->ldap_server = env('CLOUDRON_LDAP_URL');
        $settings->ldap_uname = env('CLOUDRON_LDAP_BIND_DN');
        $settings->ldap_pword = $encrypter->encrypt(env('CLOUDRON_LDAP_BIND_PASSWORD'));
        $settings->ldap_basedn = env('CLOUDRON_LDAP_USERS_BASE_DN');
        $settings->ldap_filter = '&(objectclass=user)';
        $settings->ldap_username_field = 'username';
        $settings->ldap_lname_field = 'sn';
        $settings->ldap_fname_field = 'givenname';
        $settings->ldap_auth_filter_query = 'username=';
        $settings->ldap_email = 'mail';
```

Did I understand correctly that `ldap_active_flag` _has_ to be set for users to be activated? In 5.0.6, it wasn't set and the user activated defaulted to true. But it looks like in 5.0.7 this has default to false, meaning that I have to set this flag to something ? I can fix the Cloudron package accordingly, but just want a confirmation that this is your intention.

**Comment by uberbrady** [comment] 2020-11-18 02:38
No, it _should_ be fine if you leave the flag unset; then it should just get ignored. Any imported users _should_ just be active. It seems like it must not be working for you that way though. Even if you set the flag-attribute to something, if the attribute doesn't exist at **all** on your users, we should ignore that fact too.

Unfortunately, emphasis on 'should' :/

I'm still working on it, hope to come up with something soon. I'll keep you posted.

**Comment by gramakri** [comment] 2020-11-18 02:43
@uberbrady Thanks for the explanation!

**Comment by uberbrady** [comment] 2020-11-18 02:48
@gramakri if you do a second LDAP sync, does your user flip status at all?

**Comment by gramakri** [comment] 2020-11-18 04:30
@uberbrady It does not flip status on sync. I tried `php /app/code/artisan snipeit:ldap-sync  -v` . Also, that command gave no output despite the verbose flag (tried with -vvv as well)

**Comment by uberbrady** [comment] 2020-11-18 04:54
I think I pretty much understand it now, @gramakri , I'd love it if you could give #8776 a spin.

**Comment by snipe** [comment] 2020-11-18 06:33
That PR is merged onto master/develop now

**Comment by uberbrady** [comment] 2020-11-18 18:14
Specifically, the PR for "deactivated users get a 500-page on login" is merged, the "Initial LDAP import of users" one I still need some testing on before I'm going to get comfortable enough to want to merge. I feel pretty good about it, but crave external validation :)

**Comment by gramakri** [comment] 2020-11-18 23:30
@uberbrady Got tied up with other things today, I will give this a try tomorrow.

**Comment by imc67** [comment] 2020-11-20 16:51
> @gramakri  Got tied up with other things today, I will give this a try tomorrow.

How did it worked out Girish?

**Comment by snipe** [comment] 2020-11-20 18:10
I'd love to get that PR merged and into a release. If anyone can test it and let me know how you make out, that would be fantastic

**Comment by gramakri** [comment] 2020-11-20 18:40
@snipe @imc67 on it now :)

**Comment by gramakri** [comment] 2020-11-20 18:55
Can confirm the change works and our test suite passes. In case it's interesting, here's the output of the user's table after I applied the patch. (edit: i tested https://github.com/snipe/snipe-it/pull/8776 and not the one which was already merged)

```
mysql> select * from users;
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+--------------------+------------+--------------------------------------------------------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
| id | email                | password                                                     | permissions                                                            | activated | activation_code | activated_at | last_login          | persist_code | reset_password_code | first_name | last_name    | created_at          | updated_at          | deleted_at | website | country | gravatar | location_id | phone | jobtitle | manager_id | employee_num | avatar | username | notes              | company_id | remember_token                                               | ldap_import | locale | show_in_list | two_factor_secret | two_factor_enrolled | two_factor_optin | department_id | address | city | state | zip  |
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+--------------------+------------+--------------------------------------------------------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
|  1 | admin@cloudron.local | $2y$10$dlObqnO3DoV34IIXh2uFIuJmUfDlndkikB0FYYIp.bEEmgmyl0jdq | {"admin":1,"user":1,"superuser":1,"reports.view":1, "licenses.keys":1} |         1 | NULL            | NULL         | 2020-11-20 18:51:37 | NULL         | NULL                | Snipe-IT   | Admin        | 2020-11-20 18:51:22 | 2020-11-20 18:51:37 | NULL       | NULL    | NULL    | NULL     |        NULL | NULL  | NULL     |       NULL | NULL         | NULL   | admin    | NULL               |       NULL | NULL                                                         |           0 | en     |            1 | NULL              |                   0 |                0 |          NULL | NULL    | NULL | NULL  | NULL |
|  2 | removed       | $2y$10$M1mOdv9b0OR6KBE5uL8JKO3MPYYBsmgCAFYAiyyvZTApneruxBP7y | NULL                                                                   |         1 | NULL            | NULL         | 2020-11-20 18:52:30 | NULL         | NULL                | Girish     | Ramakrishnan | 2020-11-20 18:51:48 | 2020-11-20 18:52:30 | NULL       | NULL    | NULL    | NULL     |        NULL |       |          |       NULL |              | NULL   | girish   | Imported from LDAP |       NULL | xpzfwON2D4pFdqKxz116rW04l1oDpUHNkm5tsXm7mPAWbtZVf2L3rzDDPOP6 |           1 | en     |            1 | NULL              |                   0 |                0 |          NULL | NULL    | NULL | NULL  | NULL |
+----+----------------------+--------------------------------------------------------------+------------------------------------------------------------------------+-----------+-----------------+--------------+---------------------+--------------+---------------------+------------+--------------+---------------------+---------------------+------------+---------+---------+----------+-------------+-------+----------+------------+--------------+--------+----------+--------------------+------------+--------------------------------------------------------------+-------------+--------+--------------+-------------------+---------------------+------------------+---------------+---------+------+-------+------+
2 rows in set (0.00 sec)
```

And the settings table (for our LDAP config):

```
mysql> select * from settings;
+----+---------------------+---------------------+---------+----------+---------------------------+---------+---------+--------------------+-----------------------+-------------+-----------------------+-----------------------+-------------+------+--------------+------------------------+----------------+-------------------+--------------+----------------+---------------+---------------+------------------+------------+-------+--------------+------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+---------------------+---------------------+------------------+------------------+------------------------+--------------+------------------+--------------+------------+---------------------------------+-------------------------+--------+-----------------+--------------+---------------+---------------------+----------------------+--------------------+-----------------------+------------------------+------------------------+-----------------+------------------+-------------------+---------------------+-----------------------+--------------------+-------------+---------------------+----------------+-----------------+---------------+--------------------+-----------------+-------+-----------+-----------+----------+----------------+--------------+--------------------+--------------------------+---------------------+---------------------+--------------------+------------+-----------------+---------------------+-----------------------+----------------+----------------+--------------------+--------------------+---------------------------------------------------+---------------------+-----------------------------+-----------------------+-------------------+----------------+-------------+------------------------------------------+---------------------------+-----------------------+-------------------------------------+------+----------------------+----------------+----------------------+---------------------+----------------+---------------+-------------------+---------------------+---------+------------+------------+----------------------+-------------------------------+------------------+--------------+-------------------+----------------------------+-----------------+----------+------------------+--------------------+----------------------+
| id | created_at          | updated_at          | user_id | per_page | site_name                 | qr_code | qr_text | display_asset_name | display_checkout_date | display_eol | auto_increment_assets | auto_increment_prefix | load_remote | logo | header_color | alert_email            | alerts_enabled | default_eula_text | barcode_type | slack_endpoint | slack_channel | slack_botname | default_currency | custom_css | brand | ldap_enabled | ldap_server            | ldap_uname                                                  | ldap_pword                                                                                                                                                                                                                                                                                                                                                                                                                       | ldap_basedn          | ldap_filter         | ldap_username_field | ldap_lname_field | ldap_fname_field | ldap_auth_filter_query | ldap_version | ldap_active_flag | ldap_emp_num | ldap_email | full_multiple_companies_support | ldap_server_cert_ignore | locale | labels_per_page | labels_width | labels_height | labels_pmargin_left | labels_pmargin_right | labels_pmargin_top | labels_pmargin_bottom | labels_display_bgutter | labels_display_sgutter | labels_fontsize | labels_pagewidth | labels_pageheight | labels_display_name | labels_display_serial | labels_display_tag | alt_barcode | alt_barcode_enabled | alert_interval | alert_threshold | email_domain  | email_format       | username_format | is_ad | ad_domain | ldap_port | ldap_tls | zerofill_count | ldap_pw_sync | two_factor_enabled | require_accept_signature | date_display_format | time_display_format | next_auto_tag_base | login_note | thumbnail_max_h | pwd_secure_uncommon | pwd_secure_complexity | pwd_secure_min | audit_interval | audit_warning_days | show_url_in_emails | custom_forgot_pass_url                            | show_alerts_in_menu | labels_display_company_name | show_archived_in_list | dashboard_message | support_footer | footer_text | modellist_displays                       | login_remote_user_enabled | login_common_disabled | login_remote_user_custom_logout_url | skin | show_images_in_email | admin_cc_email | labels_display_model | privacy_policy_link | version_footer | unique_serial | logo_print_assets | depreciation_method | favicon | email_logo | label_logo | show_assigned_assets | login_remote_user_header_name | ad_append_domain | saml_enabled | saml_idp_metadata | saml_attr_mapping_username | saml_forcelogin | saml_slo | saml_sp_x509cert | saml_sp_privatekey | saml_custom_settings |
+----+---------------------+---------------------+---------+----------+---------------------------+---------+---------+--------------------+-----------------------+-------------+-----------------------+-----------------------+-------------+------+--------------+------------------------+----------------+-------------------+--------------+----------------+---------------+---------------+------------------+------------+-------+--------------+------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+---------------------+---------------------+------------------+------------------+------------------------+--------------+------------------+--------------+------------+---------------------------------+-------------------------+--------+-----------------+--------------+---------------+---------------------+----------------------+--------------------+-----------------------+------------------------+------------------------+-----------------+------------------+-------------------+---------------------+-----------------------+--------------------+-------------+---------------------+----------------+-----------------+---------------+--------------------+-----------------+-------+-----------+-----------+----------+----------------+--------------+--------------------+--------------------------+---------------------+---------------------+--------------------+------------+-----------------+---------------------+-----------------------+----------------+----------------+--------------------+--------------------+---------------------------------------------------+---------------------+-----------------------------+-----------------------+-------------------+----------------+-------------+------------------------------------------+---------------------------+-----------------------+-------------------------------------+------+----------------------+----------------+----------------------+---------------------+----------------+---------------+-------------------+---------------------+---------+------------+------------+----------------------+-------------------------------+------------------+--------------+-------------------+----------------------------+-----------------+----------+------------------+--------------------+----------------------+
|  1 | 2020-11-20 18:51:22 | 2020-11-20 18:51:23 |       1 |       20 | Snipe-IT Asset Management |    NULL | NULL    |               NULL |                  NULL |        NULL |                     0 | NULL                  |           1 | NULL | NULL         | snit.app@cloudron.club |              1 | NULL              | QRCODE       | NULL           | NULL          | NULL          | USD              | NULL       |     1 | 1            | ldap://172.18.0.1:3002 | cn=f3d95855-61d5-4be2-ab25-ca85b444740e,ou=apps,dc=cloudron | eyJpdiI6Im9FSG10MG9TVnN2cXhicURaa2l6SVE9PSIsInZhbHVlIjoiYVZhSFoxVEVJME5odnE4eGlTblVLZ1Y3d1BObnV1SGxYektSTDZacTI5VTdORVF4cEpzWXZES2luclhXRDR5RnVySlNhRWxUY0NpZUN6eVVUVm9cL2lJNmw4Wmd6ZmZNdVFuazM4K21LK2kyUEVXdFF0dFF1VzczZDJxZzF3ZXdQZkNrUGxjN28wR0xOcXZnTFY0aFc4UXRxR3lmTHNnSXAycEVmY1BCXC8zNlVMY3NZakxaNUFaU3BtYmNZOWdINnMiLCJtYWMiOiJlZWEzZGM5ZThkNWJlMDJlNjVkMzgzMmFmNmUwMDU5YjRjNzU1NGZiNTI5ZDgwOTU5MzQ2MGY2M2VhMmQxODJmIn0= | ou=users,dc=cloudron | &(objectclass=user) | username            | sn               | givenname        | username=              |            3 | NULL             | NULL         | mail       |                               0 |                       0 | em     |              30 |      2.62500 |       1.00000 |             0.21975 |              0.21975 |            0.50000 |               0.50000 |                0.07000 |                0.05000 |               9 |          8.50000 |          11.00000 |                   0 |                     1 |                  1 | C128        |                   1 |             30 |               5 | cloudron.club | firstname.lastname | filastname      |     0 | NULL      | 389       |        0 |              5 |            1 |               NULL |                        0 | Y-m-d               | h:i A               |                  1 | NULL       |              50 |                   0 | NULL                  |             10 |           NULL |               NULL |                  0 | https://my.cloudron.club/login.html?passwordReset |                   1 |                           0 |                     0 | NULL              | on             | NULL        | image,category,manufacturer,model_number |                         0 |                     0 |                                     | NULL |                    1 | NULL           |                    0 | NULL                | on             |             0 |                 0 | default             | NULL    | NULL       | NULL       |                    0 |                               |                0 |            0 | NULL              | NULL                       |               0 |        0 | NULL             | NULL               | NULL                 |
+----+---------------------+---------------------+---------+----------+---------------------------+---------+---------+--------------------+-----------------------+-------------+-----------------------+-----------------------+-------------+------+--------------+------------------------+----------------+-------------------+--------------+----------------+---------------+---------------+------------------+------------+-------+--------------+------------------------+-------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+---------------------+---------------------+------------------+------------------+------------------------+--------------+------------------+--------------+------------+---------------------------------+-------------------------+--------+-----------------+--------------+---------------+---------------------+----------------------+--------------------+-----------------------+------------------------+------------------------+-----------------+------------------+-------------------+---------------------+-----------------------+--------------------+-------------+---------------------+----------------+-----------------+---------------+--------------------+-----------------+-------+-----------+-----------+----------+----------------+--------------+--------------------+--------------------------+---------------------+---------------------+--------------------+------------+-----------------+---------------------+-----------------------+----------------+----------------+--------------------+--------------------+---------------------------------------------------+---------------------+-----------------------------+-----------------------+-------------------+----------------+-------------+------------------------------------------+---------------------------+-----------------------+-------------------------------------+------+----------------------+----------------+----------------------+---------------------+----------------+---------------+-------------------+---------------------+---------+------------+------------+----------------------+-------------------------------+------------------+--------------+-------------------+----------------------------+-----------------+----------+------------------+--------------------+----------------------+
1 row in set (0.00 sec)
```

(all the password, domains etc above are all just from a test instance, in case anyone is worried).

@uberbrady thanks!

**Comment by snipe** [comment] 2020-11-20 19:11
Fantastic, thanks so much for testing!

**Closed as completed** 2020-11-20 22:34 UTC
