### ISSUE TITLE
Edit user info deactivates account

### ISSUE THREAD

**Issue by jcfrazier6** [grokability/snipe-it#13010] opened 2023-05-11 05:08 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Whenever I edit the admin user info, it deactivates the account. I have to go into the database and set activated to 1 to reenable login.

### Reproduction steps

1. Edit superuser account info and save.
2.
3.
...

### Expected behavior

Expect to be able to edit user info and not cause the account to be deactivated and unable to login.

### Snipe-IT Version

6.1.0

### Operating System

Windows

### Web Server

Apache

### PHP Version

8.0.28

**Comment by NojoudAlshehri** [comment] 2023-05-18 12:47
This issue appears to be a duplicate of issue #12971, which has already been solved. The original issue can be found at:
issue #12971 : [If you add notes to your own account then user is logged out and cannot log back in #12971](https://github.com/snipe/snipe-it/issues/12971).

**Closed as completed** 2023-10-26 14:17 UTC
