### ISSUE TITLE
Change of default Currency to comma as thousand separator and period as decimal

### ISSUE THREAD

**Issue by lalalostyou** [grokability/snipe-it#9254] opened 2021-03-05 09:04 UTC
Change of default Currency to comma as thousand separator and period as decimal
Like : five thousand six hundred and fifty cents ==> 5,600.50

I tried changing the format of the default currency in Helper.php., unfortunately the overall total of the asset was not reflected as I expected. It turned out that the computation of total asset was rounded off instead of adding it properly.
![image](https://user-images.githubusercontent.com/78790850/110092011-168fe580-7dd4-11eb-921a-53b1f426ad99.png)

Can someone help with this. I really need the format of comma separator as thousand and period as decimal.  

-----

-----

#### Please confirm you have done the following before posting your bug report:

- [/ ] I have enabled debug mode 
- [ /] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? ==>Recently upgraded to  v5.1.2
- Version of Snipe-IT you're running  ==> v5.1.2
- Version of PHP you're running        ==> PHP 7.3.7
- Version of MySQL/MariaDB you're running==>MariaDB 10.0
- What OS and web server you're running Snipe-IT on==> Windows Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) ==> Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error ==> Localization
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once f
![Untitled](https://user-images.githubusercontent.com/78790850/110092691-cfeebb00-7dd4-11eb-8794-5e66fc5c4bcf.jpg)
or every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2021-03-10 22:44
@lalalostyou I don't understand. The format of 1,500.34 is the default behavior. If you want the opposite, 1.500,34, you would change that in `Admin Settings > Localization`.

**Comment by snipe** [comment] 2021-03-10 22:52
Closing as duplicate of #9119. Please do not create duplicates for the same issue in the future.

**Closed as completed by snipe** 2021-03-10 22:52 UTC
