### ISSUE TITLE
"Requestable" asset issue

### ISSUE THREAD

**Issue by enesbutunn** [grokability/snipe-it#9417] opened 2021-04-11 08:07 UTC
I mark any asset as "requestable".
However, users cannot view these assets.
Sometimes a 500 error error is returned in the "requestable" tab. 

User panel;
![image](https://user-images.githubusercontent.com/79334518/114296795-e237d500-9ab5-11eb-9fb2-19782bac5e6a.png)

Admin panel;
![image](https://user-images.githubusercontent.com/79334518/114296841-18755480-9ab6-11eb-96f5-6642c6dcd1e4.png)

500 Error with requestable tab;
![image](https://user-images.githubusercontent.com/79334518/114296809-f67bd200-9ab5-11eb-9381-b877bfa2d034.png)

**Comment by praveenhitnalli** [comment] 2021-04-14 04:04
I also came across absolutely same issue. I'm adding steps to reproduce issue here - 

1. Login to Snipe-IT (v5.1.4, Build 5886 master) with Super Admin User first.
2. Create few Assets which are Available and mark or tag them as "Deployable" status. 
3. Navigate to "Requestable" tab/section and check whether it'll list all the "Deployable" status Requestable Assets. 
4. Click on "Request" Action. 
Observed that, "500 | Server Error" is appearing" on the Page. Refreshing Page does not work. 
5. . Logout from Super Admin and login with any other User (as non-Super Admin) and navigate to "Requestable" tab/section
**Expected** : Check whether User can see "Deployable" available Requestable Assets. 
**Actual** : User is unable to view any Requestable Assets. No matching found is appearing. 
Please refer attached screenshots. 

![SnipeIT#9417_Requestable_Assets_at_Normal_User](https://user-images.githubusercontent.com/42300155/114652943-8f079180-9d04-11eb-9191-7b2c667de05e.JPG)
![SnipeIT#9417_Requestable_Assets_at_Super Admin User](https://user-images.githubusercontent.com/42300155/114652949-929b1880-9d04-11eb-9bbc-60d745c8245a.JPG)

**Comment by enesbutunn** [comment] 2021-04-14 08:43
@praveenhitnalli thanks for the comment, were you able to fix the error?

**Comment by snipe** [comment] 2021-04-14 16:07
As mentioned in the initial issue template, we'd need to see the error logs from that 500 error.

**Comment by snipe** [comment] 2021-04-14 16:08
@bzeus - can you see if you can reproduce this?

**Comment by praveenhitnalli** [comment] 2021-04-15 04:55
> @praveenhitnalli thanks for the comment, were you able to fix the error?

@enesbutunn No, I couldn't able to fix the error 500 | Server error

**Comment by praveenhitnalli** [comment] 2021-04-16 04:57
![Requestable Assets_SuperAdminUser and Non-SuperAdminUser](https://user-images.githubusercontent.com/42300155/114973953-15f07180-9e9f-11eb-9d67-47e4b9d610d9.JPG)
@enesbutunn @snipe As I updated in Gitter, as of now we have to **uncheck** the option of **Full Multiple Companies Support** under General Settings. Then, the non-super admin user as well as super admin user (generally any user) can now see the Requestable Assets. Even the Users and Assets are from different Companies also fine. Same Requestable Assets display properly for all the users.

So, out of two issues, one issue on **Requestable Asset** for the Users seems to be **Resolved now**. 
Only pending is .. second issue of this defect - **500 | Server Error**. Still this is existing. If this is too resolved, then we can Close this defect.

**Comment by enesbutunn** [comment] 2021-04-16 08:52
Hi, how can we remove this setting? @praveenhitnalli 

-I found it okay, but now when I say request, it gives error 500 error. But when I refresh the page, it gets better.-

**Comment by praveenhitnalli** [comment] 2021-04-16 09:29
@enesbutunn if you are super admin, then there is a settings icon immediately next to your name. 
Click on that then go to General Settings. The very first option is - Full multiple company support.

**Comment by enesbutunn** [comment] 2021-04-16 11:20
Yes, I fixed it, but the 500 error error still returns. I have to do return page and refresh to fix this. @praveenhitnalli

**Comment by praveenhitnalli** [comment] 2021-04-16 11:25
@enesbutunn ya, that server error still there 🙂 we need to get rid off that also somehow. @snipe sirrr .. any suggestions ? Work around ?? Fixes ?? We need to provide debug logs right ? 

@enesbutunn if you knew how to provide debugging logs,  could you please share from your system ?

**Comment by snipe** [comment] 2021-04-16 13:28
I am not a sir. I am a ma’am. 

More importantly, without an actual stack trace from the error log, I’m not sure what you expect me to do here.

**Comment by praveenhitnalli** [comment] 2021-04-16 15:29
@snipe ah! I'm sorry ! 
Can you please tell me which logs we have to share ? (log file path would be much helpful, where it reside)

**Comment by enesbutunn** [comment] 2021-04-19 07:28
unfortunately I do not have either. @praveenhitnalli

**Comment by praveenhitnalli** [comment] 2021-04-23 01:16
@enesbutunn @snipe I tried to install latest version v5.1.4 of Snipe-IT and after properly installation of that and after configuration of email server, everything is working perfectly from end to end now. There is NO any single issue.

Hopefully,  this issue can be CLOSED now.

**Closed as completed** 2022-06-29 09:16 UTC
Labels: :question:  not sure if bug
