### ISSUE TITLE
Custom fields reset when changing model

### ISSUE THREAD

**Issue by ItzFlipp** [grokability/snipe-it#15606] opened 2024-10-03 02:28 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When changing the model of an asset that has fields from different fieldsets, the value in the custom field (radio button) gets reset

### Reproduction steps

Video: https://streamable.com/trvpqw

### Expected behavior

The value of the custom field should stay the same when changing the model if that field is present in the new model

### Snipe-IT Version

v7.0.13 - build 15514 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.3.12

### Operating System

Mac

### Browser

Arc, Chrome

### Version

Chromium Engine Version 129.0.6668.71

**Comment by snipe** [comment] 2024-10-03 09:36
Duplicate of https://github.com/snipe/snipe-it/issues/15007

**Closed as completed by snipe** 2024-10-03 09:36 UTC
