### ISSUE TITLE
Issue accessing API - Unauthorized or unauthenticated

### ISSUE THREAD

**Issue by newbie-admin** [grokability/snipe-it#9312] opened 2021-03-17 22:48 UTC
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We have installed Snipe-IT and already using it for a couple of months. However, API interface is giving me  "error": "Unauthorized or unauthenticated." all the time, except when I enter the required fields in Postman tool -->  Body  - > Raw option. Only then I see some login output result asking me authenticate. 

Our setup:

1. Snipe-IT is configured to accepts logins from Azure AD via SAML and users are able to login successfully. Also we are forcing login via Azure, so regular login is only enabled for Super Admin account.
2. Snipe-IT is behind NGinx proxy server and I am not sure if some of the headers are stripped off during the request.

**To Reproduce**
1. Go to 'Postman or via PowerShell  - under Headers:
2. Fill in required details like :

      {
        "authorization": "Bearer APIKEY",
        "accept": "application/json" or "application/x-www-form-urlencoded",      
        "content-type": "application/json"
      }

3. Press Send to API's url:  https://company-snipeit.com/api/v1/users
4. Receiving error:

      {
          "error": "Unauthorized or unauthenticated."
      } 

5. If I use - > Body - Raw :

      {
        "authorization": "Bearer APIKEY",
        "accept": "application/json" or "application/x-www-form-urlencoded",      
        "content-type": "application/json"
      }

then during Postman request  I get login screen to Microsoft:

<!DOCTYPE html>
<html dir="ltr" class="" lang="en">

<head>
	<title>Sign in to your account</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Expires" content="-1">
	<link rel="preconnect" href="https://aadcdn.msftauth.net" crossorigin>
	<meta http-equiv="x-dns-prefetch-control" content="on">
	<link rel="dns-prefetch" href="//aadcdn.msftauth.net">
	<link rel="dns-prefetch" href="//aadcdn.msauth.net">

**Expected behavior**
It is expected to receive a list of all our users - 200 OK

**Screenshots**

N/A

**Server (please complete the following information):**

 - Snipe-IT Version : v5.0.12 build 5705
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version : 7.2.24-0ubuntu0.18.04.7

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include 

php -m

[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**

- Fresh install 
- What method you used to install Snipe-IT - manual installation

**Comment by snipe** [comment] 2021-03-17 22:58
Duplicate of #9157

**Closed as completed by snipe** 2021-03-17 22:58 UTC

**Comment by newbie-admin** [comment] 2021-03-17 23:18
@snipe , I don't mind to relate this issue to the one for Windows/IIS server. I checked it today and thought that our setup is different, since we are having Linux OS in general. We have and NGinx proxy in the way... not sure how to continue troubleshooting.
