### ISSUE TITLE
Import "Process" button not moving onto next step

### ISSUE THREAD

**Issue by ChiliDave** [grokability/snipe-it#9827] opened 2021-07-14 20:52 UTC
#### Expected Behavior (or desired behavior if a feature request)

1. Download CSV Import Template
2. Populate relevant fields
3. Import > Upload CSV File
4. Upload Successful
5. Click on Import
6. Click on Process
7. See the Field to CSV Mapping
8. Assets Import

-----

#### Actual Behavior

1. Download CSV Import Template
2. Populate relevant fields (even removed all other fields that aren't mandatory)
3. Import > Upload CSV File
4. Upload Successful
5. Click on Import
6. Click on Process
7. Process button doesn't appear to do anything! (same issue regardless of browser / incognito etc)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - In Progress (hope to post soon if no-one else has come across this - it's 10PM and my Linux guy is on leave this week :(  )
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes - Nothing found

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Clean install as of yesterday
- Version of Snipe-IT you're running - v5.1.8 - build 6148 (master)
- Version of PHP you're running - 7.4.21
- Version of MySQL/MariaDB you're running - 
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Import
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No errors, just a button that doesn't load the next step!
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Nope as Import is not available on Demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2021-07-14 21:14
This is already fixed on master. Duplicate of #9788

**Closed as completed by snipe** 2021-07-14 21:14 UTC
