### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:40

### ISSUE THREAD

**Issue by damianwayne7** [grokability/snipe-it#8506] opened 2020-10-09 11:53 UTC
Hey,
               I have been trying to install Snipe in ubuntu (Aws ec2), i had done all the steps till the installation of composer, while i try to install composer (composer install --no-dev --prefer-source) it's throwing the error like below

Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#2 {main}
  thrown in /var/www/snipe-it/app/Exceptions/Handler.php on line 40
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/snipe-it/app/Exceptions/Handler.php on line 40
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

even if i skip this step and go to generating the artisan key again some error like below is showing

PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#2 {main}
  thrown in /var/www/snipe-it/app/Exceptions/Handler.php on line 40
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report()
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/snipe-it/app/Exceptions/Handler.php on line 40

What should i do now..?

**Comment by gramakri** [comment] 2020-10-26 22:08
I hit pretty much the same issue when trying to update the Cloudron package to the latest 5.x release.

**Comment by snipe** [comment] 2020-10-26 22:10
https://snipe-it.readme.io/docs/installation-issues#fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by snipe** [comment] 2020-10-26 22:19
I don't have an idea what Cloudron is, but if it's anything like Softaculous, etc, you'd have to take that up with them, as their upgrade process is likely flawed. I see this tho: https://forum.cloudron.io/topic/3244/snipe-it-is-now-available

Those types of companies never actually talk to us, and we're not part of their upgrade/installation process, so we don't really have any god ways of troubleshooting them. 

<blockquote><img src="https://forum.cloudron.io/assets/uploads/profile/3-profileavatar.jpeg" width="48" align="right"><div><img src="/assets/uploads/system/favicon.ico?v=l2r6es1qcds" height="14"> Cloudron Forum</div><div><strong><a href="https://forum.cloudron.io/topic/3244/snipe-it-is-now-available">Snipe-IT is now available</a></strong></div><div>Hi all, Snipe-IT is now available in the app store. It's marked as unstable at the moment, just ironing out some minor issues. Most of the packaging work was done by @jimcavoli (thanks!) Code: https://git.cloudron.io/cloudron/snipeit-app App store link: h...</div></blockquote>

**Comment by snipe** [comment] 2020-10-26 22:20
@gramakri also, I don't even see 5x listed here? https://www.cloudron.io/store/com.snipeitapp.cloudronapp.html

<blockquote><img src="https://api.cloudron.io/api/v1/apps/com.snipeitapp.cloudronapp/versions/0.3.0/icon" width="48" align="right"><div>Cloudron</div><div><strong><a href="https://www.cloudron.io/store/com.snipeitapp.cloudronapp.html">Install Snipe-IT - Open Source IT Asset Management</a></strong></div><div>Effortlessly run Snipe-IT on your server and keep it up-to-date and secure.</div></blockquote>

**Comment by gramakri** [comment] 2020-10-26 22:21
@snipe Thanks, I found several similar issues https://github.com/snipe/snipe-it/issues/4673, https://github.com/snipe/snipe-it/issues/7174, https://github.com/snipe/snipe-it/issues/6104 and https://github.com/snipe/snipe-it/issues/4470 . Still investigating what the root cause is.

**Comment by snipe** [comment] 2020-10-26 22:22
@gramakri as mentioned in the docs (and in all of those tickets), it's almost always an issue in the .env, or some cached files that need to be deleted. 

It's a difficult one to troubleshoot, because basically if *anything* goes wrong and prevents the stack from fully loading, it can toss out that message. Basically, the framework fails to load (again, usually for the reasons I mentioned), and it farts out so hard that the logging system can't even load properly to give you a better error.

**Comment by gramakri** [comment] 2020-10-26 22:23
> Those types of companies never actually talk to us

I am one of the co-founders of Cloudron :-D  We only very recently added Snipe-IT, it was contributed by our community. I am updating it to 5.x as we speak and that is when I hit the issue. I have been meaning to reach out to you about the package but this was published not even 2-3 weeks ago and wasn't "stable" yet.

**Comment by snipe** [comment] 2020-10-26 22:24
Yeah, we just released v5 last monday

**Comment by shah-id** [comment] 2021-03-11 06:09
For anyone else who's facing this,
set `GOOGLE_MAPS_API=` to `GOOGLE_MAPS_API=''` in `.env`

**Comment by sumarna14** [comment] 2021-05-07 05:48
> For anyone else who's facing this,
> set `GOOGLE_MAPS_API=` to `GOOGLE_MAPS_API=''` in `.env`

Yup thanks a lot it helped me, 
works like a charm So what exactly is it for?

![bitmoji](https://sdk.bitmoji.com/render/panel/fbf70eb2-c012-465e-9c1e-7b092675dfd8-22d72019-6c9c-4d0f-986f-0349460bc4d7-v1.png?transparent=1&palette=1&width=246)

**Comment by 0xpr03** [comment] 2021-06-14 08:38
I've had some stuff in `storage/framework/cache` that got copied over from v4

**Comment by francogp** [comment] 2021-08-13 13:16
I have this problem, and I already set  GOOGLE_MAPS_API= to GOOGLE_MAPS_API='' in .env

**Comment by snipe** [comment] 2021-08-13 23:16
@francogp Please paste in your .env file here, XXXXXing out any sensitive stuff like passwords.

**Comment by francogp** [comment] 2021-08-14 01:05
> @francogp Please paste in your .env file here, XXXXXing out any sensitive stuff like passwords.

it was a permission thing. I change the snipe-it folder owner to www-data and it work

**Closed as completed** 2021-08-28 01:58 UTC

**Comment by sseidl1984** [comment] 2022-08-05 08:55
same here 
cant fix it

**Comment by snipe** [comment] 2022-08-05 12:30
@sseidl1984 
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

The Class Log issue is mentioned in our documentation.
