### ISSUE TITLE
[Feature Request]: Adding custom fields to locations

### ISSUE THREAD

**Issue by marche14** [grokability/snipe-it#13194] opened 2023-06-22 12:35 UTC
### Is your feature request related to a problem? Please describe.

I want to add 2 fields to Locations, phone number and FAX, but i can't

### Describe the solution you'd like

Basically I would like the possibility to add custom fields to locations, like telephone number and FAX without putting them in another field.

### Describe alternatives you've considered

As an alternative, I would personally modify, to the best of my ability, the php files concerning the search (already done), the list of fields in the filters, and the edit of the fields (so that I can modify them such as the name or the city), but being a bit new to this project, I'm having trouble finding all the various files needed. Could you show me the php files concerning the search (already done), the list of fields in the filters, and the edit of the fields (so that I can modify them such as the name or the city)? I have already edited the SQL table and I can view them in the upper right when clicking on a location as well as filter by that data in the search bar, but I can't find the file regarding the view in the actual table of the site, like any other accessory, nor the one that allows me to show the fields when I want to modify them.

**Comment by snipe** [comment] 2023-07-05 15:47
Duplicate of https://github.com/snipe/snipe-it/issues/4261

**Closed as completed by snipe** 2023-07-05 15:47 UTC

**Comment by rodrigobuttow** [comment] 2025-03-25 21:34
Do you have any feedback on this suggestion?
