### ISSUE TITLE
Clicking a parent location does not show assets in child location

### ISSUE THREAD

**Issue by NAP-LN** [grokability/snipe-it#11953] opened 2022-10-12 06:35 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When settings a location we have established a heirachy.
Location A 
- Location A-b, Location A is parent
- Location A-c, Location A is parent

When trying to see all the assets within 'location A', clicking 'Location A' does not show assets in location A-c or A-b. We manually have to enter those locations to get total asset list. 

### Reproduction steps

1. Create location heiracrchy and set a parent location
2. Clicking parent location does not consolidate all the assets that are under the parent location. Each child location is independant.

### Expected behavior

Clicking a parent location should show all assets under that parent location, inclusive of all child assets. There is a location heading within the locations UI so we can still tell if it is in a child location or the parent.

### Screenshots

![locations 1](https://user-images.githubusercontent.com/115613055/195267470-227f9e05-1233-4bec-b749-f10527fab025.png)
![locations 2](https://user-images.githubusercontent.com/115613055/195267487-91acd092-af72-4eef-8d4e-9d35b7b7b67b.png)

### Snipe-IT Version

HOSTED version

### Operating System

HOSTED version

### Web Server

HOSTED version

### PHP Version

HOSTED version

**Comment by arcticash** [comment] 2022-11-16 12:46
I would also be very interested in this feature, the nested locations seem to need more attention as really I agree, the parent location should display a summary of all the child locations below (eg. Room A with children RACK 1, RACK 2 ... viewing room A should show items located in both Rack 1 and Rack 2)

**Comment by DrekiDegga** [comment] 2024-04-09 19:31
This is a feature we would use a great deal.

**Comment by snipe** [comment] 2024-10-30 09:28
Duplicate of #4546

**Closed as completed by snipe** 2024-10-30 09:28 UTC
