### ISSUE TITLE
I can assign (checkout) an undeployable asset 

### ISSUE THREAD

**Issue by hmacugova** [grokability/snipe-it#9131] opened 2021-02-12 09:44 UTC
#### Please confirm you have done the following before posting your bug report:

- [ no] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Asset with "pending" or "undeployable" status is possible to checkout to user/asset/location.

**To Reproduce**
1. Go to 'list all asset'
2. Click on 'checkout asset with pending or undeployable status'
3. Assign asset to user

**Expected behavior**
Assets with pending or undeployable status cannot be checked out.

**Screenshots**
![step1](https://user-images.githubusercontent.com/74250943/107750474-5f480780-6d1c-11eb-8874-d9e172ce0bb5.JPG)
![step2](https://user-images.githubusercontent.com/74250943/107750478-5fe09e00-6d1c-11eb-9fdc-22a86b59b4b9.JPG)
![step3](https://user-images.githubusercontent.com/74250943/107750479-5fe09e00-6d1c-11eb-9c7b-fe861c0a24d4.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version: Version v5.0.12 - build 5705 (master)
 - OS: Debian 10
 - Web Server: Apache2
 - PHP: 7.3.19-1~deb10u1

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - Browser Firefox 
 - Version 78.7.1esr (64-bit)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? NO
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by boring10** [comment] 2021-02-12 11:51
I can confirm that this is the case for the hosted version as well (v5.0.12 - build 5705 (master)). My guess is that the title is not correct (see image) since it is showing as "undefined".

![Checkout - Undeployable](https://user-images.githubusercontent.com/35600612/107764679-9ad3d900-6cfe-11eb-852c-5093f63f332d.png)

**Comment by hmacugova** [comment] 2021-02-12 13:25
Yes, but pending status do not have "undefined" and also can be assigned

**Comment by boring10** [comment] 2021-02-12 13:39
You're right. At least this issue does not appear to be a problem with archived assets.

**Comment by LegendaryGameworks** [comment] 2022-02-21 22:06
We're also able to checkout an undeployable assets to an asset or user. Anyone have a workaround or resolution for this?

**Comment by snipe** [comment] 2022-02-22 00:26
I can't reproduce this on the demo or locally.

<img width="1128" alt="Screen Shot 2022-02-21 at 4 24 27 PM" src="https://user-images.githubusercontent.com/197404/155041786-5a42643e-6c20-4e0e-a343-df06c9df117e.png">

(note the checkout button is disabled)

<img width="1394" alt="Screen Shot 2022-02-21 at 4 26 16 PM" src="https://user-images.githubusercontent.com/197404/155041904-2ef953f3-9cfe-44b9-b0ef-f0b364a585fb.png">

Can I see your status labels page and the status you assigned to the asset you're referring to?

**Comment by snipe** [comment] 2022-02-22 00:30
Same for pending assets.

<img width="1126" alt="Screen Shot 2022-02-21 at 4 29 19 PM" src="https://user-images.githubusercontent.com/197404/155042110-4d7f8961-84ca-429a-a86a-79a675dcce01.png">

**Closed as completed** 2022-09-28 23:54 UTC
