### ISSUE TITLE
Column selections resets to default

### ISSUE THREAD

**Issue by FG-Lars** [grokability/snipe-it#10675] opened 2022-02-15 10:38 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have to enable view of the Country column each time I open the Locations list

### Reproduction steps

1. Click Settings
2. Click Locations
3. Open column selection
4. Enable Country
5. Browse to asset list
6. Click Settings
7. Click Locations

### Expected behavior

I expect the columns I enable to be saved in the view.

### Snipe-IT Version

v5.3.8 - build 6619 (master)

### Operating System

Debian 11

### Web Server

Apache2

### PHP Version

7.4.25

**Comment by FG-Lars** [comment] 2022-02-22 07:11
Edited the heading and text, as it seems to be a general issue for all lists.

**Comment by snipe** [comment] 2022-02-22 17:41
Yes this is a known issue that we're working on.

**Comment by snipe** [comment] 2022-03-01 08:26
Closing as duplicate of #10482

**Closed as completed by snipe** 2022-03-01 08:26 UTC
