### ISSUE TITLE
Custom fields/sets to the Asset maintenance page

### ISSUE THREAD

**Issue by danielnovello-pf** [grokability/snipe-it#9921] opened 2021-08-11 12:07 UTC
**Server (please complete the following information):**
 - Snipe-IT Version
    Hosted version, so latest?
 - OS: [e.g. Ubuntu, CentOS]
    Hosted version
 - Web Server: [e.g. Apache, IIS]
    Hosted version
 - PHP Version
    Hosted version

**Is your feature request related to a problem? Please describe.**
We require addition fields in the asset maintenance page, so yeah. We cannot use this feature until we can get this.

**Describe the solution you'd like**
The same way you can add custom fields and field sets to Assets, we would like the ability to add additional custom fields to the Asset Maintenance page

**Describe alternatives you've considered**
Adding the additional fields to the asset is cumbersome and makes the page way too long, nit to mention confusing

**Comment by francogp** [comment] 2021-08-16 18:27
already reported almost 3 years ago...

**Comment by snipe** [comment] 2021-08-18 04:30
Duplicate of #4261

**Closed as completed by snipe** 2021-08-18 04:30 UTC
