### ISSUE TITLE
License->Create page (not licenses main page) leads to 404 Not Found

### ISSUE THREAD

**Issue by Tyree** [grokability/snipe-it#12055] opened 2022-11-01 18:51 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I can load the licenses page, but not the license create page. I am running on XAMPP because I already had a XAMPP server spun up for other uses. I removed XAMPP's own licenses alias and everything else seems to be functioning fine.

The apache error logs:
```
[Tue Nov 01 14:36:30.368708 2022] [cgi:error] [pid 12296:tid 1856] [client 10.0.0.175:57044] AH02811: script not found or unable to stat: C:/xampp/htdocs/snipe-it/publiccreate, referer: http://snipe-it.ap.local/licenses
[Tue Nov 01 14:36:34.040596 2022] [cgi:error] [pid 12296:tid 1856] [client 10.0.0.175:57044] AH02811: script not found or unable to stat: C:/xampp/htdocs/snipe-it/publiccreate
[Tue Nov 01 14:36:42.150074 2022] [cgi:error] [pid 12296:tid 1840] [client 10.0.0.175:57049] AH02811: script not found or unable to stat: C:/xampp/htdocs/snipe-it/publiccreate, referer: http://snipe-it.ap.local/
```
All other create pages seem to work: assets, components, user, etc.

### Reproduction steps

1.Click Create New->License
2.404 Page opens

### Expected behavior

New license page should open

### Snipe-IT Version

v6.0.12 build 8824 (g915186883)

### Operating System

Windows

### Web Server

XAMPP

### PHP Version

7.4.28

### Browser

Chrome and Edge

### Additional context

Manual fresh install

**Comment by snipe** [comment] 2022-11-01 18:57
I'm not sure what the ask is here. This is already documented. 

- https://snipe-it.readme.io/docs/xampp
- https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases

We cannot (and would not) make changes to the built-in aliases on a web server. 

<img width="809" alt="Screen Shot 2022-11-01 at 11 53 54 AM" src="https://user-images.githubusercontent.com/197404/199314996-7fe0c753-c34a-48d2-a526-359bde5b0aec.png">

Duplicate of #6647, #5011, #4897, #4407, & #4031.



<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/xampp">XAMPP</a></strong></div><div>Download the Snipe-IT project using one of the methods on the Download page. We strongly recommend installing via Git. Follow the directions in the configuration section of the normal setup. Download XAMPP from the official site. In order to install required library dependencies, you'll need to inst...</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/xampp#remove-built-in-aliases">XAMPP</a></strong></div><div>Download the Snipe-IT project using one of the methods on the Download page. We strongly recommend installing via Git. Follow the directions in the configuration section of the normal setup. Download XAMPP from the official site. In order to install required library dependencies, you'll need to inst...</div></blockquote>

**Closed as completed by snipe** 2022-11-01 18:57 UTC

**Comment by Tyree** [comment] 2022-11-01 21:24
I DID remove the built in alias per the documentation you pasted. As far as I can tell from the documentation, the licenses page wouldn't even work if that alias was still in place. Not just the create page. So no, this is not the documented issue. At least not as it's written.

**Comment by Tyree** [comment] 2022-11-02 11:20
I had already followed the documentation to get to where I described above. What is in the documentation does not work. The licenses page loads fine after following the documentation, it's just the licenses create page that doesn't. That's not what the documentation describes.

None of the other issues you linked as being a duplicate is the same scenario. They are getting "Object not found" and/or getting an index when loading the licenses page. Again, license page loads just fine for me (which would indicate the XAMPP alias has been overridden). It's just the license create page that has an issue.

I think there's some missing details in the documentation that would alleviate this for XAMPP users.

Turns out, what worked for me (in addition to changing the built-in XAMPP alias) is what is described by @brijeshdave in https://github.com/snipe/snipe-it/issues/4407 where he commented out:
`ScriptAlias /licenses/ "C:\xampp\htdocs\snipe-it\public"`
in the httpd-vhosts.conf file, which the documentation instructs to add.

I think some improvement could be made to the documentation to make XAMPP a viable option when folks are already using it. Trying to spin up IIS or WAMP alongside XAMPP can be a serious pain.

**Comment by mrzeroo** [comment] 2025-06-09 18:17
> I had already followed the documentation to get to where I described above. What is in the documentation does not work. The licenses page loads fine after following the documentation, it's just the licenses create page that doesn't. That's not what the documentation describes.
> 
> None of the other issues you linked as being a duplicate is the same scenario. They are getting "Object not found" and/or getting an index when loading the licenses page. Again, license page loads just fine for me (which would indicate the XAMPP alias has been overridden). It's just the license create page that has an issue.
> 
> I think there's some missing details in the documentation that would alleviate this for XAMPP users.
> 
> Turns out, what worked for me (in addition to changing the built-in XAMPP alias) is what is described by [@brijeshdave](https://github.com/brijeshdave) in [#4407](https://github.com/grokability/snipe-it/issues/4407) where he commented out: `ScriptAlias /licenses/ "C:\xampp\htdocs\snipe-it\public"` in the httpd-vhosts.conf file, which the documentation instructs to add.
> 
> I think some improvement could be made to the documentation to make XAMPP a viable option when folks are already using it. Trying to spin up IIS or WAMP alongside XAMPP can be a serious pain.

Commenting this line solved the problem, Thanks ;-)
/licenses/ "C:\xampp\htdocs\snipe-it\public"` in the httpd-vhosts.conf file
