### ISSUE TITLE
[Feature Request]: Custom Fields in Licences

### ISSUE THREAD

**Issue by Venoxi24** [grokability/snipe-it#15448] opened 2024-09-04 08:53 UTC
### Is your feature request related to a problem? Please describe.

I need more fields for the licenses: 
Cost center 
Internal invoice number
External invoice number
Status
Payment intervals

I cannot define these in a license.

### Describe the solution you'd like

It would be nice to be able to assign custom fields to licenses, like with asset models. For example, you could add cost centers or similar for licenses. In general, you could also see whether it is possible to create custom fields for all categories.

**Comment by snipe** [comment] 2024-09-04 14:19
Duplicate of #4261

**Closed as completed by snipe** 2024-09-04 14:19 UTC
