### ISSUE TITLE
[Feature Request]: Add time to expected checkin date

### ISSUE THREAD

**Issue by alex9947** [grokability/snipe-it#13266] opened 2023-07-06 19:39 UTC
### Is your feature request related to a problem? Please describe.

My team and I have run into the issue of needing assets on an hourly basis and realized that snipeit only offers days when prompted to enter expected check in date while checking out an asset.

### Describe the solution you'd like

When checking out an asset and filling in the expected check in date, it would be nice if there was a time option input box. On the assets page the column for expected check in date could look like the checkout date column where the time is displayed along with the date. That way users could easily see how long an asset will be checked out for to the hour in case if they needed that specific asset the same day. 
Also a nice additional feature to have would be to sync email notifications with the hourly increments, as in when the check in time approaches maybe have an option to send a reminder email to the user to check it in (similar to what y'all already have but just up to the hour).

![image](https://github.com/snipe/snipe-it/assets/44882419/0011c19f-2321-404f-ac52-88ee731c4a21)

### Describe alternatives you've considered

I've tried going through the source code myself to try an put together a temporary work around of another input box for time beside the input expected checkin date, what file(s) contain the sections for input for the expected checkin date as well as what file(s) contain the display of expected checkin date on the assets page? Also I'm assuming there will be some backend changes needed as well, if I could get pointed to the code that manages the expected checkin date in the data base that would be appreciated as well.

### Additional context

![image](https://github.com/snipe/snipe-it/assets/44882419/f8ba2420-b04b-4c4a-8202-d602166af312)

![image](https://github.com/snipe/snipe-it/assets/44882419/b08bd400-b796-4731-9b24-d80d02235311)

**Comment by snipe** [comment] 2023-07-19 11:38
Duplicate of #11580

**Closed as completed by snipe** 2023-07-19 11:38 UTC
