### ISSUE TITLE
[Feature Request]: Checkout without Checkin.....

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [grokability/snipe-it#15294] opened 2024-08-14 11:52 UTC
### Is your feature request related to a problem? Please describe.

When performing asset moves/audits in bulk, having to check-in an asset before check-out takes time.

### Describe the solution you'd like

The ability to check-out an already checked-out asset - Behind the scenes, the check-in can still happen, but the user only needs to perform a single action.

### Describe alternatives you've considered

I've scripted this in the past, but that's not practical when my team want to update Snipe-IT when I'm on holiday.......

**Comment by snipe** [comment] 2024-08-14 11:53
Duplicate of #5834 and #8280

**Closed as completed by snipe** 2024-08-14 11:53 UTC
