### ISSUE TITLE
Customize dashboard/reports

### ISSUE THREAD

**Issue by Richkos** [grokability/snipe-it#10016] opened 2021-08-31 14:32 UTC
#### Expected Behavior - Enable features to customize the dashboard page

We recently acquired the pro-support and we like to know if there is a chance to customize the dashboard page, like disable acessories and licenses and just use components and consumables and manage effective reports, like showing total and remaining components of a specific category similar to filter/pivot
-----

#### Actual Behavior

Dashboard show every item and the reports are not very useful.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  fresh install
- Version of Snipe-IT you're running - v4.9.5 build 4482 (g5b68a321a)
- Version of PHP you're running - 7.2.33
- Version of MySQL/MariaDB you're running - mysql  Ver 15.1 Distrib 10.1.10-MariaDB, for Linux (x86_64) using readline 5.1
- What OS and web server you're running Snipe-IT on - chrome
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment] 2021-09-11 02:14
That's not currently possible, but it's something we're considering for future releases

**Comment by snipe** [comment] 2022-09-28 23:48
Duplicate of https://github.com/snipe/snipe-it/issues/7297

**Closed as completed by snipe** 2022-09-28 23:48 UTC
Labels: :woman_technologist: ready for dev, :heart: feature request
