### ISSUE TITLE
Transfer of Assets

### ISSUE THREAD

**Issue by chong-doh** [grokability/snipe-it#8997] opened 2021-01-12 14:28 UTC
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.16 build 4018
 - OS: ?
 - Web Server: ?
 - PHP Version : 5.4.35

As our org is growing a lot of situations arise where I have to transfer assets from one user to the next. The story usually goes someone who has had control of 15+ assets moves to another position or leaves the company which means those assets now have to be transferred to the next person who fills in that vacancy. This happens A LOT. Especially when it comes to items that are assigned to temps, part timers, contractors, and designers who are constantly changing teams, projects, etc. It's actually astonishing that something like this does not exist in the first place.

The solution I would like is as follows. User A has assets assigned to them. I would like the ability to view those assets (which already exists) and highlight multiple assets to be transferred to user B (which does not exist).

I haven't really considered any alternatives because normally the simple answer is the best answer. Unless you want to build in the ability where you go to a user's page, then have the feature to look up multiple assets and assign it to the user, the system prompts that these assets are already assigned to another user, would you like to re-assign them anyway? Then you choose yes.

No real other information for this. It's easy to see. Someone has multiple assets. At the current state you have to check in each item. Then you have to check out each item again to another user instead of being able to transfer them in one action.

**Comment by UserGoodtm** [comment] 2021-02-21 21:21
I agree, such a function is needed

**Comment by hegdemaahi24** [comment] 2024-04-26 09:06
+1
This feature most important, when the asset can be transferred to another user
Now we need to checkin the asset and later again we need checkout. More work here

**Comment by snipe** [comment] 2024-08-14 11:54
Duplicate of #5834 and #8280

**Closed as completed by snipe** 2024-08-14 11:54 UTC
