### ISSUE TITLE
Assets accepted/declined

### ISSUE THREAD

**Issue by manukean** [grokability/snipe-it#12311] opened 2023-01-05 08:42 UTC
### Is your feature request related to a problem? Please describe.

I have such a problem, if the asset was sent to the user but the user did not accept and did not reject, and then the same asset was re-sent to another user and he accepts the asset, and then the first user rejects the asset, then the asset becomes without a user.

### Describe the solution you'd like

assets were not left without a user.

**Comment by inietov** [comment] 2023-01-30 23:35
@Karmanuk  Can't reproduce the issue, while the asset is not accepted/declined you can't assigned it to other user. If you checkin the asset so you can re-assign it, the asset disappears from the accept/decline list of the first user. 

Can we have more info? What steps did you follow to find the error? What version of Snipe-It are you running? Thanks in advance, and thanks for your report!

**Closed as completed** 2023-04-07 10:54 UTC

**Comment by akeshell** [comment] 2024-04-02 03:03
I ran into the same problem, Version v6.3.1, can you add Settings to cancel links in emails: I have read and agree to the terms of use, and have received this item.
There is no need for the user to accept/reject, and the email is only used for notification
