### ISSUE TITLE
[Feature Request]: Save advanced search

### ISSUE THREAD

**Issue by gilgalock** [grokability/snipe-it#13801] opened 2023-10-26 09:39 UTC
### Is your feature request related to a problem? Please describe.

I want to be able to have a report of all assets in a certain status with a certain location.
I can achieve this with Advanced search, but I am not able to save this query, nor save the URL as the custom query is not appended. Therefore I have to fill out the advanced search form every time for the same query.

### Describe the solution you'd like

It would be very helpful to be able to save advanced search queries, or get a custom url to save as a bookmark. 

### Describe alternatives you've considered

I do not see an alternative. As far as I know, there is not way to create a custom dashboard in snipe it to display assets based for multiple field search

**Comment by snipe** [comment] 2023-10-30 15:10
Duplicate of [#9884](https://github.com/snipe/snipe-it/issues/9884)

**Closed as completed by snipe** 2023-10-30 15:10 UTC
