### ISSUE TITLE
[Feature Request]: add ldap Company Field

### ISSUE THREAD

**Issue by conan522** [grokability/snipe-it#14033] opened 2023-12-14 05:13 UTC
### Is your feature request related to a problem? Please describe.

Can not sync "Company" data by ldap

### Describe the solution you'd like

Wish can add ldap Company Field and Can sync "Company" data by ldap

**Comment by wiggywoosaa** [comment] 2024-01-29 18:57
+1 for this please

**Comment by snipe** [comment] 2024-08-10 17:34
Duplicate of #10698

**Closed as completed by snipe** 2024-08-10 17:34 UTC
