### ISSUE TITLE
Feature Request - Store accepted and signed EULA

### ISSUE THREAD

**Issue by bruce2004x** [grokability/snipe-it#7891] opened 2020-03-10 19:30 UTC
#### Expected Behavior (or desired behavior if a feature request)

We expect that after an end-user receives and signs the EULA, it can be store in any place into de application, so that we can print it later or , in our case, it also works as evidence for the assigment. Other people have requested this in the past, but those cases have been closed due to lack of follow-up.

-----

#### Actual Behavior

The user receives an email with the asset assigment, he accepts and signs, but that EULA and signature are not store in any place.

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running: v4.8.0  build 4186

I just want to say THANKS for making this awesome tool!

**Comment by SirajQu** [comment] 2020-03-11 09:47
Would really love to have this feature, as for now it only shows the accepted/declined status if we go to that specific asset then click on the history which is burdensome if we have lots of assets and users expecting their responds, also it would be better if we can generate the acceptance status in custom report.

**Comment by bruce2004x** [comment] 2020-03-28 22:40
Just to know if there's any comment about this improvement :-)

**Comment by bruce2004x** [comment] 2020-05-20 13:29
Dear admins hope your families and you are well, regarding this request,  any answers related to this?

**Comment by ifimust-okay** [comment] 2020-05-22 15:04
+1, This would be an excellent feature.  Our HR department loves how Snipe-IT has simplified their understanding of who has what and when they received it, but the only element lacking is the ability for them to print off an EULA that includes the verbiage and signature that the employee actually received (since the verbiage can change, legally speaking we would have to provide logs to show the change, if any).

Thanks, Snipe - this is my second time implementing Snipe-IT at a company and both times it's been very well-received.

**Comment by thomisus** [comment] 2020-06-25 15:46
+1 for this feature. It is really needed in order to track received items.

**Comment by sarang2502** [comment] 2020-06-28 23:11
+1 We recently implemented SnipeIT and found this feature missing. This is very important for proving Eula is actually signed by users. Please add it to feature list.

Thanks for the great tool.

**Comment by subdriven** [comment] 2020-06-30 15:37
Going to throw my 2c in here as well for having this feature. Would be great for the reasons pointed out.

**Comment by thomisus** [comment] 2020-08-29 18:59
Still relevant.. need this feature

**Comment by Speed1** [comment] 2020-09-02 08:37
+1

**Comment by bruce2004x** [comment] 2020-10-20 18:55
Still waiting ;-)

**Comment by thumperest** [comment] 2020-11-12 09:51
+1 :)

**Comment by ahardylaniertech** [comment] 2021-01-06 15:48
+1 here as well!

**Comment by thomisus** [comment] 2021-01-28 12:24
+1

**Comment by seanlawson932** [comment] 2021-02-01 13:52
Would love to see this implemented as soon as possible. Thanks.

**Comment by bruce2004x** [comment] 2021-06-11 14:20
Dear @snipe have you taken a look to this request?

**Comment by bruce2004x** [comment] 2021-08-13 16:53
Just a follow-up

**Comment by gferreiraw** [comment] 2022-01-12 11:09
+1

**Comment by Kithygh** [comment] 2022-03-23 20:01
Very necessary to be able to associate a signature with the verbiage of what was signed.

**Comment by snipe** [comment] 2022-03-23 21:07
Yes, we are aware, that's why there's an open PR under review.

**Comment by Kithygh** [comment] 2022-03-24 20:06
> Yes, we are aware, that's why there's an open PR under review.

It has been 2 years since this was created and there is nothing listed under Assignee, Labels, Projects, Milestone, or Development on this page.

**Comment by snipe** [comment] 2022-03-24 20:07
I just told you there is an open PR for it...

**Comment by snipe** [comment] 2022-03-24 20:09
And actually, this is a duplicate of #3019

**Closed as completed by snipe** 2022-03-24 20:09 UTC
