### ISSUE TITLE
Consumables assign to asset

### ISSUE THREAD

**Issue by svcgithubtestoil** [grokability/snipe-it#9760] opened 2021-06-28 18:49 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 5.1.7 6136
 - OS: Ubuntu 20.04
 - Web Server: Apache2
 - PHP Version 7.4

Consumables are only assignable to Users

Would like to see Consumables assignable to users and assets as with Licenses

IE:

Printers are setup as assets with serial numbers, models and categories.

Consumables like Toners and Service kits should be assignable to Assets 

This would allow to track consumable costs, usages and notifications of consumables by Asset such as a printer.

**Comment by snipe** [comment] 2021-09-11 00:46
Closed as duplicate of #9634

**Closed as completed by snipe** 2021-09-11 00:46 UTC
