### ISSUE TITLE
[Feature Request]: "Asset by status" in the dashboard merging ready to deploy and deployed assets

### ISSUE THREAD

**Issue by achuet** [grokability/snipe-it#11892] opened 2022-09-29 11:19 UTC
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/73993090/193017581-6cbc3c23-20a2-406b-977d-20225633b1d8.png)

"Asset by status" in the dashboard merging ready to deploy and deployed assets. Couldn't any option to show ready to deploy and deployed assets separately

### Describe the solution you'd like

I believe having a separate status for Deployed (Checked out) assets will resolve the issue.

**Comment by snipe** [comment] 2022-09-30 00:11
Duplicate of #11521

**Closed as completed by snipe** 2022-09-30 00:11 UTC
