### ISSUE TITLE
Cannot assign manager to user / On dashboard, recent activities are sorted from oldest to most recent items

### ISSUE THREAD

**Issue by memph1sx** [grokability/snipe-it#8599] opened 2020-10-23 13:18 UTC
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

**Describe the bug**
**On dashboard, recent activity, assigned assed are shown from older to latest instead from latest to older.

When assigning a manager to a user we get the error "The manager id and users.id must be different.", it happens on Demo and our instance of SnipeIT**

**Expected behavior**
We expect to be able to assign a manager to a user (it used to work on 4.9.5)

We used to see activites on dashboard from latest to oldest

**Screenshots**

![image](https://user-images.githubusercontent.com/73347067/97007674-c17fc100-150f-11eb-8a24-01a878225b5a.png)
![Capture](https://user-images.githubusercontent.com/73347067/97007721-d3f9fa80-150f-11eb-884b-e04a32eae200.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version , **5.0.2**
 - OS: [e.g. Ubuntu, CentOS], **Ubuntu**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **PHP 7.3.23-4+ubuntu18.04.1+deb.sury.org+1**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade from 4.9.5 to 5.0.2**
- What OS and web server you're running Snipe-IT on **Ubuntu 18.04, Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc), **all of them, issues persist**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **we did not modify the database manually**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment] 2020-10-23 13:19
Duplicate of #8561 and #8537

**Closed as completed by snipe** 2020-10-23 13:19 UTC
