### ISSUE TITLE
Adding/removing columns in /hardware resets to initial view after a page refresh.

### ISSUE THREAD

**Issue by elvinu** [grokability/snipe-it#10754] opened 2022-03-01 08:09 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hello, 
This is strange: If I select or deselect columns in /hardware page after I leave  or refresh the page it is resetting to my old view. It seems this _bug_ was before 5.40 because I updated the app today and the issue still persists.

I have checked on multiple computers and different browsers and its the same.

I get no errors with Debug ON

The cookie with the view exists but it seems it remains unchanged even if I make any modifications. I think is this one `hardware.index.bs.table.columns` ?

### Reproduction steps

1. Check/Uncheck columns in hardware
2. Refresh the page
3.
...

### Expected behavior

To remember the columns I selected  or deselected

### Snipe-IT Version

5.4.0 - build 6685 (master)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Windows

### Browser

Chrome

### Version

98

**Comment by snipe** [comment] 2022-03-01 08:26
Closing as duplicate of #10482

**Closed as completed by snipe** 2022-03-01 08:26 UTC
