### ISSUE TITLE
[Feature Request]: Asset Tags per Categories

### ISSUE THREAD

**Issue by jlcitdept** [grokability/snipe-it#13700] opened 2023-10-03 12:30 UTC
### Is your feature request related to a problem? Please describe.

The feature request is not related to a problem.

### Describe the solution you'd like

It would be great if one could auto generate asset tags per categories. In other words, a way to assign a particular prefix per category. Example below:

Category: Display/Monitor
Prefix: DP-
Length: 3 
Result: DP-001, D-P002...

Category: Workstation
Prefix: WT-
Length: 3 
Result: WT-001, WT-002...

**Comment by snipe** [comment] 2023-10-05 15:59
Duplicate of #9013

**Closed as completed by snipe** 2023-10-05 15:59 UTC
