### ISSUE TITLE
Teams webhook integration is not compatible with newly required MS Teams workflows aka. power automate connectors

### ISSUE THREAD

**Issue by mus455** [grokability/snipe-it#15425] opened 2024-08-30 07:22 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Since MS is retiring the old office 365 connectors: [Retirement of Office 365 connectors within Microsoft Teams
](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/), i tried using the offical recommended methods (listen in the provided URL), and making my own but when i try to test the connection the teams or general webhook settings gives me an error: 
![Posnetek zaslona 2024-08-30 080726](https://github.com/user-attachments/assets/b0f785a7-1527-4c5e-85cd-deccdf64007f)
The same issue is documented on other projects: [grafana issue](https://github.com/grafana/grafana/issues/90139), [also grafana](https://github.com/grafana/alerting/pull/221), [librenms](https://community.librenms.org/t/depricated-0365-connector-on-ms-teams/24897/5).
I used the office 365 connector for MS Teams (documented in snipeit docs) before and it worked completely fine, but since it will be depracated soon, i want to migrate to the new method (workflows or power automate connectors). 

### Reproduction steps

1. Make a new connector in the teams via MS Teams workflows [workflows tutorial](https://support.microsoft.com/en-us/office/create-incoming-webhooks-with-workflows-for-microsoft-teams-8ae491c7-0394-4861-ba59-055e33f75498) power automate or using the templates listed in [Retirement of Office 365 connectors within Microsoft Teams
](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/)
2. Test the connection by suppling the MS provided URL (ending in ...westeurope.logic.azure.com..... or similar) via integrations -> update webhook settings -> MS Teams
3. The MS Teams integration test returns a 400 error

### Expected behavior

Expected behaviour would be that snipeit sends a test message/card in teams channel/chat.

### Snipe-IT Version

v7.0.11 - build 15044 (master)

### Operating System

Rocky linux 8

### Web Server

Apache

### PHP Version

 8.2.13

### Operating System

Windows

### Browser

Firefox and Edge

### Version

newest

**Comment by snipe** [comment] 2024-08-30 09:46
Duplicate of #15080

**Closed as completed by snipe** 2024-08-30 09:46 UTC
