### ISSUE TITLE
Extra field for Licences / Custom field support

### ISSUE THREAD

**Issue by S0QR2** [grokability/snipe-it#8305] opened 2020-08-07 08:28 UTC
**Server (please complete the following information):**
 - 494
 - OS: CentOS
 - Web Server: Apache

**Is your feature request related to a problem? Please describe.**
Licences could need an update, the feature ist great and needed in a fully integrated inventory system. Snipe-It does such a great job on the Hardwareinventory in that regard. Adding the custom fieldsets to licences would solve alot of problems.

**Describe the solution you'd like**
Abillity to add custom field sets to software licences.
Notification emails when licences are about to expire 

**Describe alternatives you've considered**
An extra field for a link to an internal ressource like a weblink or a custom eventhandler link like osecm://12312312

**Comment by sjackson0109** [comment] 2020-09-02 19:55
would like licenses to include:
- name
- version
- Serial-Number
- License-Key
- Key-File (XML/JSON/ANYOTHERFILE_TYPE - with an import-file option)
- Purchase Order No
- Assigned-To option (assets/location/user)
- Start date
- Expiry date

**Comment by sjackson0109** [comment] 2020-12-27 13:24
Yes

**Comment by S0QR2** [comment] 2020-12-27 13:39
Yes--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.12.20, 19:23 schrieb "stale[bot]" <notifications@github.com>:

   
  Is this still relevant? We haven't heard from anyone in a bit. If so, please comment with any updates or additional detail. This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Don't take it personally, we just need to keep a handle on things. Thank you for your contributions!

**Comment by snipe** [comment] 2023-09-21 15:21
Duplicate of #4261

**Closed as completed by snipe** 2023-09-21 15:21 UTC
