### ISSUE TITLE
Export horizontal PDF

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#10045] opened 2021-09-03 14:20 UTC
**Server (please complete the following information):**
 - Snipe-IT   Version v5.1.8 - build 6257
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
Exporting a report to PDF usually does not fit any column content, but, if we can download a landscape version, maybe we can see columns better
![Screenshot_20210903_111731](https://user-images.githubusercontent.com/2739706/132020319-65ab30b9-a8a0-4b0e-9d91-13dcbadaca31.png)

**Describe the solution you'd like**
 buttons to download a landscape or portrait version  of a PDF report

**Comment by snipe** [comment] 2021-09-11 02:01
Closed as duplicate of #10025

**Closed as completed by snipe** 2021-09-11 02:01 UTC
