### ISSUE TITLE
class="far fa-wrench" does not exist

### ISSUE THREAD

**Issue by Manschk3rl** [grokability/snipe-it#14781] opened 2024-05-29 05:16 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The warranty check url should show a little wrench symbol. But it only displays a ![image](https://github.com/snipe/snipe-it/assets/4741314/503310cc-4daa-4a0e-865a-d830a0bce444).

### Reproduction steps

1. Set the "Warranty Lookup URL" at "SNIPE-IT-URL/manufacturers".
2. Open a asset from that manufacturer.
3. Under "Info" > "Manufacturer" u should see the missing icon
![image](https://github.com/snipe/snipe-it/assets/4741314/5b3528a2-77bc-4098-9cec-6972716c2733)

### Expected behavior

if u change the class to "fa fa-wrench" or "fas fa-wrench" it works.
![image](https://github.com/snipe/snipe-it/assets/4741314/d8bb35eb-b05c-4d58-9cfa-a7464f596acd)

### Snipe-IT Version

6.4.2

### Operating System

Docker v26.0.1 with Docker Compose v2.27.0 on Ubuntu 22.04.4 LTS

### Web Server

Apache

### PHP Version

8.1.2

### Operating System

Windows 11 23H2

### Browser

Microsoft Edge

### Version

125.0.2535.51

### Error messages

```shell
The error is reproducible on the demo: https://snipeitapp.com/demo
```

**Comment by snipe** [comment] 2024-05-29 18:15
I can't reproduce this on the demo: https://demo.snipeitapp.com/hardware/2101

<img width="907" alt="Screenshot 2024-05-29 at 7 14 38 PM" src="https://github.com/snipe/snipe-it/assets/197404/2ceb588c-edc2-4690-b0af-38b9df215517">


<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/hardware/2101">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by snipe** [comment] 2024-05-29 18:16
Maybe an Edge thing? 

Update: Can reproduce in Chrome, just not Safari.

**Comment by snipe** [comment] 2024-05-29 18:23
Thanks for this - it's fixed in the upcoming v7.

**Closed as completed** 2024-05-29 18:23 UTC
Labels: :hand: bug
