### ISSUE TITLE
Category EULA is being emailed even when option in unchecked. 

### ISSUE THREAD

**Issue by morgish** [grokability/snipe-it#9449] opened 2021-04-19 05:19 UTC
#### Please confirm you have done the following before posting your bug report:

- [N] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
SNIPE is emailing the user upon check out when the Category EULA is populated BUT the " Send email to user on checkin/checkout" option is unticked. 

The Category EULA field must be empty for no email to be sent. 

**To Reproduce**
Enter text into the Category EULA and leave the "Send email to user on checkin/checkout" option unticked. 

**Expected behavior**
Email not to be sent when "Send email to user on checkin/checkout" option is unticked. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v5.1.4 build 5886 (g9f3a8a43c)
 - OS: [e.g. Ubuntu, CentOS] CentOS Linux 8 
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.2.24

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 90.0.4430.72 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by adagioajanes** [comment] 2021-12-14 22:35
I was just working on asset categories and also ran into this issue. However, I almost wouldn't call it a bug, and might call it, working by design.

The exact phrasing of the checkbox is, "Require users to confirm acceptance of assets in this category." This indicates whether or not the user has to accept that the asset has been assigned to them. It doesn't necessarily refer to the EULA.

When an EULA is filled in, whether or not the _asset_ needs to be accepted is irrelevant, as there is now an _EULA_ associated with the asset that does need to be accepted.

I think the best course of action here would be to move the checkbox up, so it is not accidently associated with the EULA settings. Additionally, I think it would be a good move to add a little note stating that, when an EULA is configured, an email will be sent to require acceptance, regardless of your other settings.

Something like this...
![image](https://user-images.githubusercontent.com/38761237/146090239-d06a3723-50f0-46ef-8456-61444353feeb.png)

I think there might be more cleanup on phrasing and positioning that can be done. But this, at a minimum, should help to resolve this issue. :)

**Closed as completed** 2022-03-24 20:08 UTC
