### ISSUE TITLE
[Feature Request]: Patch supplier_id with API

### ISSUE THREAD

**Issue by sleger-avril** [grokability/snipe-it#13632] opened 2023-09-19 12:37 UTC
### Is your feature request related to a problem? Please describe.

The API takes the supplier_id field but doesn't update the field. supplier_id is not listed in the Patch section of [/hardware/:id]

### Describe the solution you'd like

Is it possible to simply add it?

Thank you

**Comment by snipe** [comment] 2023-09-19 17:45
I can't reproduce this on develop or the main demo, or locally. `supplier_id` is accepted as fillable and has a value in the `store()` and `update()` API controllers, so without more information, I'm not sure how we can help. It might (or might not) be documented, but it is accepted. Try the API demo, you'll see that it works.

Give you've ignored the required questions we ask for to open an issue (version of PHP. version of Snipe-IT. etc), I'm closing this for now.

**Closed as completed by snipe** 2023-09-19 17:45 UTC
