### ISSUE TITLE
Signature pad is too  big and zoomed

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#8656] opened 2020-11-02 06:28 UTC
Hi, 

We are using Version v5.0.0 - build 4484 (master). 
In this version the signature pad is too big and itis not possible to sign. We tested on iPad and on PC.
Which css file should be edited?

UPDATE:

I've just updated to the Version v5.0.4 - build 5452 (master). The issue is the same
You can see the screenshot here https://ibb.co/P13gf4d
<img src="https://i.ibb.co/WBqfYFL/2-FDD702-E-2214-4-CAB-9-F9-F-0-A55-EC431346.png">

**Comment by denzfarid** [comment] 2020-11-02 07:24
+1, me too , after upgrade to v5, signature pad not sync, so very difficult
like this

Firefox version 82.0.2 (64-bit)
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/1294403/97840664-062d0880-1d17-11eb-83fb-f22615d65fbd.gif)

google chroome version 86.0.4240.111 (Official Build) (x86_64)
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/1294403/97844723-1d232900-1d1e-11eb-869d-676f4d643f60.gif)




im use this version
<img width="243" alt="gambar" src="https://user-images.githubusercontent.com/1294403/97840885-6754dc00-1d17-11eb-8275-d3861199a349.png">

**Comment by snipe** [comment] 2020-11-02 22:00
Can anyone tell me if this happens only on mobile v desktop?

**Comment by snipe** [comment] 2020-11-02 22:21
Have either of you tried upgrading to the latest tagged release?

**Comment by snipe** [comment] 2020-11-02 22:23
@Godmartinz From what I can tell, the OP's issue should only happen on mobile, so we may need to do a `@media` split on screen sizes. I'm not sure why that would have changed from v4 to v5, but the two reports from desktop users seems to be the same (the pointer being off a little, as we see in #8603)

**Comment by denzfarid** [comment] 2020-11-02 23:52
> Can anyone tell me if this happens only on mobile v desktop?

I use the desktop version, but the same thing seems to happen in the mobile version, I tried using Google Chrome with the Google Device Toolbar on the Inspect Element, and replaced it with the iPhone X device

thank you

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1294403/97931793-05d94f80-1da1-11eb-9258-3a2a73907c95.gif)

**Comment by snipe** [comment] 2020-11-02 23:52
What happens if you turn it to landscape mode on the phone?

**Comment by denzfarid** [comment] 2020-11-02 23:57
> What happens if you turn it to landscape mode on the phone?

this is when I use landscape mode on the phone
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/1294403/97932108-c2331580-1da1-11eb-85d4-ad1c8bfcfb36.gif)

**Comment by yanagha** [comment] 2020-11-03 05:13
> What happens if you turn it to landscape mode on the phone?

Hi @snipe  we tested on mobile, PC and iPad. The issue is the same. I have updated from  v5.0.0 - build 4484 to v5.0.4 - build 5452 master. The issue persists.
I think the canvas is too big.

**Comment by snipe** [comment] 2020-11-03 17:16
I think this issue is a duplicate of #8603

**Closed as completed by snipe** 2020-11-03 17:16 UTC
Labels: 📝 signature
