### ISSUE TITLE
[Feature Request]: Extra language support for asset import for Simplified Chinese

### ISSUE THREAD

**Issue by sean7084** [grokability/snipe-it#15895] opened 2024-11-28 05:11 UTC
### Is your feature request related to a problem? Please describe.

When I import csv files containing category name in Chinese, the import would fail.

### Describe the solution you'd like

I hope you may include additional language support for asset import. Also, I am new to PHP and Laravel, so I would be happy if someone can help explain why the import would fail.

**Comment by snipe** [comment] 2024-12-02 16:06
Duplicate of #15587

**Closed as completed by snipe** 2024-12-02 16:06 UTC
