### ISSUE TITLE
Column visibility are not saved per statuslabel basis

### ISSUE THREAD

**Issue by romannazarenko** [grokability/snipe-it#9638] opened 2021-05-27 12:40 UTC
#### Expected Behavior (or desired behavior if a feature request)

Column visibility are saved per statuslabel basis

-----

#### Actual Behavior

Column visibility doesn't saved after page refresh. Returns to default

-----

#### Please confirm you have done the following before posting your bug report:

- [ *] I have enabled debug mode 
- [ *] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install 
- Version of Snipe-IT you're running - v5.1.5 - build 6082 (master)
- Version of PHP you're running - 7.4.19
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - confirmed in demo

Steps to reproduce:

Create custom statuslabel
Check Show in side nav
Click on status label in side nav
Change columns visibility settings
Refresh page

**Comment by jajabro1** [comment] 2021-06-08 21:55
I can confirm this is an issue, I only noticed this because Finance reached out do to being annoyed that they had to reset their columns in the custom view they have. 

For me this is my info: 
Is this a fresh install or an upgrade? - Upgraded Install
Version of Snipe-IT you're running - v5.1.5 - build 6029 (master) - I will update and confirm the issue is happening on 6082
Version of PHP you're running - 7.4.20
Version of MySQL/MariaDB you're running
What OS and web server you're running Snipe-IT on - Ubuntu 18.04.5
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Upgraded from PHP upgrade.php. Originally installed with install.sh
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: No errors
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. No error just not expected behaviour
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - confirmed in demo
Steps to reproduce:

go to custom status label view under Assets
set or modify columns to the view you want
refresh page, or navigate away and back
all changes to column views revert
This does not happen under any of the default Status labels or the List All View.

<blockquote><img src="https://snipeitapp.com/img/desktop_snipe.png" width="48" align="right"><div><strong><a href="https://snipeitapp.com/demo">Try the Demo - Snipe-IT Open Source IT Asset Management</a></strong></div><div>Try the live demo of Snipe-IT, the best open source IT asset management system around.</div></blockquote>

**Comment by alfiewild** [comment] 2021-12-01 14:41
Also experiencing the exact same bug

**Comment by snipe** [comment] 2021-12-01 20:15
Not really sure what to advise here. It's a cookie based column visibility system. Are these folks using different computers/devices?

Sometimes plugins can get in the way, sometimes odd browser settings can get in the way, but it works for 99% of users and I haven't been able to reproduce it anywhere.

**Comment by Midnex** [comment] 2022-05-19 19:28
Having the same issue, would be great to move some of the per user settings to the database versus cookies. I log in multiple places, and would also like default views options. 

While the below fix is specifically for asset model status labels. It would work for other tables as well regarding columns.
Note this will reset all column labels for all asssetModels Columns settings.
Right click Window Inspect
Click Application Tab
Click Cookies
Delete asssetModelsTable.bs.table.columns
Close Browser, restart. it should now be fixed.

**Comment by snipe** [comment] 2022-05-19 20:19
This was fixed in later versions of v5 and remains fixed in v6.

**Closed as completed by snipe** 2022-05-19 20:19 UTC

**Comment by Midnex** [comment] 2022-05-23 21:26
> This was fixed in later versions of v5 and remains fixed in v6.

Except I was using v6 and had the issue.

https://discord.com/channels/849770616521359401/877686893549080716/976922778659848252
