### ISSUE TITLE
Saved Asset Searches

### ISSUE THREAD

**Issue by cstout1** [grokability/snipe-it#10904] opened 2022-04-05 21:40 UTC
### Snipe-IT Version

v5.4.1 - build 6746 (master)

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

Hosted

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

It would be great for speeding up productivity to be able to save searches (simple filter searches, like what's available at the top of the assets view _or_ an advanced criteria search). This would allow you to run frequently searched items with a click or two.

### Describe the solution you'd like A clear and concise description of what you want to happen.

Similar to how you have the option to have custom status labels shown in the left navigation menu, you could have your saved searches appear there as well. Or, for those of us that may have many saved searches where this would clutter the navigation menu you could choose which searches show in the menu (just like how you can for custom status labels).

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

I've considered using more custom status labels, but I'm finding that having too many causes confusion and makes it harder to actually get a concise list of whatever it is I'm looking for. For example, when I'm auditing my loaner pool of computers, they span various categories, statuses, and locations so none of those in itself works for seeing the full list across all statuses. Using a naming convention allows me to pull this list in a filter search. Any assets with the name "loaner" show when I search this and it will show me mac/pc, available/deployed, in transit, and more from this search view.

If there could be a single click for a search like this it would be very helpful in speeding up commonly referenced lists or reports.

**Comment by snipe** [comment] 2023-10-30 15:09
Duplicate of [#9884](https://github.com/snipe/snipe-it/issues/9884)

**Closed as completed by snipe** 2023-10-30 15:09 UTC
