### ISSUE TITLE
[Feature Request]: Support for Separate Serial Number For Components if Qty is more than 1

### ISSUE THREAD

**Issue by OptimusPrm9** [grokability/snipe-it#15323] opened 2024-08-17 09:32 UTC
### Is your feature request related to a problem? Please describe.

in my case we purchase multiple qty of same material having different serial number currently there is only one serial number field even if qty is more than 1.

### Describe the solution you'd like

ability to add multiple serial number for same model of component which can further issued to user with proper tacking.

**Comment by snipe** [comment] 2024-08-17 09:34
Duplicate of #4421,  #9015, #13722

**Closed as completed by snipe** 2024-08-17 09:34 UTC
