### ISSUE TITLE
Bulk checkout for assets and accessories

### ISSUE THREAD

**Issue by yanagha** [grokability/snipe-it#9247] opened 2021-03-04 13:36 UTC
Hi, 

Is there a way to check out more than one assets and accessories at the same time? 
For example, we have 100 keyboards in the storage and we want to assign 50 of them to a location computer lab. We need to click the checkout button 50 times. We are using Version v5.1.2 - build 5847 (master). Server OS CentOS 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux, webserver apache, PHP 7.3.27

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bwint** [comment] 2022-04-27 07:50
I'm the exact same position for accessories.
I often want to check out more than one accessory item and it is currently very frustrating that you only can do it one by one.

In general such a feature would also be nice for consumables an licenses. Probably for all non-asset items.

**Comment by snipe** [comment] 2022-07-13 17:00
Duplicate of #6928

**Closed as completed by snipe** 2022-07-13 17:00 UTC
