### ISSUE TITLE
[Feature Request]: Need to enable Custom Fields for Licenses

### ISSUE THREAD

**Issue by 00717747** [grokability/snipe-it#15881] opened 2024-11-25 07:42 UTC
### Is your feature request related to a problem? Please describe.

Need to enable Custom Fields for Licenses

### Describe the solution you'd like

Need to enable Custom Fields for Licenses

### Describe alternatives you've considered

Need to enable Custom Fields for Licenses

### Additional context

Need to enable Custom Fields for Licenses

**Comment by snipe** [comment] 2024-12-02 16:33
Duplicate of https://github.com/snipe/snipe-it/issues/4261

**Closed as completed by snipe** 2024-12-02 16:33 UTC
