### ISSUE TITLE
API Result Bug

### ISSUE THREAD

**Issue by Oscillometer** [grokability/snipe-it#8335] opened 2020-08-17 23:30 UTC
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When performing a **/statuslabels/:id/assetlist** API call all assets return NULL in the assiged_to field.
This occurs on all assets, but the correct value is returned when any GET asset API calls.

**To Reproduce**
Perform **/statuslabels/:id/assetlist** API call for any status label that contains assets which are checked out to someone

All assets will return NULL in the assigned_to field even after validating asset is correctly assigned

**Expected behavior**
Receive the same info from **/statuslabels/:id/assetlist** API call as is provided from any of the GET asset api calls.

**Screenshots**
Below is the broken API results from the **/statuslabels/:id/assetlist** API call
![Broken](https://user-images.githubusercontent.com/58958957/90453915-11c14980-e0af-11ea-8af7-77794448e882.png)

Below is the expected API results, as retrieved from **/hardware/bytag/:asset_tag**
![Expected](https://user-images.githubusercontent.com/58958957/90453921-14bc3a00-e0af-11ea-8772-3ca2ce0fec9f.png)

**Server (please complete the following information):**
Server is hosted and maintained by Snipe directly, exact info not known.

**Comment by snipe** [comment] 2020-08-26 03:30
I can't reproduce this locally on master...

<img width="629" alt="Screen Shot 2020-08-25 at 8 29 10 PM" src="https://user-images.githubusercontent.com/197404/91252118-bed03d80-e711-11ea-8be3-8f286d3cb961.png">

**Comment by snipe** [comment] 2020-08-26 03:30
Actually, I just realized I misread your issue. Let me check into this.

**Comment by snipe** [comment] 2020-08-26 03:38
This is now fixed on master and will be in the next tagged release.

**Closed as completed** 2020-08-26 03:38 UTC
Labels: :question:  not sure if bug
