### ISSUE TITLE
View Model

### ISSUE THREAD

**Issue by rshingala** [grokability/snipe-it#9178] opened 2021-02-22 09:00 UTC
#### Expected Behavior (or desired behavior if a feature request)

Number of item shown on page filter  1 of 10 or 1 of 20. After selecting item to show 10, filter has disappeared from page and now only 10 items showing. Export to CSV / PDF also shows 10 items rather then all.  When select view and type any item name then only that particular item appears.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

Not listed in bug tracking

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh
- Version of Snipe-IT you're running - 5.1.1
- Version of PHP you're running - 7.3
- Version of MySQL/MariaDB you're running - Not sure, installed with Snipe IT
- What OS and web server you're running Snipe-IT on - CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Seeting --View Models
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console - No.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo - Yes, same error on Demo too.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jbloomfield80** [comment] 2021-02-22 20:58
We are seeing the same issue.  The number of rows per page in the Asset Models section is limited to 10 or 20 and does not allow for navigating to other pages.  When changing from 20 to 10, the entire option to change the number per row disappears permanently, and you are stuck with only seeing 10.  You can still search and sort.  See attached images.  There are over 50 Asset Models entered, but not all are even visible on this page.  I have also attached an image of the Asset Manufacturer page as a comparison to reference what it should be like.  Thanks!
![Asset Manufacturers](https://user-images.githubusercontent.com/75686387/108769280-66da8e00-751e-11eb-8abe-044162c1fc03.png)
![Asset Models](https://user-images.githubusercontent.com/75686387/108769288-693ce800-751e-11eb-9485-47be3aae054d.png)

**Comment by nghia-dang** [comment] 2021-02-23 14:19
seems related to https://github.com/snipe/snipe-it/issues/9107

**Comment by snipe** [comment] 2021-02-25 21:06
Duplicate of #9085

**Closed as completed by snipe** 2021-02-25 21:06 UTC
