### ISSUE TITLE
Location report does not include child locations

### ISSUE THREAD

**Issue by francogp** [grokability/snipe-it#10030] opened 2021-09-01 12:26 UTC
**Server (please complete the following information):**
 - Snipe-IT  Version v5.1.8 - build 6257 (develop)
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version 7.4

**Is your feature request related to a problem? Please describe.**
When I do a report by location, it should ask me if I want to include all SUB-LOCATIONS. I need to do a report by building, but it report nothing because all items are on sub-locations.

**Describe the solution you'd like**
Add a checkbox to allow the user to create a report including all sublocations, when filtering by location

**Comment by snipe** [comment] 2021-09-01 15:56
Duplicate of #4546

**Closed as completed by snipe** 2021-09-01 15:56 UTC
