### ISSUE TITLE
Google Script Create Users

### ISSUE THREAD

**Issue by jlopeztech** [grokability/snipe-it#14002] opened 2023-12-05 23:09 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The API call via Google Scripts cannot create a user. I can query users but when using the sample javascript it seems as if the payload is not delivered.

```json
{
   "status":"error",
   "messages":{
      "first_name":[
         "The first name field is required."
      ],
      "username":[
         "The username field is required unless ldap import is in 1."
      ],
      "password":[
         "The password field is required."
      ]
   },
   "payload":null
}
```

### Reproduction steps

1. Run attached code in Google script attached to google sheet to create a user
2. Review error message in a1 of current sheet
3.
...
the 

### Expected behavior

Create a sample user 

### Screenshots

```js
function test2() {
  var options = {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      Authorization: 'Bearer YOUR_AUTH_TOKEN', // Replace with your actual authorization token
      'Content-Type': 'application/json',
    },
    payload: JSON.stringify({
      groups: null,
      vip: false,
      first_name: 'Bob',
      username: 'bsmith@rvusd.org',
      password: '12345678',
      password_confirmation: '12345678',
      email: 'bsmith@rvusd.org',
      last_name: 'Smith',
    }),
  };

  var response = UrlFetchApp.fetch('XXXX/api/v1/users', options);

  if (response.getResponseCode() === 200) {
    var content = response.getContentText();
    SpreadsheetApp.getActiveSpreadsheet().getActiveSheet().getRange("a1").setValue(content);
    var json = JSON.parse(content);
  } else {
    Logger.log('Error - HTTP Response Code: ' + response.getResponseCode());
    Logger.log('Error Content: ' + response.getContentText());
  }
}
```

### Snipe-IT Version

v6.2.4-pre build 12090 (g776b16d37)

### Operating System

Hosted

### Web Server

Hosted

### PHP Version

8.1.23

### Operating System

Mac

### Browser

Chrome

### Version

119

### Error messages

```json
{
  "status":"error",
  "messages":
      {
           "first_name":["The first name field is required."],
           "username":["The username field is required unless ldap import is in 1."],
           "password":["The password field is required."]
       },
    "payload":null
}
```

**Comment by uberbrady** [comment] 2023-12-12 11:50
Since `options` is defined in the `test2()` function, is it possible that it is "falling out of scope?" E.g., what happens if you declare `options` at the root level, without the test2 function "wrapper"?

**Comment by snipe** [comment] 2023-12-12 12:15
### Obviously, never include your bearer token in example code here - I can do that here since the develop bearer token is already available via the API code samples in the API docs.

I actually can't reproduce this error. Using the live develop demo, I added this script:

```js
function test2() {
  var options = {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZTU2MDc0MjVmYjM5YTEwYjFjNTZlZTAxMTBmZDk4ZjQ0ZjVjODMzYjcxZWVhYjZlNDk1NGMwOThlY2YzMzU2MDY4Mzg4MmFhMDMzOTAzNzciLCJpYXQiOjE2MzI4NjU5MTgsIm5iZiI6MTYzMjg2NTkxOCwiZXhwIjoyMjY0MDIxNTE4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.LgGVzyH67IRhXvccHd4j2Dn6TDuIuQTBoo30_wD9jPehy8v_h0xBmE1-dOUBRJyeJOI8B4gwPeALsWaudpGj9Lb5qWAtKV7eYtH9IYQKoLF_iHgOGXnAUcNwID6zBU_YyLNSI6gp8zjutLJias33CBLsHy5ZRNpxVibVrZouJ_HjYuIYbtZyLus-KFFeibtZoPiTWOeHhQFD37MR6ifx4dBqT37fN-xDS99mONtrkAplEIou5aSO1oZ4IlJIPCUyA1lixPgpn1YU7PxiBDZp1teeugD0WEmrAqxRS2I0bH4qPsuTsrVXS_lo87Sf5LBGLW7lGHKqyYH6J47OZOM0K-SrxLKtE1ww8jyLBgnnxH0lJHRLCBiwUnL5ZGTUmiOysUA-wSJ6s78o8Pc-ec6bpBvAlelHdiQ-wslE7gzEJDptbejFg-75b_CEwgJYh7J2D18ul6Qu5EFCUEgt033mm04dgVk0isWTDt6EW5ZvTo5Qhr1LY0YnEIXCTqIRN-BSQjL55sZaCrtwR_21bnBGgniyI5MRDYblFawVmFKroeClCpSjBo9vi66akdD5hjpvx67RL3r33BZQhEXmPifUPNH5wP_U-IHGFUD99TJk2c1awF0RASveZRLSunbJb1x6hGAVUaIvQV4r2quWzXqYyKLph9kGTyJYrb6iJtH5smE', 
      'Content-Type': 'application/json',
    },
    payload: JSON.stringify({
      groups: null,
      vip: false,
      first_name: 'Bob',
      username: 'bsmith@rvusd.org',
      password: '12345678',
      password_confirmation: '12345678',
      email: 'bsmith@rvusd.org',
      last_name: 'Smith',
    }),
  };

  var response = UrlFetchApp.fetch('https://develop.snipeitapp.com/api/v1/users', options);

  if (response.getResponseCode() === 200) {
    var content = response.getContentText();
    SpreadsheetApp.getActiveSpreadsheet().getActiveSheet().getRange("a1").setValue(content);
    var json = JSON.parse(content);
  } else {
    Logger.log('Error - HTTP Response Code: ' + response.getResponseCode());
    Logger.log('Error Content: ' + response.getContentText());
  }
}
```

<img width="1698" alt="Screenshot 2023-12-12 at 12 11 56 PM" src="https://github.com/snipe/snipe-it/assets/197404/af30e79a-e17b-472f-b29c-bb43eb3b7601">

<img width="1699" alt="Screenshot 2023-12-12 at 12 13 27 PM" src="https://github.com/snipe/snipe-it/assets/197404/37949f4e-f684-476e-855d-b48ad527f679">

and add it to Google sheets under `Extensions > App Scripts`, the user does get created:

The response in sheets is:

```json
    {
   "status":"success",
   "messages":"User was successfully created.",
   "payload":{
      "id":60,
      "avatar":"\/\/gravatar.com\/avatar\/4319b12b3b909b465c43550ee035fab6",
      "name":"Bob Smith",
      "first_name":"Bob",
      "last_name":"Smith",
      "username":"bsmith@rvusd.org",
      "remote":false,
      "locale":null,
      "employee_num":null,
      "manager":null,
      "jobtitle":null,
      "vip":false,
      "phone":null,
      "website":null,
      "address":null,
      "city":null,
      "state":null,
      "country":null,
      "zip":null,
      "email":"bsmith@rvusd.org",
      "department":null,
      "location":null,
      "notes":null,
      "permissions":null,
      "activated":false,
      "autoassign_licenses":false,
      "ldap_import":false,
      "two_factor_enrolled":false,
      "two_factor_optin":false,
      "assets_count":0,
      "licenses_count":0,
      "accessories_count":0,
      "consumables_count":0,
      "company":null,
      "created_by":null,
      "created_at":{
         "datetime":"2023-12-12 04:10:32",
         "formatted":"Tue Dec 12, 2023 4:10AM"
      },
      "updated_at":{
         "datetime":"2023-12-12 04:10:32",
         "formatted":"Tue Dec 12, 2023 4:10AM"
      },
      "start_date":null,
      "end_date":null,
      "last_login":null,
      "deleted_at":null,
      "available_actions":{
         "update":true,
         "delete":true,
         "clone":true,
         "restore":false
      },
      "groups":null
   }
}
```

**Comment by snipe** [comment] 2023-12-18 18:08
As I mentioned, I was unable to reproduce this issue, but if you want to create users from a spreadsheet and for some reason you don't want to use the CSV importer, we have a script to do that for you: https://github.com/grokability/google-apps-scripts-for-snipe-it/tree/main/create-users

**Closed as completed by snipe** 2023-12-18 18:08 UTC
