### ISSUE TITLE
custom fields for models

### ISSUE THREAD

**Issue by vapier** [grokability/snipe-it#10084] opened 2021-09-15 05:49 UTC
### Snipe-IT Version

5.2.0

### Operating System

Linux

### Web Server

Apache

### PHP Version

7.4

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

custom fieldsets are nice for settings that change on a per-asset basis, but there are settings that are the same across all models.  currently, custom fields may only be applied (via fieldsets) to assets.

for example, i want to track on a per-model basis:
* where to buy the model exactly
  * the supplier info is much higher level.  consider something like Amazon or DigiKey -- the supplier info would be the base page, but the model will have a much more specific & useful URL.
* links to manuals and other documentation
  * could be PDF's or YouTube videos
* support information
  * the manufacturer info might be sufficient, but like ordering/supplier, there might be model-specific info
  * maybe the manufacturer went out of business, but another business has picked up support for a subset of devices

some of these might be useful to integrate as standard fields, but being able to add arbitrary custom fields at the model level would avoid bikeshedding as to what could/should be official.

### Describe the solution you'd like A clear and concise description of what you want to happen.

the model edit page should have a section to add arbitrary number of additional fields

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

using the existing "Notes" text field is painful for structured things like URIs & phone numbers & e-mails & such

**Comment by snipe** [comment] 2021-09-15 06:02
Closing as duplicate of #4261

**Closed as completed by snipe** 2021-09-15 06:02 UTC
