### ISSUE TITLE
Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified

### ISSUE THREAD

**Issue by megairwalk** [grokability/snipe-it#10234] opened 2021-10-26 20:20 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. . #0 C:\inetpub\wwwroot\SnipeIT\vendor\spatie\db-dumper\src\DbDumper.php(263): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process)) #1 C:\inetpub\wwwroot\SnipeIT\vendor\spatie\db-dumper\src\Databases\MySql.php(203): Spatie\DbDumper\DbDumper->checkIfDumpWasSuccessFul(Object(Symfony\Component\Process\Process), 'C:\\inetpub\\wwwr

### Reproduction steps

1.Open Snipe-IT>Admin Settings
2.Backups>Generate
3.
...

### Expected behavior

I was hoping this would run a full backup of my Snipe-IT database

### Screenshots

![2021-10-26_14-19-11](https://user-images.githubusercontent.com/93224204/138954745-304fec9e-cdf8-4639-84c6-a0750a12f4d8.png)

### Snipe-IT Version

5.1.8 Build 6148

### Operating System

Windows Server 2019 Standard

### Web Server

IIS

### PHP Version

7.3.29

### Operating System

Windows

### Browser

Chrome

### Error messages

```shell
Cannot reproduce in demo
 Error: This feature has been disabled for the demo installation.
```

### Additional context

Fresh install several months ago. First time attempting to backup the database

**Comment by snipe** [comment] 2021-10-29 19:24
Closing as duplicate of #4862

**Closed as completed by snipe** 2021-10-29 19:24 UTC

**Comment by megairwalk** [comment] 2021-11-03 17:15
I followed all steps in case #4862 but i am still unable to generate a backup. 
I am unable to run backup via GUI or php artisan backup:run
I verified the permissions on app/backups and IIS_IUSRS has full control
I verified the permissions on c:\windows\temp and IIS_IUSRS has full control

**Comment by megairwalk** [comment] 2021-11-03 17:18
# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=password
DB_PREFIX=null
DB_DUMP_PATH="C:\\PROGRA~1\\MARIAdb 10.1\\bin"
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

**Comment by HoangNi133** [comment] 2024-03-21 09:32
I'm also having the same situation, I've tried everything everyone suggested but it doesn't seem to work :( 
![Capture](https://github.com/snipe/snipe-it/assets/164329797/6c6c6af5-dd34-4aad-8cb3-99fa567cb5df)
