### ISSUE TITLE
Importing images over 2MB not working for asset models

### ISSUE THREAD

**Issue by Doneven2012** [grokability/snipe-it#9492] opened 2021-04-26 20:18 UTC
#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I try to import an image that's more than 2mb, I get an error. (See screenshot).

**To Reproduce**
1. Go to any asset model
2. Click on 'edit'
3. Scroll down to 'Upload Image'
4. Import an image that's more than 2mb. 
5. I get an error saying  "Accepted filetypes are jpg, webp, png, gif, and svg. Max upload size allowed is 8M. Upload is 2.15 MB." even though the image chosen is a .webp image and it's way lower than 8MB. 

**Expected behavior**
The image imports and is tied to the asset model.

**Screenshots**
![image](https://user-images.githubusercontent.com/37813014/116142909-74400000-a6a8-11eb-90c2-aba01ecb1339.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v5.1.4
 - OS: Ubuntu 20.04
 - Web Server: Apache
 - PHP Version: PHP 7.4.3

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Brave 
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Mix 2
 - OS: Android 9.0
 - Browser: Chrome
 - Version: Latest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include the output from `php -m` (this should display what modules you have enabled.)

I don't see anything pop up in the debug console of Snipe-IT.

If I save after trying to upoad the image, I get this in Brave's console: 
![image](https://user-images.githubusercontent.com/37813014/116144208-0dbbe180-a6aa-11eb-99be-581d46e4659c.png)

The issue doesn't happen in the demo, but the demo seems to have a massive 1024M upload limit for asset model image uploads.

These are my PHP modules from php -m: 
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

This is a fresh install of 5.1.4 which was installed with install.sh as far as I can remember, but it was converted to git soon after installing using the guide: https://snipe-it.readme.io/docs/switching-to-a-git-install. I installed it and filled it with assets, accessories, and users from LDAP. I haven't modified it in any way.

In case it might be useful, that's the image I'm trying to upload on an asset model. (Had to zip it since GitHub doesn't support uploading webp.
[ca-uhd-ku6290-un70ku6290fxzc-001-front-black.zip](https://github.com/snipe/snipe-it/files/6379984/ca-uhd-ku6290-un70ku6290fxzc-001-front-black.zip)

This same image, if resized, uploads perfectly at 1.97mb but not at 2.04mb. Tested with a png image, same thing. Same thing if I use my phone to directly take and upload a picture from the web interface. As soon as it's over 2mb, bug.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by novastream** [comment] 2021-04-26 21:53
I think this is a Brave related issue. I have a similar issue when uploading a image a new tab is opened. Have you tried disabled the Brave shield?

**Comment by Doneven2012** [comment] 2021-04-26 21:55
Hi there, that's always my first reaction to any bug on any web page, disabling the shield ! So I did try that. I had the same reaction when using snipe it from Google chrome on my phone.

________________________________

**Comment by snipe** [comment] 2021-04-26 22:45
I think this might be a duplicate of #9440

**Comment by Doneven2012** [comment] 2021-04-26 22:57
I probably skipped over that ticket thinking it was about not being able to upload images at all. If you prefer, I can continue following from that other ticket and add info to it if necessary. 

Just to add to that ticket, I set the two variables mentionned there to 8M and restart Apache, then the whole server just to make sure, and it didn't seem to change anything. But "upload_max_filesize" was indeed set on "2M" by default.

**Comment by snipe** [comment] 2021-08-18 04:41
Let's keep the convo moving over in that ticket - thanks :)

**Closed as completed by snipe** 2021-08-18 04:41 UTC
