### ISSUE TITLE
Asset Model Uniqueness 

### ISSUE THREAD

**Issue by jandjkes** [grokability/snipe-it#15419] opened 2024-08-29 19:44 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to create a new asset model, getting error "The name has already been taken." on ASSET MODEL NAME. I am reusing model name and manufacturer, but the model number is different. I looked on another post and verified that was the uniqueness requirements.

https://github.com/snipe/snipe-it/issues/1572 

I also used to be able to do this, as evident by having multiple asset models with name 'OptiPlex', manufacturer 'dell', and different model numbers.

### Reproduction steps

1. Copy existing asset model
2. Change the model number to something different
3. Save
...

### Expected behavior

A new asset model with a different model number should be created.

### Screenshots

![Screenshot 2024-08-29 144151](https://github.com/user-attachments/assets/18ef65c8-38c9-4c2b-9bbd-cbe97912603d)
![Screenshot 2024-08-29 144208](https://github.com/user-attachments/assets/fd49f957-7e29-4803-89ed-78155c552338)

### Snipe-IT Version

We are on Version v7.0.11 - build 14904 (master) CLOUD

### Operating System

Cloud

### Web Server

Cloud

### PHP Version

Cloud

### Operating System

W11

### Browser

chrome

### Version

up to date

**Comment by snipe** [comment] 2024-08-29 20:10
Duplicate of #15405

**Closed as completed by snipe** 2024-08-29 20:10 UTC

**Comment by jandjkes** [comment] 2024-08-29 20:48
So this is fixed on a new build (15044)? How do we get to the build that the Demo is on?

**Comment by snipe** [comment] 2024-08-29 20:58
To get the latest, update to latest on master using upgrade.php

**Comment by jandjkes** [comment] 2024-08-29 21:14
Okay, I want to preface that I was not the one to set up any of this. I checked our subscription and it says we have basic hosting. Not sure that means I can do what you just recommended. Can I even access the server/root to run a command?

**Comment by snipe** [comment] 2024-08-29 21:23
No, you can't, but you can open a ticket at support@snipeitapp.com and we'll get you updated. Just make sure you send us the subdomain you're using :)

**Comment by jandjkes** [comment] 2024-08-29 21:24
Okay, will do. Thank you.
