### ISSUE TITLE
Username repeats on user display when window is resized.

### ISSUE THREAD

**Issue by a8bit** [grokability/snipe-it#12455] opened 2023-02-02 18:54 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

If you are on the Asset list and you resize the browser window the username of all the users on the screen gets repeated. Keep resizing, it keeps duplicating. It doesn't happen to the users' full name, just the username and it doesn't happen to assets allocated to a location. Here's a screenshot after I've resized the window a few times. 

![2023-02-02 12_24_09-All Assets __ Asset DB and 3 more pages - Boz - Microsoft​ Edge](https://user-images.githubusercontent.com/12753/216416344-930893ef-81fb-489d-ab6e-d1d90c56f926.png)

Refresh the page to go back to one instance of username in the brackets.

### Reproduction steps

1. Resize the screen while the asset list is displayed.
2.
3.
...

### Expected behavior

The screen resizes and only displays the username once. 

### Screenshots

![2023-02-02 12_24_09-All Assets __ Asset DB and 3 more pages - Boz - Microsoft​ Edge](https://user-images.githubusercontent.com/12753/216417417-4e00707e-02ae-4a83-9944-dd8608de0d54.png)

### Snipe-IT Version

6.0.14

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.10

### Operating System

Windows 11

### Browser

Edge

### Version

109.0.1518.70 (Official build) (64-bit)

### Error messages

```shell
It doesn't happen in the demo version. I don't get any error messages at all .

boz@cmdb:/var/www/html/snipeit$ php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

### Additional context

This is a fresh install, Ubuntu in a VM then the install script for snipe-it. 
Users are populated from an AD server.

**Comment by snipe** [comment] 2023-02-02 19:08
This is a duplicate of #12430 and #12432 and is already fixed on master.

**Closed as completed by snipe** 2023-02-02 19:08 UTC
