### ISSUE TITLE
Allow All Statuses to Show at Checkout

### ISSUE THREAD

**Issue by twinsmom71** [grokability/snipe-it#10075] opened 2021-09-13 15:10 UTC
### Snipe-IT Version

5.2.0

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

7.4.3

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I am frustrated that all statuses are not available when checking out an asset.  I shouldn't have to click on the asset twice to move it out of inventory and assign it to a user?  I submitted a ticket thinking this was a setup issues but was told it's by design.

### Describe the solution you'd like A clear and concise description of what you want to happen.

I would like ALL statuses, including custom statuses, to be available when checking out an asset

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

I spoke with support and they said this is by design

### Additional context Add any other context or screenshots about the feature request here.

![Snipeit improvement](https://user-images.githubusercontent.com/79875860/133109417-f2ae8b2a-418f-43a9-b1c0-ca3b4ebc7896.jpg)

**Comment by snipe** [comment] 2021-09-13 15:17
This is by design and we have no plans to change that. Create a new deployable status if that’s what will work for your workflow, but you should not be able to check out something and assign it to a non-deployable status. If it’s broken, archived, etc, you shouldn’t be checking it out. That’s the whole point of status types.

**Closed as completed by snipe** 2021-09-13 15:17 UTC
