### ISSUE TITLE
Bulk checkout of accessories #7351

### ISSUE THREAD

**Issue by mngala** [grokability/snipe-it#8930] opened 2020-12-21 05:41 UTC
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
 
- My feature request is  to issuexactly the same as  #7351

**Comment by snipe** [comment] 2022-07-13 17:00
Duplicate of #6928

**Closed as completed by snipe** 2022-07-13 17:00 UTC
