### ISSUE TITLE
Docker image missing tag v5.2.0

### ISSUE THREAD

**Issue by fabricat** [grokability/snipe-it#10078] opened 2021-09-13 19:39 UTC
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

The newest Snipe-IT official Docker image `snipe/snipe-it:v5.2.0` is not available (see[Docker Hub](https://hub.docker.com/r/snipe/snipe-it/tags/))

### Reproduction steps

1. `docker pull snipe/snipe-it:v5.2.0`
2. got error `Error response from daemon: manifest for snipe/snipe-it:v5.2.0 not found: manifest unknown: manifest unknown`

### Expected behavior

Image `snipe/snipe-it:v5.2.0` should be available

### Snipe-IT Version

5.2.0

### Operating System

n/a (Docker image)

### Web Server

n/a

### PHP Version

embedded

**Comment by snipe** [comment] 2021-09-13 20:13
Closed as duplicate of #10065

**Closed as completed by snipe** 2021-09-13 20:13 UTC
